// data-uk.js - UK Universities - Undergraduate Programs Only
// v4.0 - All programs are bachelor's level (BSc/BA/BEng/LLB/MBBS etc.)
(function(){
var D = [
// ============ RUSSELL GROUP TOP ============
{id:"oxford",n:"牛津大学",e:"University of Oxford",c:"Oxford",r:3,cat:"russell",
 ll:{std:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:24,w:24,s:25,l:22}},
     high:{ielts:{t:7.5,r:7,w:7,s:7,l:7},toefl:{t:110,r:24,w:24,s:25,l:22}}},
 pol:{nt:"suspended",mb:false,v:"2y",note:"暂停接受2026年1月21日起的新托福申请 / Paused new TOEFL from 21 Jan 2026"},
 fee:{ug:"GBP 33,050-48,620",currency:"GBP"},
 living:"GBP 13,000-17,000/yr",
 visa:{psw:"2yr",note:"毕业生签证2年工作许可 / Graduate Route visa 2yr post-study work"},
 ddl:{fall:"Oct 15 (UCAS deadline for Oxford)"},
 schol:["Clarendon Fund","Rhodes Scholarship","Oxford-China Scholarship"],
 materials:["UCAS","PS","Admissions test","Interview","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA",note:"建议数学+进阶数学；需要MAT考试 / Maths + further maths recommended; MAT test required"},
  {c:"eng",l:"std",g:"A*A*A",note:"工程科学；需要PAT考试 / Engineering Science; PAT test required"},
  {c:"math",l:"std",g:"A*A*A",note:"需要MAT考试 / MAT test required"},
  {c:"phys",l:"std",g:"A*AA",note:"需要PAT考试 / PAT test required"},
  {c:"chem",l:"std",g:"A*A*A",note:"化学理学士/硕士 / Chemistry BSc/MChem"},
  {c:"bio",l:"std",g:"A*AA",note:"生物科学 / Biological Sciences"},
  {c:"med",l:"high",g:"A*AA",note:"需要BMAT考试；IB 39+ / BMAT required; IB 39+"},
  {c:"law",l:"high",g:"AAA",note:"需要LNAT考试 / LNAT test required"},
  {c:"econ",l:"std",g:"A*AA",note:"经济与管理；需要TSA考试 / Economics & Management; TSA test"},
  {c:"hist",l:"high",g:"AAA",note:"需要HAT考试 / HAT test required"},
  {c:"psych",l:"std",g:"A*AA",note:"实验心理学；需要TSA考试 / Experimental Psychology; TSA test"},
  {c:"phil",l:"high",g:"AAA",note:"哲学政治经济学(PPE) / Philosophy Politics Economics (PPE)"},
  {c:"ling",l:"high",g:"AAA",note:"现代语言 / Modern Languages"},
  {c:"ir",l:"high",g:"AAA",note:"提供政治学方向 / Politics sub-fields available"}
]},

{id:"cambridge",n:"剑桥大学",e:"University of Cambridge",c:"Cambridge",r:2,cat:"russell",
 ll:{def:{ielts:{t:7.5,r:7,w:7,s:7,l:7},toefl:{t:110,r:25,w:25,s:25,l:25}}},
 pol:{nt:"suspended",mb:false,v:"2y",note:"暂停接受新托福申请 / Paused new TOEFL"},
 fee:{ug:"GBP 33,825-61,000",currency:"GBP"},
 living:"GBP 13,000-17,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Oct 15 (UCAS)"},
 schol:["Cambridge Trust","Gates Cambridge Scholarship","College-specific awards"],
 materials:["UCAS","PS","Admissions test","Interview","Transcript","SAQ"],
 p:[
  {c:"cs",l:"def",g:"A*A*A",note:"建议参加TMUA考试；IB 42+ / TMUA test recommended; IB 42+"},
  {c:"eng",l:"def",g:"A*A*A",note:"工程学；需要ENGAA考试 / Engineering; ENGAA test required"},
  {c:"math",l:"def",g:"A*A*A",note:"需要STEP考试；进阶数学必须 / STEP required; further maths essential"},
  {c:"phys",l:"def",g:"A*A*A",note:"自然科学（物理方向） / Natural Sciences (Physical)"},
  {c:"chem",l:"def",g:"A*A*A",note:"自然科学（化学方向） / Natural Sciences (Chemistry)"},
  {c:"bio",l:"def",g:"A*A*A",note:"自然科学（生物方向） / Natural Sciences (Biological)"},
  {c:"med",l:"def",g:"A*A*A",note:"需要BMAT考试；IB 40-42 / BMAT required; IB 40-42"},
  {c:"law",l:"def",g:"A*AA",note:"可能需要LNAT考试 / LNAT may be required"},
  {c:"econ",l:"def",g:"A*A*A",note:"经济学；建议参加TMUA考试 / Economics; TMUA recommended"},
  {c:"hist",l:"def",g:"A*AA"},
  {c:"arch",l:"def",g:"A*AA",note:"建筑学；需要作品集 / Architecture; portfolio required"},
  {c:"vet",l:"def",g:"A*AA",note:"兽医学 / Veterinary Medicine"},
  {c:"psych",l:"def",g:"A*A*A",note:"心理与行为科学 / Psychological & Behavioural Sciences"}
]},

{id:"imperial",n:"帝国理工学院",e:"Imperial College London",c:"London",r:6,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:92,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"accepted",mb:false,v:"2y"},
 fee:{ug:"GBP 36,700-49,400",currency:"GBP"},
 living:"GBP 15,000-18,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine"},
 schol:["President's UG Scholarship","Imperial Bursary","Department-specific awards"],
 materials:["UCAS","PS","Interview (some)","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*A*A",note:"需要MAT考试；IB 39-41 / MAT test; IB 39-41"},
  {c:"ee",l:"std",g:"A*AA",note:"电子与电气工程 / Electronic & Electrical Engineering"},
  {c:"me",l:"std",g:"A*A*A",note:"机械工程 / Mechanical Engineering"},
  {c:"ce",l:"std",g:"A*AA",note:"土木工程 / Civil Engineering"},
  {c:"math",l:"std",g:"A*A*A",note:"进阶数学必须；IB 39-41 / Further maths required; IB 39-41"},
  {c:"phys",l:"std",g:"A*A*A"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA",note:"生物科学/生物化学 / Biological Sciences / Biochemistry"},
  {c:"med",l:"high",g:"A*AA",note:"需要BMAT/UCAT考试；IB 38+ / BMAT/UCAT; IB 38+"},
  {c:"ds",l:"std",g:"A*AA",note:"数学与统计学 / Mathematics with Statistics"},
  {c:"ai",l:"std",g:"A*A*A",note:"计算（人工智能与机器学习方向） / Computing (AI & ML specialism)"},
  {c:"env",l:"std",g:"AAA",note:"地球科学与工程 / Earth Science & Engineering"}
]},

{id:"ucl",n:"伦敦大学学院",e:"University College London",c:"London",r:9,cat:"russell",
 ll:{l1:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:92,r:24,w:24,s:20,l:20}},
     l2:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:96,r:24,w:24,s:22,l:22}},
     l3:{ielts:{t:7.0,r:7,w:7,s:7,l:7},toefl:{t:100,r:25,w:25,s:23,l:23}},
     l4:{ielts:{t:7.5,r:7,w:7,s:7,l:7},toefl:{t:109,r:27,w:27,s:23,l:23}},
     l5:{ielts:{t:8.0,r:8,w:8,s:8,l:8},toefl:{t:110,r:29,w:29,s:23,l:23}}},
 pol:{nt:"published",mb:false,v:"2y"},
 fee:{ug:"GBP 28,500-42,000",currency:"GBP"},
 living:"GBP 15,000-18,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine"},
 schol:["UCL Global UG Scholarship","Denys Holland Scholarship","Faculty-specific bursaries"],
 materials:["UCAS","PS","Transcript","Portfolio (some)"],
 p:[
  {c:"cs",l:"l1",g:"A*A*A",note:"英语1级要求；IB 40 / Level 1 English; IB 40"},
  {c:"ee",l:"l1",g:"A*AA",note:"电子与电气工程 / Electronic & Electrical Engineering"},
  {c:"arch",l:"l2",g:"AAB",note:"巴特莱特建筑学院；需要作品集 / Bartlett School; portfolio required"},
  {c:"math",l:"l1",g:"A*A*A",note:"进阶数学必须 / Further maths required"},
  {c:"phys",l:"l1",g:"A*A*A"},
  {c:"chem",l:"l1",g:"AAA"},
  {c:"bio",l:"l1",g:"AAA"},
  {c:"med",l:"l5",g:"A*AA",note:"需要UCAT；英语5级要求；IB 39 / UCAT; Level 5 English; IB 39"},
  {c:"law",l:"l4",g:"A*AA",note:"需要LNAT；英语4级要求 / LNAT; Level 4 English"},
  {c:"econ",l:"l2",g:"A*AA"},
  {c:"psych",l:"l3",g:"A*AA"},
  {c:"edu",l:"l3",g:"ABB",note:"教育学院 - 教育学顶尖 / IOE - top ranked education"},
  {c:"stat",l:"l1",g:"A*AA",note:"统计科学 / Statistical Science"},
  {c:"ling",l:"l4",g:"ABB",note:"语言学 / Linguistics"},
  {c:"hist",l:"l4",g:"AAA"},
  {c:"phil",l:"l4",g:"AAA"},
  {c:"media",l:"l3",g:"AAB",note:"信息管理/数字媒体 / Information Management / Digital Media"}
]},

{id:"lse",n:"伦敦政治经济学院",e:"LSE",c:"London",r:50,cat:"russell",
 ll:{std:{ielts:{t:7.0,r:7,w:7,s:7,l:7},toefl:{t:107,r:25,w:25,s:24,l:24}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 26,184-38,736",currency:"GBP"},
 living:"GBP 15,000-18,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["LSE UG Support Scheme","LSE Financial Support Office awards"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"econ",l:"std",g:"A*AA",note:"经济学理学士；数学A*必须；IB 38 / Economics BSc; maths A* essential; IB 38"},
  {c:"fin",l:"std",g:"A*AA",note:"金融学理学士；数学A*必须 / Finance BSc; maths A* essential"},
  {c:"acct",l:"std",g:"AAA",note:"会计与金融学理学士 / Accounting & Finance BSc"},
  {c:"bus",l:"std",g:"AAA",note:"管理学理学士 / Management BSc"},
  {c:"law",l:"std",g:"A*AA",note:"需要LNAT考试 / LNAT required"},
  {c:"ir",l:"std",g:"AAA",note:"国际关系学理学士 / International Relations BSc"},
  {c:"pub",l:"std",g:"AAA",note:"政治学/政府学理学士 / Politics / Government BSc"},
  {c:"hist",l:"std",g:"AAA"},
  {c:"math",l:"std",g:"A*A*A",note:"数学与经济学 / Mathematics & Economics"},
  {c:"stat",l:"std",g:"A*AA",note:"精算学/统计学 / Actuarial Science / Statistics"},
  {c:"psych",l:"std",g:"A*AA",note:"心理与行为科学 / Psychological & Behavioural Science"},
  {c:"soc",l:"std",g:"AAA",note:"社会学理学士 / Sociology BSc"},
  {c:"media",l:"std",g:"AAA",note:"媒体与传播学 / Media & Communications"}
]},

{id:"edinburgh",n:"爱丁堡大学",e:"University of Edinburgh",c:"Edinburgh",r:22,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:5.5,w:6.0,s:5.5,l:5.5},toefl:{t:92,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:23,w:23,s:23,l:23}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 25,300-36,500",currency:"GBP"},
 living:"GBP 12,000-15,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine"},
 schol:["Edinburgh Global UG Scholarship","Principal's Career Development Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA",note:"信息学理学士；IB 37 / Informatics BSc; IB 37"},
  {c:"ai",l:"std",g:"A*AA",note:"人工智能理学士 - 先锋课程 / AI BSc - pioneering programme"},
  {c:"eng",l:"std",g:"AAA-ABB",note:"多个工程方向 / Various engineering disciplines"},
  {c:"math",l:"std",g:"A*AA"},
  {c:"phys",l:"std",g:"A*AA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"chem",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"A*AA",note:"需要UCAT考试；IB 37 / UCAT required; IB 37"},
  {c:"vet",l:"high",g:"A*AA",note:"皇家（迪克）兽医学院 / Royal (Dick) Vet School"},
  {c:"law",l:"high",g:"A*AA",note:"苏格兰法与英格兰法 / Scots & English law"},
  {c:"econ",l:"std",g:"A*AA"},
  {c:"bus",l:"std",g:"AAA",note:"商学院 / Business School"},
  {c:"hist",l:"high",g:"AAA"},
  {c:"psych",l:"std",g:"AAA"},
  {c:"ling",l:"high",g:"AAA-AAB"},
  {c:"arch",l:"std",g:"AAA",note:"爱丁堡艺术学院 / Edinburgh College of Art"}
]},

{id:"manchester",n:"曼彻斯特大学",e:"University of Manchester",c:"Manchester",r:32,cat:"russell",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}},
     med:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 25,000-35,000",currency:"GBP"},
 living:"GBP 10,000-13,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine/Dentistry"},
 schol:["Manchester Master's Bursary","Equity & Merit Scholarship","International Excellence UG"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA",note:"IB 37"},
  {c:"ee",l:"std",g:"AAA",note:"电气电子工程/机电一体化 / EEE / Mechatronics"},
  {c:"me",l:"std",g:"AAA"},
  {c:"ce",l:"std",g:"AAA"},
  {c:"math",l:"std",g:"A*AA"},
  {c:"phys",l:"std",g:"A*AA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"A*AA",note:"需要UCAT考试 / UCAT required"},
  {c:"dent",l:"high",g:"AAA",note:"需要UCAT考试 / UCAT required"},
  {c:"law",l:"high",g:"AAA"},
  {c:"econ",l:"med",g:"AAA"},
  {c:"bus",l:"med",g:"AAA",note:"曼彻斯特商学院 / Alliance MBS"},
  {c:"psych",l:"med",g:"AAA"},
  {c:"arch",l:"std",g:"AAA",note:"曼彻斯特建筑学院 / Manchester School of Architecture"},
  {c:"env",l:"std",g:"AAA-AAB"}
]},

{id:"kcl",n:"伦敦国王学院",e:"King's College London",c:"London",r:37,cat:"russell",
 ll:{a:{ielts:{t:7.5,r:7,w:7,s:7,l:7},toefl:{t:109,r:27,w:27,s:23,l:23}},
     b:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:24,w:24,s:20,l:20}},
     c:{ielts:{t:7.0,r:6,w:6,s:6,l:6},toefl:{t:96,r:23,w:23,s:20,l:20}},
     d:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:92,r:20,w:20,s:20,l:20}},
     e:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:18,l:18}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 26,500-42,000",currency:"GBP"},
 living:"GBP 15,000-18,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine/Dentistry"},
 schol:["KCL International Bursary","Desmond Tutu Scholarship","Faculty-specific awards"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"d",g:"A*AA",note:"D档 / Band D"},
  {c:"math",l:"d",g:"A*AA"},
  {c:"phys",l:"e",g:"AAA-AAB"},
  {c:"chem",l:"e",g:"AAA-AAB"},
  {c:"bio",l:"d",g:"AAA-AAB"},
  {c:"med",l:"a",g:"A*AA",note:"需要UCAT；A档；IB 35 A*AA / UCAT; Band A; IB 35 A*AA"},
  {c:"dent",l:"a",g:"A*AA",note:"需要UCAT；A档 / UCAT; Band A"},
  {c:"nurs",l:"b",g:"ABB",note:"B档；需要OSCE考试 / Band B; OSCE"},
  {c:"law",l:"b",g:"A*AA",note:"需要LNAT；B档 / LNAT; Band B"},
  {c:"econ",l:"c",g:"AAA",note:"C档 / Band C"},
  {c:"psych",l:"c",g:"AAA"},
  {c:"hist",l:"b",g:"AAA"},
  {c:"ir",l:"b",g:"AAA",note:"战争研究/国际关系 / War Studies / International Relations"},
  {c:"ling",l:"b",g:"AAA-AAB"},
  {c:"edu",l:"b",g:"ABB"},
  {c:"pharm",l:"d",g:"AAB"}
]},

{id:"bristol",n:"布里斯托大学",e:"University of Bristol",c:"Bristol",r:55,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 24,700-34,800",currency:"GBP"},
 living:"GBP 11,000-14,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine/Dentistry/Vet"},
 schol:["Think Big UG Scholarship","Bristol Scholars","Faculty awards"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA",note:"IB 38"},
  {c:"eng",l:"std",g:"A*AA",note:"多种工程学士/硕士课程 / Various engineering BEng/MEng"},
  {c:"math",l:"std",g:"A*A*A"},
  {c:"phys",l:"std",g:"A*AA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"A*AA",note:"需要UCAT考试 / UCAT required"},
  {c:"dent",l:"high",g:"AAA",note:"需要UCAT考试 / UCAT required"},
  {c:"vet",l:"high",g:"A*AA"},
  {c:"law",l:"high",g:"A*AA"},
  {c:"econ",l:"std",g:"A*AA"},
  {c:"psych",l:"std",g:"AAA"},
  {c:"env",l:"std",g:"AAA-AAB"}
]},

{id:"warwick",n:"华威大学",e:"University of Warwick",c:"Coventry",r:67,cat:"russell",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:21,s:20,l:18}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:23,l:21}}},
 pol:{nt:"accepted",mb:false,v:"2y"},
 fee:{ug:"GBP 24,600-34,000",currency:"GBP"},
 living:"GBP 10,000-13,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["Warwick UG Global Excellence Scholarship","Warwick Chancellor's Intl Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*A*A",note:"IB 39"},
  {c:"eng",l:"std",g:"A*AA",note:"工程学士/硕士 / Engineering BEng/MEng"},
  {c:"math",l:"std",g:"A*A*A",note:"建议参加STEP考试；IB 39 / STEP recommended; IB 39"},
  {c:"phys",l:"std",g:"A*AA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"A*AA",note:"华威-HYMS联合项目；需要UCAT / Warwick-HYMS joint; UCAT"},
  {c:"law",l:"high",g:"A*AA",note:"需要LNAT考试 / LNAT"},
  {c:"econ",l:"high",g:"A*A*A",note:"数学A*必须；IB 39 / Maths A* required; IB 39"},
  {c:"bus",l:"high",g:"A*AA",note:"华威商学院管理学理学士 / WBS Management BSc"},
  {c:"fin",l:"high",g:"A*AA",note:"华威商学院会计与金融 / WBS Accounting & Finance"},
  {c:"psych",l:"std",g:"AAA"},
  {c:"hist",l:"high",g:"AAA"},
  {c:"media",l:"high",g:"AAA",note:"电影与电视研究 / Film & Television Studies"}
]},

// ============ RUSSELL GROUP MID ============
{id:"glasgow",n:"格拉斯哥大学",e:"University of Glasgow",c:"Glasgow",r:76,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:23,w:23,s:23,l:23}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 22,000-31,000",currency:"GBP"},
 living:"GBP 10,000-13,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine/Dentistry/Vet"},
 schol:["Glasgow Excellence Entrance Scholarship","International Leadership Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"AAA-AAB",note:"计算机科学理学士；IB 36-38 / Computing Science BSc; IB 36-38"},
  {c:"eng",l:"std",g:"AAA-AAB",note:"多种工程学士/工程学士课程 / Various engineering BSc/BEng"},
  {c:"math",l:"std",g:"AAA"},
  {c:"phys",l:"std",g:"AAA-AAB"},
  {c:"chem",l:"std",g:"AAA-AAB"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"AAA",note:"需要UCAT；可能修读苏格兰4年制学位 / UCAT required; Scottish 4-yr degree possible"},
  {c:"dent",l:"high",g:"AAA",note:"需要UCAT考试 / UCAT required"},
  {c:"vet",l:"high",g:"AAA",note:"兽医学院 / School of Veterinary Medicine"},
  {c:"law",l:"high",g:"AAA",note:"苏格兰法律学士 / Scots law LLB"},
  {c:"econ",l:"std",g:"AAA",note:"亚当·斯密商学院 / Adam Smith Business School"},
  {c:"bus",l:"std",g:"AAA-AAB"},
  {c:"psych",l:"std",g:"AAA-AAB"},
  {c:"hist",l:"high",g:"AAA-AAB"}
]},

{id:"durham",n:"杜伦大学",e:"Durham University",c:"Durham",r:78,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:92,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:102,r:25,w:25,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 24,500-33,500",currency:"GBP"},
 living:"GBP 10,000-13,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["Vice-Chancellor's Scholarship","Durham Inspired Awards"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA",note:"IB 38"},
  {c:"eng",l:"std",g:"A*AA"},
  {c:"math",l:"std",g:"A*A*A"},
  {c:"phys",l:"std",g:"A*AA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA"},
  {c:"law",l:"high",g:"A*AA",note:"需要LNAT考试 / LNAT required"},
  {c:"econ",l:"std",g:"A*AA",note:"杜伦大学商学院 / Durham University Business School"},
  {c:"bus",l:"std",g:"AAA"},
  {c:"psych",l:"std",g:"AAA"},
  {c:"hist",l:"high",g:"AAA"},
  {c:"phil",l:"high",g:"AAA"},
  {c:"edu",l:"std",g:"ABB-BBB"}
]},

{id:"leeds",n:"利兹大学",e:"University of Leeds",c:"Leeds",r:75,cat:"russell",
 ll:{l60:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}},
     l65:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:88,r:20,w:21,s:22,l:19}},
     l70:{ielts:{t:7.0,r:6,w:6,s:6,l:6},toefl:{t:96,r:22,w:22,s:23,l:21}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 23,500-31,500",currency:"GBP"},
 living:"GBP 10,000-12,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["Leeds Academic Excellence Intl Scholarship","Tetley & Lupton Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"l65",g:"A*AA",note:"IB 36"},
  {c:"ee",l:"l60",g:"AAA",note:"电子与电气工程 / Electronic & Electrical Engineering"},
  {c:"me",l:"l60",g:"AAA"},
  {c:"ce",l:"l60",g:"AAA"},
  {c:"math",l:"l65",g:"A*AA"},
  {c:"phys",l:"l60",g:"AAA-AAB"},
  {c:"chem",l:"l60",g:"AAA-AAB"},
  {c:"bio",l:"l60",g:"AAA-AAB"},
  {c:"med",l:"l70",g:"A*AA",note:"需要UCAT考试 / UCAT required"},
  {c:"law",l:"l70",g:"A*AA"},
  {c:"econ",l:"l65",g:"AAA"},
  {c:"bus",l:"l65",g:"AAA-AAB"},
  {c:"psych",l:"l65",g:"AAA"},
  {c:"media",l:"l70",g:"AAA",note:"媒体与传播学院 - 顶尖排名 / School of Media & Communication - top ranked"},
  {c:"edu",l:"l65",g:"ABB-BBB"}
]},

{id:"sheffield",n:"谢菲尔德大学",e:"University of Sheffield",c:"Sheffield",r:91,cat:"russell",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:95,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 22,700-31,000",currency:"GBP"},
 living:"GBP 9,500-12,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["Sheffield UG International Scholarship","Department-specific awards"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA",note:"IB 36"},
  {c:"eng",l:"std",g:"AAA",note:"多种工程课程 / Various engineering programmes"},
  {c:"math",l:"std",g:"A*AA"},
  {c:"phys",l:"std",g:"AAA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"AAA",note:"需要UCAT考试 / UCAT required"},
  {c:"dent",l:"high",g:"AAA"},
  {c:"law",l:"high",g:"AAA"},
  {c:"econ",l:"std",g:"AAA"},
  {c:"arch",l:"std",g:"AAA",note:"建筑学顶尖 / Top ranked architecture"},
  {c:"psych",l:"std",g:"AAA"},
  {c:"media",l:"high",g:"AAA-AAB",note:"新闻学 / Journalism Studies"}
]},

{id:"southampton",n:"南安普顿大学",e:"University of Southampton",c:"Southampton",r:80,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 22,300-29,000",currency:"GBP"},
 living:"GBP 10,000-13,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine"},
 schol:["Southampton Merit Scholarship","International Foundation Year Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA",note:"电子与计算机科学实力强 / Electronics & CS strong"},
  {c:"ee",l:"std",g:"AAA",note:"电子与计算机科学顶尖 / Top for ECS"},
  {c:"me",l:"std",g:"AAA"},
  {c:"ce",l:"std",g:"AAA"},
  {c:"math",l:"std",g:"A*AA"},
  {c:"phys",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"A*AA",note:"需要UCAT考试 / UCAT required"},
  {c:"law",l:"high",g:"AAA"},
  {c:"econ",l:"std",g:"AAA"},
  {c:"env",l:"std",g:"AAA-AAB",note:"海洋与地球科学 / Ocean & Earth Science"},
  {c:"ds",l:"std",g:"A*AA"}
]},

{id:"nottingham",n:"诺丁汉大学",e:"University of Nottingham",c:"Nottingham",r:100,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:87,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6,w:6,s:6,l:6},toefl:{t:100,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 22,000-29,000",currency:"GBP"},
 living:"GBP 9,500-12,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine/Vet"},
 schol:["Nottingham High Achiever Scholarship","Developing Solutions UG Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA",note:"IB 36"},
  {c:"eng",l:"std",g:"AAA"},
  {c:"math",l:"std",g:"A*AA"},
  {c:"phys",l:"std",g:"AAA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"A*AA",note:"需要UCAT考试 / UCAT required"},
  {c:"vet",l:"high",g:"AAA"},
  {c:"pharm",l:"std",g:"AAB"},
  {c:"law",l:"high",g:"AAA"},
  {c:"econ",l:"std",g:"A*AA"},
  {c:"bus",l:"std",g:"AAA",note:"诺丁汉大学商学院 / Nottingham University Business School"},
  {c:"psych",l:"std",g:"AAA"}
]},

{id:"birmingham",n:"伯明翰大学",e:"University of Birmingham",c:"Birmingham",r:84,cat:"russell",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}},
     med:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:88,r:20,w:20,s:21,l:19}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:95,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 22,260-29,940",currency:"GBP"},
 living:"GBP 10,000-13,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine/Dentistry"},
 schol:["Birmingham Elite Scholarship","International Scholarship Programme"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA"},
  {c:"eng",l:"std",g:"AAA"},
  {c:"math",l:"std",g:"A*AA"},
  {c:"phys",l:"std",g:"AAA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA"},
  {c:"med",l:"high",g:"A*AA",note:"需要UCAT；IB 32+ / UCAT; IB 32+"},
  {c:"dent",l:"high",g:"AAA",note:"需要UCAT考试 / UCAT required"},
  {c:"law",l:"high",g:"AAA"},
  {c:"econ",l:"med",g:"AAA"},
  {c:"bus",l:"med",g:"AAA-AAB",note:"伯明翰商学院 / Birmingham Business School"},
  {c:"psych",l:"med",g:"AAA"},
  {c:"edu",l:"med",g:"ABB-BBB"}
]},

{id:"standrews",n:"圣安德鲁斯大学",e:"University of St Andrews",c:"St Andrews",r:68,cat:"other",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:24,w:24,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 25,000-33,000",currency:"GBP"},
 living:"GBP 10,000-12,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["St Andrews International Scholarship","600th Anniversary Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"AAA",note:"IB 36"},
  {c:"math",l:"std",g:"AAA"},
  {c:"phys",l:"std",g:"AAA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"ir",l:"high",g:"AAA",note:"国际关系学院顶尖排名 / School of International Relations top ranked"},
  {c:"econ",l:"std",g:"AAA"},
  {c:"hist",l:"high",g:"AAA"},
  {c:"phil",l:"high",g:"AAA"},
  {c:"psych",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"A*AA",note:"医学入门项目 / Gateway to Medicine programme"}
]},

{id:"exeter",n:"埃克塞特大学",e:"University of Exeter",c:"Exeter",r:130,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6,w:6,s:6,l:6},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 22,500-29,500",currency:"GBP"},
 living:"GBP 10,000-13,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["Exeter Global Excellence Scholarship","Subject-specific awards"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA"},
  {c:"eng",l:"std",g:"AAA-AAB"},
  {c:"math",l:"std",g:"A*AA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"A*AA",note:"需要UCAT考试 / UCAT required"},
  {c:"law",l:"high",g:"A*AA"},
  {c:"econ",l:"std",g:"A*AA"},
  {c:"bus",l:"std",g:"AAA",note:"埃克塞特商学院 / Exeter Business School"},
  {c:"fin",l:"std",g:"AAA"},
  {c:"psych",l:"std",g:"AAA"},
  {c:"hist",l:"high",g:"AAA-AAB"}
]},

{id:"bath",n:"巴斯大学",e:"University of Bath",c:"Bath",r:148,cat:"other",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:21,w:21,s:21,l:21}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:24,w:24,s:24,l:24}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 22,000-29,000",currency:"GBP"},
 living:"GBP 10,000-13,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["Bath International Scholarship","Chancellor's Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA",note:"IB 36"},
  {c:"eng",l:"std",g:"A*AA",note:"有丰富带薪实习年选项 / Strong placement year options"},
  {c:"math",l:"std",g:"A*AA"},
  {c:"phys",l:"std",g:"A*AA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA"},
  {c:"bus",l:"high",g:"A*AA",note:"管理学院顶尖排名 / School of Management top ranked"},
  {c:"acct",l:"high",g:"A*AA",note:"会计与金融学理学士 / Accounting & Finance BSc"},
  {c:"psych",l:"std",g:"AAA"},
  {c:"arch",l:"std",g:"AAA",note:"建筑学理学士 / Architecture BSc"}
]},

{id:"york",n:"约克大学",e:"University of York",c:"York",r:141,cat:"russell",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:96,r:22,w:22,s:23,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 21,950-28,800",currency:"GBP"},
 living:"GBP 9,500-12,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["York Global Merit Scholarship","Vice-Chancellor's Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA"},
  {c:"eng",l:"std",g:"AAA-AAB"},
  {c:"math",l:"std",g:"A*AA"},
  {c:"phys",l:"std",g:"AAA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"law",l:"high",g:"AAA"},
  {c:"econ",l:"std",g:"AAA"},
  {c:"psych",l:"std",g:"AAA",note:"心理学顶尖排名 / Top ranked psychology"},
  {c:"edu",l:"std",g:"ABB-BBB"},
  {c:"hist",l:"high",g:"AAA"},
  {c:"media",l:"high",g:"AAA-AAB"}
]},

{id:"lancaster",n:"兰卡斯特大学",e:"Lancaster University",c:"Lancaster",r:122,cat:"other",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:87,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6,w:6,s:6,l:6},toefl:{t:93,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 21,500-28,000",currency:"GBP"},
 living:"GBP 9,500-12,000/yr",
 visa:{psw:"2yr",note:"毕业生签证 / Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["Lancaster Global Scholarship","LUMS Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"AAA"},
  {c:"eng",l:"std",g:"AAA-AAB"},
  {c:"math",l:"std",g:"AAA"},
  {c:"phys",l:"std",g:"AAA-AAB"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"env",l:"std",g:"AAA-ABB"},
  {c:"law",l:"high",g:"AAA"},
  {c:"econ",l:"std",g:"AAA"},
  {c:"bus",l:"std",g:"AAA",note:"兰卡斯特管理学院顶尖排名 / LUMS top ranked"},
  {c:"fin",l:"std",g:"AAA",note:"兰卡斯特管理学院 / Lancaster Management School"},
  {c:"psych",l:"std",g:"AAA"},
  {c:"ling",l:"std",g:"AAA-AAB"}
]},

// ============ RUSSELL GROUP OTHER ============
{id:"newcastle",n:"纽卡斯尔大学",e:"Newcastle University",c:"Newcastle",r:110,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"A*AA"},{c:"eng",l:"std",g:"AAA"},{c:"math",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},{c:"med",l:"high",g:"A*AA",note:"需要UCAT考试 / UCAT required"},
  {c:"arch",l:"std",g:"AAA"},{c:"law",l:"high",g:"AAA"},
  {c:"bus",l:"std",g:"AAA-AAB"},{c:"psych",l:"std",g:"AAA"}
]},

{id:"liverpool",n:"利物浦大学",e:"University of Liverpool",c:"Liverpool",r:150,cat:"russell",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:95,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"AAA-AAB"},{c:"eng",l:"std",g:"AAA-AAB"},{c:"math",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},{c:"med",l:"high",g:"AAA",note:"需要UCAT考试 / UCAT required"},
  {c:"dent",l:"high",g:"AAA"},{c:"vet",l:"high",g:"AAA"},
  {c:"arch",l:"std",g:"AAA-AAB"},{c:"law",l:"high",g:"AAA"},
  {c:"bus",l:"std",g:"AAA-AAB"}
]},

{id:"qmul",n:"伦敦玛丽女王",e:"Queen Mary University of London",c:"London",r:125,cat:"russell",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"A*AA"},{c:"eng",l:"std",g:"AAA"},{c:"math",l:"std",g:"A*AA"},
  {c:"bio",l:"std",g:"AAA-AAB"},{c:"med",l:"high",g:"A*AA",note:"需要UCAT考试 / UCAT required"},
  {c:"dent",l:"high",g:"AAA"},{c:"law",l:"high",g:"AAA",note:"法学院顶尖排名 / Top ranked law school"},
  {c:"econ",l:"std",g:"AAA"},{c:"ling",l:"std",g:"AAA-AAB"},
  {c:"hist",l:"high",g:"AAA-AAB"}
]},

{id:"cardiff",n:"卡迪夫大学",e:"Cardiff University",c:"Cardiff",r:154,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:90,r:17,w:17,s:20,l:17}},
     high:{ielts:{t:7.0,r:6,w:6,s:6,l:6},toefl:{t:100,r:20,w:20,s:22,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"AAA-AAB"},{c:"eng",l:"std",g:"AAA-AAB"},{c:"math",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},{c:"med",l:"high",g:"AAA",note:"需要UCAT考试 / UCAT required"},
  {c:"dent",l:"high",g:"AAA"},{c:"arch",l:"std",g:"AAA-AAB"},
  {c:"law",l:"high",g:"AAA"},{c:"bus",l:"std",g:"AAA-AAB"},
  {c:"media",l:"high",g:"AAA",note:"新闻学院顶尖排名 / School of Journalism top ranked"},
  {c:"psych",l:"std",g:"AAA"}
]},

{id:"qub",n:"贝尔法斯特女王大学",e:"Queen's University Belfast",c:"Belfast",r:195,cat:"russell",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:17,w:17,s:20,l:17}},
     high:{ielts:{t:7.0,r:6,w:6,s:6,l:6},toefl:{t:95,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"AAA-AAB"},{c:"eng",l:"std",g:"AAA-ABB"},{c:"math",l:"std",g:"AAA-AAB"},
  {c:"bio",l:"std",g:"AAA-AAB"},{c:"med",l:"high",g:"A*AA",note:"需要UCAT考试 / UCAT required"},
  {c:"law",l:"high",g:"AAA"},{c:"pharm",l:"std",g:"AAB-ABB"},
  {c:"econ",l:"std",g:"AAA-AAB"},{c:"psych",l:"std",g:"AAA-AAB"}
]},

// ============ OTHER RANKED ============
{id:"loughborough",n:"拉夫堡大学",e:"Loughborough University",c:"Loughborough",r:212,cat:"other",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:92,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"AAA-AAB"},{c:"eng",l:"std",g:"AAA-AAB"},
  {c:"bus",l:"std",g:"AAA-AAB"},{c:"ds",l:"std",g:"AAA-AAB"},
  {c:"art",l:"std",g:"ABB-BBB",note:"设计与体育科学顶尖 / Top for design & sport science"}
]},

{id:"surrey",n:"萨里大学",e:"University of Surrey",c:"Guildford",r:230,cat:"other",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:88,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"AAA-AAB"},{c:"eng",l:"std",g:"AAA-ABB"},
  {c:"bus",l:"std",g:"AAA-ABB"},{c:"vet",l:"std",g:"AAA",note:"兽医学院 / School of Veterinary Medicine"},
  {c:"bio",l:"std",g:"AAA-AAB"}
]},

{id:"sussex",n:"萨塞克斯大学",e:"University of Sussex",c:"Brighton",r:218,cat:"other",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:88,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"AAA-AAB"},{c:"ai",l:"std",g:"AAA-AAB"},
  {c:"ir",l:"std",g:"AAA-AAB",note:"发展研究顶尖 / Top for development studies"},
  {c:"media",l:"std",g:"AAA-ABB"},{c:"psych",l:"std",g:"AAA"},
  {c:"edu",l:"std",g:"ABB-BBB"},{c:"econ",l:"std",g:"AAA-AAB"}
]},

{id:"soas",n:"伦敦大学亚非学院",e:"SOAS University of London",c:"London",r:340,cat:"other",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:92,r:22,w:22,s:22,l:22}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:24,w:24,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"law",l:"high",g:"AAA",note:"含多个专业方向的法律学士 / LLB with specialisms"},{c:"ir",l:"high",g:"AAA-AAB"},
  {c:"econ",l:"std",g:"AAA-AAB"},{c:"ling",l:"std",g:"AAA-ABB"},
  {c:"hist",l:"high",g:"AAA-AAB"},{c:"soc",l:"std",g:"AAA-ABB",note:"区域研究方向 / Area studies focus"}
]},

{id:"city",n:"伦敦城市大学",e:"City, University of London",c:"London",r:320,cat:"other",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}},
     cass:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:89,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"AAA-ABB"},{c:"eng",l:"std",g:"AAA-ABB"},
  {c:"bus",l:"cass",g:"AAA",note:"贝叶斯商学院 / Bayes Business School"},
  {c:"fin",l:"cass",g:"A*AA",note:"贝叶斯；金融学理学士顶尖排名 / Bayes; top ranked finance BSc"},
  {c:"acct",l:"cass",g:"AAA"},{c:"law",l:"std",g:"AAA-AAB"},
  {c:"media",l:"std",g:"AAA-ABB",note:"新闻与出版学 / Journalism & publishing"}
]},

{id:"ual",n:"伦敦艺术大学",e:"University of the Arts London",c:"London",r:null,cat:"other",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}}},
 pol:{nt:"accepted",mb:false,v:"2y"},
 p:[
  {c:"art",l:"std",g:"Portfolio",note:"CSM/LCF/LCC - 世界顶尖艺术与设计；需要作品集 / CSM/LCF/LCC - world leading art & design; portfolio essential"},
  {c:"media",l:"std",g:"Portfolio",note:"传播与媒体设计 / Communication & media design"},
  {c:"arch",l:"std",g:"Portfolio",note:"建筑与空间设计 / Architecture & spatial design"}
]},

{id:"coventry",n:"考文垂大学",e:"Coventry University",c:"Coventry",r:380,cat:"other",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:79,r:18,w:18,s:20,l:17}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"BBB-BCC"},{c:"eng",l:"std",g:"BBB-BCC"},
  {c:"bus",l:"std",g:"BBB-BCC"},{c:"art",l:"std",g:"BCC-CCC",note:"以作品集为基础 / Portfolio based"},
  {c:"media",l:"std",g:"BBB-BCC"}
]},

{id:"westminster",n:"威斯敏斯特大学",e:"University of Westminster",c:"London",r:400,cat:"other",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}}},
 pol:{nt:"accepted",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"BBB-BCC"},{c:"bus",l:"std",g:"BBB-BCC"},
  {c:"media",l:"std",g:"BBB-BCC",note:"媒体与传播学顶尖 / Top for media & communications"},
  {c:"arch",l:"std",g:"BBB"},{c:"art",l:"std",g:"BCC"}
]}
];
COMPASS_DATA.uk = D;
})();
