// data-ca.js - Canadian Universities - Undergraduate Programs Only
// v4.0 - All programs are bachelor's level
(function(){
var D = [
// ============ U15 TOP TIER ============
{id:"uoft",n:"多伦多大学",e:"University of Toronto",c:"Toronto, ON",r:21,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:89,r:21,w:22,s:22,l:21}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:21,
 fee:{ug:"CAD 60,000-65,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 18,000-22,000/yr",
 ddl:{fall:"Jan 15 (OUAC)"},
 schol:["Lester B. Pearson Scholarship (full ride)","President's Scholars of Excellence","UofT Scholars Program"],
 materials:["OUAC application","Transcripts","Supplementary application","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 90s",note:"文理学院或工程方向；竞争激烈 / Arts & Science or Engineering stream; highly competitive"},
  {c:"eng",l:"def",g:"mid-to-high 90s",note:"应用科学与工程学院 / Faculty of Applied Science & Engineering"},
  {c:"ee",l:"def",g:"low-to-mid 90s",note:"电气与计算机工程 / Electrical & Computer Engineering"},
  {c:"math",l:"def",g:"low-to-mid 90s"},
  {c:"phys",l:"def",g:"low-to-mid 90s"},
  {c:"chem",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s",note:"生命科学 / Life Sciences"},
  {c:"econ",l:"def",g:"low-to-mid 90s",note:"经济学/商学 / Economics / Commerce"},
  {c:"bus",l:"def",g:"low-to-mid 90s",note:"Rotman商学院 / Rotman Commerce"},
  {c:"law",l:"def",g:"mid-to-high 80s",note:"无直接本科法律；有法律预科方向 / No direct UG law; pre-law tracks available"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"med",l:"def",g:"low-to-mid 90s",note:"医学预科；MD为研究生 / pre-med; MD is post-grad"},
  {c:"arch",l:"def",g:"mid-to-high 80s",note:"丹尼尔斯学院；需作品集 / Daniels Faculty; portfolio"},
  {c:"ds",l:"def",g:"low-to-mid 90s",note:"数据科学专业方向 / Data Science specialist"}
]},

{id:"ubc",n:"英属哥伦比亚大学",e:"University of British Columbia",c:"Vancouver, BC",r:34,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:22,w:21,s:21,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:45,
 fee:{ug:"CAD 49,000-60,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 18,000-22,000/yr",
 ddl:{fall:"Jan 15"},
 schol:["International Major Entrance Scholarship (up to full tuition)","Outstanding International Student Award","Karen McKellin International Leader of Tomorrow"],
 materials:["UBC application","Transcripts","Personal profile","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 90s",note:"计算机科学理学士；竞争激烈 / BSc Computer Science; highly competitive"},
  {c:"eng",l:"def",g:"mid-to-high 90s",note:"应用科学学士 / Applied Science BASc"},
  {c:"math",l:"def",g:"low-to-mid 90s"},
  {c:"phys",l:"def",g:"low-to-mid 90s"},
  {c:"chem",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s"},
  {c:"econ",l:"def",g:"mid-to-high 80s",note:"温哥华经济学院 / Vancouver School of Economics"},
  {c:"bus",l:"def",g:"low-to-mid 90s",note:"Sauder School of Business 商学士 / BCom"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"media",l:"def",g:"mid-to-high 80s",note:"新闻学/媒体研究 / Journalism / Media Studies"},
  {c:"env",l:"def",g:"mid-to-high 80s",note:"土地与食品系统/环境科学 / Land & Food Systems / Environmental Sc."},
  {c:"arch",l:"def",g:"mid-to-high 80s",note:"建筑与景观学院；可能需要作品集 / SALA; portfolio may be required"}
]},

{id:"mcgill",n:"麦吉尔大学",e:"McGill University",c:"Montreal, QC",r:29,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:21,w:21,s:21,l:21}},
     high:{ielts:{t:7.0,r:6.5,w:7,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:41,
 fee:{ug:"CAD 29,000-50,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP; Quebec CAQ required"},
 living:"CAD 15,000-20,000/yr",
 ddl:{fall:"Jan 15"},
 schol:["Entrance Scholarships (up to CAD 12,000)","One Planet Scholarship","Faculty-specific awards"],
 materials:["McGill application","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"low-to-mid 90s",note:"计算机科学学院理学士 / School of Computer Science BSc"},
  {c:"eng",l:"def",g:"low-to-mid 90s",note:"工程学院 / Faculty of Engineering BEng"},
  {c:"math",l:"def",g:"low-to-mid 90s"},
  {c:"phys",l:"def",g:"low-to-mid 90s"},
  {c:"chem",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"bus",l:"high",g:"low-to-mid 90s",note:"Desautels 商学士 / BCom; IELTS 7.0"},
  {c:"law",l:"high",g:"low-to-mid 90s",note:"法律预科；民法/法学士为研究生学位 / Pre-law; BCL/LLB is post-grad"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"med",l:"def",g:"low-to-mid 90s",note:"医学预科通道；MDCM为研究生学位 / Pre-med pathway; MDCM post-grad"},
  {c:"arch",l:"def",g:"mid-to-high 80s",note:"建筑学院理学士 / School of Architecture BSc(Arch)"}
]},

{id:"waterloo",n:"滑铁卢大学",e:"University of Waterloo",c:"Waterloo, ON",r:112,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6.5,l:6},toefl:{t:90,r:20,w:25,s:25,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:162,
 fee:{ug:"CAD 52,000-62,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 15,000-18,000/yr",
 ddl:{fall:"Feb 1 (OUAC)"},
 schol:["President's Scholarship of Distinction (CAD 10,000)","International Experience Award","Faculty-specific entrance awards"],
 materials:["OUAC application","AIF (Admission Information Form)","Transcripts","English proficiency","Euclid/CCC contest (optional)"],
 p:[
  {c:"cs",l:"def",g:"low-to-mid 90s",note:"Cheriton计算机学院；可选带薪实习；竞争极激烈 / Cheriton School of CS; co-op available; extremely competitive"},
  {c:"eng",l:"def",g:"low-to-mid 90s",note:"软件/计算机/电气工程；带薪实习 / Software/Computer/Electrical Engineering; co-op"},
  {c:"ee",l:"def",g:"low-to-mid 90s"},
  {c:"me",l:"def",g:"low-to-mid 90s"},
  {c:"math",l:"def",g:"low-to-mid 90s",note:"数学学院；带薪实习 / Faculty of Mathematics; co-op"},
  {c:"stat",l:"def",g:"low-to-mid 90s",note:"精算与统计 / Actuarial Science / Statistics"},
  {c:"phys",l:"def",g:"mid-to-high 80s"},
  {c:"bus",l:"def",g:"mid-to-high 80s",note:"会计与金融管理；数学导向商科 / AFM / FARM; math-heavy business"},
  {c:"acct",l:"def",g:"mid-to-high 80s",note:"会计与金融学院 / School of Accounting & Finance"},
  {c:"ds",l:"def",g:"low-to-mid 90s",note:"数学学院数据科学方向 / Data Science within Math faculty"},
  {c:"env",l:"def",g:"mid-to-high 80s",note:"环境学院 / Faculty of Environment"}
]},

{id:"ualberta",n:"阿尔伯塔大学",e:"University of Alberta",c:"Edmonton, AB",r:96,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:21,w:21,s:21,l:21}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:119,
 fee:{ug:"CAD 33,000-42,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 14,000-18,000/yr",
 ddl:{fall:"Mar 1"},
 schol:["International Student Scholarship","President's Award of Distinction","Faculty-specific awards"],
 materials:["Alberta application","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s",note:"计算科学理学士 / Computing Science BSc"},
  {c:"eng",l:"def",g:"mid-to-high 80s",note:"工程学院 / Faculty of Engineering BEng"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"phys",l:"def",g:"mid-to-high 80s"},
  {c:"chem",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"bus",l:"def",g:"mid-to-high 80s",note:"Alberta School of Business 商学士 / BCom"},
  {c:"edu",l:"def",g:"mid-to-high 80s",note:"教育学院 教育学士 / Faculty of Education BEd"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"env",l:"def",g:"mid-to-high 80s"},
  {c:"nurs",l:"def",g:"mid-to-high 80s",note:"护理理学士 / BScN Nursing"}
]},

{id:"mcmaster",n:"麦克马斯特大学",e:"McMaster University",c:"Hamilton, ON",r:152,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:86,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:116,
 fee:{ug:"CAD 38,000-52,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 14,000-18,000/yr",
 ddl:{fall:"Jan 15 (OUAC)"},
 schol:["Provost's Award","McMaster International Excellence Award","Faculty awards"],
 materials:["OUAC application","Supplementary application","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s",note:"计算与软件应用科学学士 / Computing & Software BASc"},
  {c:"eng",l:"def",g:"low-to-mid 90s",note:"工程一年级（通识基础年） / Engineering I (common first year)"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"phys",l:"def",g:"mid-to-high 80s"},
  {c:"chem",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s",note:"生命科学-健康科学方向 / Life Sciences - Health Sciences stream"},
  {c:"bus",l:"def",g:"mid-to-high 80s",note:"DeGroote School 商学士 / BCom"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"nurs",l:"def",g:"low-to-mid 90s",note:"护理理学士 / BScN"},
  {c:"med",l:"def",g:"low-to-mid 90s",note:"健康科学学士；医学预科；需CARS测试 / Health Sciences BHSc; pre-med; CARS test"}
]},

// ============ U15 MID TIER ============
{id:"western",n:"韦仕敦大学",e:"Western University",c:"London, ON",r:114,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:83,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:201,
 fee:{ug:"CAD 40,000-55,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 14,000-17,000/yr",
 ddl:{fall:"Jan 15 (OUAC)"},
 schol:["Western Scholarship of Excellence","International President's Entrance Scholarship","National Scholarship"],
 materials:["OUAC application","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s"},
  {c:"eng",l:"def",g:"mid-to-high 80s",note:"工程学院 / Faculty of Engineering BESc"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s",note:"医学科学-热门医学预科 / Medical Sciences popular pre-med"},
  {c:"bus",l:"def",g:"low-to-mid 90s",note:"Ivey商学院AEO/HBA；竞争激烈 / Ivey AEO / HBA; very competitive"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"media",l:"def",g:"mid-to-high 80s",note:"媒体、信息与科技文化 / Media, Information & Technoculture"},
  {c:"nurs",l:"def",g:"mid-to-high 80s",note:"护理理学士 / BScN"},
  {c:"med",l:"def",g:"low-to-mid 90s",note:"医学科学预科通道 / Medical Sciences pre-med track"}
]},

{id:"queens",n:"女王大学",e:"Queen's University",c:"Kingston, ON",r:176,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:88,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:251,
 fee:{ug:"CAD 45,000-55,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 13,000-17,000/yr",
 ddl:{fall:"Feb 1 (OUAC)"},
 schol:["Queen's International Scholarship","Chancellor's Scholarship","Principal's Scholarship"],
 materials:["OUAC application","Personal Statement of Experience","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s",note:"计算学院理学士 / School of Computing BSc"},
  {c:"eng",l:"def",g:"mid-to-high 80s",note:"史密斯工程应用科学学士 / Smith Engineering BASc"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"phys",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s",note:"生命科学 / Life Sciences"},
  {c:"bus",l:"def",g:"low-to-mid 90s",note:"Smith School 商学士 / BCom; 竞争激烈 / highly competitive"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"nurs",l:"def",g:"mid-to-high 80s",note:"护理理学士 / BNSc"}
]},

{id:"uottawa",n:"渥太华大学",e:"University of Ottawa",c:"Ottawa, ON",r:203,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:86,r:20,w:22,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:187,
 fee:{ug:"CAD 35,000-50,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 14,000-18,000/yr",
 ddl:{fall:"Apr 1 (OUAC for Ontario; direct for others)"},
 schol:["International Admission Scholarship","Merit Scholarship","Chancellor's Scholarship"],
 materials:["Application","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s",note:"电气工程与计算机科学学院；双语校园 / School of EECS; bilingual campus"},
  {c:"eng",l:"def",g:"mid-to-high 80s",note:"工程学院 / Faculty of Engineering"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s"},
  {c:"bus",l:"def",g:"mid-to-high 80s",note:"Telfer School 商学士 / BCom"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"law",l:"def",g:"mid-to-high 80s",note:"法律预科；民法与普通法学院（研究生） / Pre-law; Civil & Common Law Faculty (post-grad)"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"edu",l:"def",g:"mid-to-high 80s",note:"教育学院 / Faculty of Education"},
  {c:"nurs",l:"def",g:"mid-to-high 80s",note:"护理理学士 / BScN"}
]},

{id:"dalhousie",n:"达尔豪斯大学",e:"Dalhousie University",c:"Halifax, NS",r:298,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:301,
 fee:{ug:"CAD 25,000-38,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 13,000-17,000/yr",
 ddl:{fall:"Apr 1"},
 schol:["Entrance Scholarships (up to CAD 40,000)","International Impact Scholarship","Faculty awards"],
 materials:["Dalhousie application","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s",note:"计算机科学学院 / Faculty of Computer Science"},
  {c:"eng",l:"def",g:"mid-to-high 80s"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s",note:"海洋科学实力强 / Ocean Sciences strong"},
  {c:"bus",l:"def",g:"mid-to-high 80s",note:"Rowe School 商学士 / BCom"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"env",l:"def",g:"mid-to-high 80s",note:"海洋与环境 / Marine & Environmental"},
  {c:"nurs",l:"def",g:"mid-to-high 80s",note:"护理理学士 / BScN"}
]},

{id:"ucalgary",n:"卡尔加里大学",e:"University of Calgary",c:"Calgary, AB",r:175,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:86,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:201,
 fee:{ug:"CAD 28,000-40,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 14,000-18,000/yr",
 ddl:{fall:"Mar 1"},
 schol:["International Entrance Scholarship","Chancellor's Club Scholarship","Faculty awards"],
 materials:["Calgary application","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s"},
  {c:"eng",l:"def",g:"mid-to-high 80s",note:"舒立赫工程学院 / Schulich School of Engineering"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s"},
  {c:"bus",l:"def",g:"mid-to-high 80s",note:"Haskayne 商学士 / BCom"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"edu",l:"def",g:"mid-to-high 80s",note:"Werklund School 教育学士 / BEd"},
  {c:"nurs",l:"def",g:"mid-to-high 80s",note:"护理学士 / BN"},
  {c:"env",l:"def",g:"mid-to-high 80s"}
]},

{id:"umontreal",n:"蒙特利尔大学",e:"Universite de Montreal",c:"Montreal, QC",r:141,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:21,w:21,s:21,l:21}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:150,
 fee:{ug:"CAD 25,000-35,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP; Quebec CAQ required"},
 living:"CAD 14,000-18,000/yr",
 ddl:{fall:"Feb 1"},
 schol:["Bursaries for international students","Faculty excellence scholarships"],
 materials:["UdeM application","Transcripts","French & English proficiency"],
 p:[
  {c:"cs",l:"def",g:"R-score 28+",note:"计算机系；大部分法语授课；Mila AI实验室附属 / DIRO; most programs in French; Mila AI lab affiliated"},
  {c:"eng",l:"def",g:"R-score 28+",note:"蒙特利尔工程学院附属 / Polytechnique Montreal affiliated"},
  {c:"math",l:"def",g:"R-score 28+"},
  {c:"bio",l:"def",g:"R-score 26+"},
  {c:"econ",l:"def",g:"R-score 26+"},
  {c:"bus",l:"def",g:"R-score 28+",note:"蒙特利尔高等商学院（附属）；部分英语选项 / HEC Montreal (affiliated); some English options"},
  {c:"law",l:"def",g:"R-score 30+",note:"法学院；需法语 / Faculty of Law; French required"},
  {c:"psych",l:"def",g:"R-score 26+"},
  {c:"med",l:"def",g:"R-score 34+",note:"需法语；MD为研究生学位 / French required; MD post-grad"},
  {c:"edu",l:"def",g:"R-score 26+"}
]},

// ============ OTHER NOTABLE ============
{id:"sfu",n:"西蒙菲莎大学",e:"Simon Fraser University",c:"Burnaby, BC",r:328,cat:"other",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:88,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:251,
 fee:{ug:"CAD 32,000-38,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP"},
 living:"CAD 17,000-22,000/yr",
 ddl:{fall:"Jan 31"},
 schol:["SFU Open Scholarship","International Transfer Student Scholarship","Provost Entrance Award"],
 materials:["SFU application","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s",note:"计算科学学院理学士 / School of Computing Science BSc"},
  {c:"eng",l:"def",g:"mid-to-high 80s",note:"机电系统/工程科学 / Mechatronic Systems / Engineering Science"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s"},
  {c:"bus",l:"def",g:"mid-to-high 80s",note:"Beedie 工商管理学士 / BBA"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"media",l:"def",g:"mid-to-high 80s",note:"传播学院 / School of Communication"},
  {c:"ds",l:"def",g:"mid-to-high 80s",note:"数据科学辅修/方向 / Data Science minor/stream"}
]},

{id:"uvic",n:"维多利亚大学",e:"University of Victoria",c:"Victoria, BC",r:322,cat:"other",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:301,
 fee:{ug:"CAD 28,000-36,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP"},
 living:"CAD 16,000-20,000/yr",
 ddl:{fall:"Feb 28"},
 schol:["UVic International Entrance Scholarship","Faculty-specific awards"],
 materials:["UVic application","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s",note:"带薪实习可选 / Co-op available"},
  {c:"eng",l:"def",g:"mid-to-high 80s",note:"软件/计算机/电气/机械工程 / Software/Computer/Electrical/Mechanical"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s"},
  {c:"bus",l:"def",g:"mid-to-high 80s",note:"Gustavson 商学士 / BCom"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"env",l:"def",g:"mid-to-high 80s",note:"环境研究 / Environmental Studies"}
]},

{id:"york_ca",n:"约克大学(加拿大)",e:"York University",c:"Toronto, ON",r:353,cat:"other",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:88,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:401,
 fee:{ug:"CAD 30,000-40,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP"},
 living:"CAD 16,000-20,000/yr",
 ddl:{fall:"Feb 1 (OUAC)"},
 schol:["International Entrance Scholarship of Distinction","Global Leader of Tomorrow Award"],
 materials:["OUAC application","Transcripts","English proficiency","Supplementary (Schulich)"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s",note:"拉松德学院理学士 / Lassonde School BSc"},
  {c:"eng",l:"def",g:"mid-to-high 80s",note:"拉松德工程学士 / Lassonde BEng"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s"},
  {c:"bus",l:"def",g:"low-to-mid 90s",note:"Schulich 工商管理学士 / BBA; globally ranked"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"law",l:"def",g:"mid-to-high 80s",note:"法律预科；奥斯古德堂为研究生学位 / Pre-law; Osgoode Hall is post-grad"},
  {c:"edu",l:"def",g:"mid-to-high 80s",note:"教育学士 / BEd concurrent"},
  {c:"media",l:"def",g:"mid-to-high 80s",note:"电影/传播研究 / Film / Communication Studies"}
]}
];
COMPASS_DATA.ca = D;
})();
