// data-ca.js - Canadian Universities (15)
// Pushes into COMPASS_DATA.ca
(function(){
var D = [
// ============ U15 TOP TIER ============
{id:"uoft",n:"多伦多大学",e:"University of Toronto",c:"Toronto, ON",r:21,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:89,r:null,w:22,s:22,l:null}},
     grad:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:93,r:null,w:22,s:22,l:null}},
     high:{ielts:{t:7.5,r:7.5,w:7.5,s:7,l:null},toefl:{t:107,r:null,w:27,s:24,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"ug",l:"def",g:"mid-to-high 80s",note:"IELTS 6.5 no band <6.0; TOEFL 89 W22 S22"},
  {c:"cs_ms",l:"grad",g:"B+",note:"Dept of Computer Science"},
  {c:"cs_phd",l:"grad",g:"A-",note:"Fully funded PhD"},
  {c:"mba",l:"high",g:"B+",note:"Rotman MBA; avg GMAT 680"},
  {c:"eng_ms",l:"grad",g:"B+",note:"Faculty of Applied Science & Engineering"},
  {c:"law_llm",l:"high",g:"B+",note:"Faculty of Law"},
  {c:"edu_ms",l:"grad",g:"B",note:"OISE"},
  {c:"bus_ms",l:"grad",g:"B+",note:"Rotman MFin/MMgt"},
  {c:"med",l:"high",g:"A-",note:"Temerty Faculty of Medicine"},
  {c:"ph_ms",l:"grad",g:"B+",note:"Dalla Lana SPH"}
],
 the:21,
 fee:{ug:"CAD 60,000-65,000",pg:"CAD 25,000-55,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 18,000-22,000/yr",
 ddl:{fall:"Jan 15 (UG); varies by dept (Grad)",winter:"Sep-Nov (Grad)"},
 schol:["Lester B. Pearson Scholarship (UG full ride)","Vanier CGS (PhD CAD 50k/yr x3)","Ontario Graduate Scholarship","UofT Fellowship"],
 materials:["transcripts","statement of purpose","letters of recommendation","CV/resume","English proficiency scores"]
},

{id:"ubc",n:"英属哥伦比亚大学",e:"University of British Columbia",c:"Vancouver, BC",r:34,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:22,w:21,s:21,l:22}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"ug",l:"def",g:"mid-to-high 80s",note:"IELTS 6.5 no band <6.0"},
  {c:"cs_ms",l:"def",g:"B+",note:"Dept of Computer Science"},
  {c:"eng_ms",l:"def",g:"B+",note:"Faculty of Applied Science"},
  {c:"mba",l:"high",g:"B+",note:"Sauder School; IELTS 7.0 / TOEFL 100"},
  {c:"law_llm",l:"high",g:"B+",note:"Peter A. Allard School of Law"},
  {c:"edu_ms",l:"def",g:"B+",note:"Faculty of Education"},
  {c:"bus_ms",l:"high",g:"B+",note:"Sauder MBAN/MM"},
  {c:"med",l:"high",g:"A-",note:"Faculty of Medicine"},
  {c:"env_ms",l:"def",g:"B+"}
],
 the:45,
 fee:{ug:"CAD 49,000-60,000",pg:"CAD 9,000-55,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 18,000-22,000/yr",
 ddl:{fall:"Jan 15 (UG); Dec-Feb (Grad)",winter:"Sep 15 (Grad)"},
 schol:["International Major Entrance Scholarship (UG)","Vanier CGS (PhD CAD 50k/yr x3)","Four Year Doctoral Fellowship","International Tuition Award"],
 materials:["transcripts","statement of purpose","letters of recommendation","CV/resume","English proficiency scores"]
},

{id:"mcgill",n:"麦吉尔大学",e:"McGill University",c:"Montreal, QC",r:29,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:21,w:21,s:21,l:21}},
     grad:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:86,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:7,s:6.5,l:6.5},toefl:{t:100,r:23,w:25,s:23,l:23}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"ug",l:"def",g:"mid-to-high 80s",note:"TOEFL 90 min 21 per section; Mgmt/Ed require 100"},
  {c:"cs_ms",l:"high",g:"B+/3.3",note:"TOEFL 100 min 22 per component"},
  {c:"eng_ms",l:"grad",g:"B/3.0",note:"Faculty of Engineering"},
  {c:"mba",l:"high",g:"B+",note:"Desautels MBA"},
  {c:"law_llm",l:"high",g:"B+",note:"Faculty of Law; IELTS W7.0 / TOEFL W25"},
  {c:"edu_ms",l:"def",g:"B+",note:"Faculty of Education"},
  {c:"bus_ms",l:"high",g:"B+",note:"Desautels MMA/MFin"},
  {c:"med",l:"high",g:"A-",note:"Faculty of Medicine and Health Sciences"},
  {c:"bio_ms",l:"grad",g:"B/3.0"}
],
 the:41,
 fee:{ug:"CAD 29,000-50,000",pg:"CAD 10,000-45,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length; Quebec CAQ required"},
 living:"CAD 15,000-20,000/yr",
 ddl:{fall:"Jan 15 (UG); Dec-Apr (Grad by dept)",winter:"Sep 15 (Grad)"},
 schol:["Entrance Scholarships (UG up to CAD 12k)","Vanier CGS (PhD CAD 50k/yr x3)","McGill Engineering Doctoral Award","MEDA (grad)"],
 materials:["transcripts","statement of purpose","letters of recommendation","CV/resume","English proficiency scores"]
},

{id:"waterloo",n:"滑铁卢大学",e:"University of Waterloo",c:"Waterloo, ON",r:112,cat:"u15",
 ll:{def:{ielts:{t:7.0,r:6,w:6,s:6,l:6},toefl:{t:90,r:null,w:25,s:25,l:null}},
     grad:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:90,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"ug",l:"def",g:"low-to-mid 90s",note:"IELTS 7.0; TOEFL 90 W25 S25"},
  {c:"cs_ms",l:"grad",g:"B+/80%",note:"David R. Cheriton School of CS"},
  {c:"cs_phd",l:"grad",g:"A-",note:"Fully funded; co-op available"},
  {c:"eng_ms",l:"grad",g:"B+/78%",note:"Faculty of Engineering"},
  {c:"mba",l:"grad",g:"B+",note:"Conrad School of Entrepreneurship & Business"},
  {c:"bus_ms",l:"grad",g:"B+",note:"School of Accounting & Finance"},
  {c:"edu_ms",l:"grad",g:"B+"},
  {c:"math_ms",l:"grad",g:"B+/80%",note:"Faculty of Mathematics"},
  {c:"ds_ms",l:"grad",g:"B+",note:"Master of Data Science & AI"}
],
 the:162,
 fee:{ug:"CAD 52,000-62,000",pg:"CAD 18,000-40,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 15,000-18,000/yr",
 ddl:{fall:"Feb 1 (UG); varies by dept (Grad)",winter:"Oct-Nov (Grad)"},
 schol:["President's Scholarship of Distinction (UG CAD 10k)","Vanier CGS (PhD CAD 50k/yr x3)","Graduate Research Studentship","International Master's Award of Excellence"],
 materials:["transcripts","statement of purpose","letters of recommendation","CV/resume","English proficiency scores"]
},

{id:"ualberta",n:"阿尔伯塔大学",e:"University of Alberta",c:"Edmonton, AB",r:96,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:90,r:21,w:21,s:21,l:21}},
     high:{ielts:{t:7.0,r:6,w:6,s:6,l:6},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"ug",l:"def",g:"mid-to-high 80s",note:"IELTS 6.5 no band <5.5"},
  {c:"cs_ms",l:"def",g:"3.0/4.0",note:"Dept of Computing Science"},
  {c:"eng_ms",l:"def",g:"3.0/4.0",note:"Faculty of Engineering"},
  {c:"mba",l:"high",g:"3.0/4.0",note:"Alberta School of Business"},
  {c:"edu_ms",l:"def",g:"3.0/4.0",note:"Faculty of Education"},
  {c:"bus_ms",l:"high",g:"3.0/4.0",note:"Alberta School of Business MACT/MFM"},
  {c:"law_llm",l:"high",g:"3.0/4.0",note:"Faculty of Law"},
  {c:"med",l:"high",g:"3.5/4.0",note:"Faculty of Medicine & Dentistry"}
],
 the:119,
 fee:{ug:"CAD 33,000-42,000",pg:"CAD 12,000-35,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 14,000-18,000/yr",
 ddl:{fall:"Mar 1 (UG); Dec-Mar (Grad)",winter:"Oct (Grad)"},
 schol:["International Student Scholarship (UG)","Vanier CGS (PhD CAD 50k/yr x3)","Alberta Graduate Excellence Scholarship","75th Anniversary Graduate Student Award"],
 materials:["transcripts","statement of purpose","letters of recommendation","CV/resume","English proficiency scores"]
},

{id:"mcmaster",n:"麦克马斯特大学",e:"McMaster University",c:"Hamilton, ON",r:152,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:86,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"ug",l:"def",g:"mid-to-high 80s",note:"IELTS 6.5; some programs require 7.0"},
  {c:"cs_ms",l:"def",g:"B+",note:"Dept of Computing & Software"},
  {c:"eng_ms",l:"def",g:"B",note:"Faculty of Engineering; TOEFL 88"},
  {c:"mba",l:"high",g:"B+",note:"DeGroote MBA; IELTS 7.0 / TOEFL 100"},
  {c:"bus_ms",l:"high",g:"B+",note:"DeGroote Finance/eHealth MSc"},
  {c:"edu_ms",l:"def",g:"B+"},
  {c:"med",l:"high",g:"A-",note:"Michael G. DeGroote School of Medicine"},
  {c:"ph_ms",l:"def",g:"B+",note:"Faculty of Health Sciences"}
],
 the:116,
 fee:{ug:"CAD 38,000-52,000",pg:"CAD 16,000-40,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 14,000-18,000/yr",
 ddl:{fall:"Jan 15 (UG); varies by dept (Grad)",winter:"Oct-Nov (Grad)"},
 schol:["Provost's Visiting Student Award","Vanier CGS (PhD CAD 50k/yr x3)","Ontario Graduate Scholarship","Graduate Scholarship"],
 materials:["transcripts","statement of purpose","letters of recommendation","CV/resume","English proficiency scores"]
},

// ============ U15 MID TIER ============
{id:"western",n:"韦仕敦大学",e:"Western University",c:"London, ON",r:114,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:86,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"ug",l:"def",g:"mid-to-high 80s",note:"IELTS 6.5; TOEFL 86 no section <20"},
  {c:"cs_ms",l:"def",g:"B+/78%",note:"Dept of Computer Science"},
  {c:"eng_ms",l:"def",g:"B/70%",note:"Faculty of Engineering"},
  {c:"mba",l:"high",g:"B+",note:"Ivey MBA; GMAT required"},
  {c:"bus_ms",l:"high",g:"B+",note:"Ivey MSc/MFin"},
  {c:"law_llm",l:"high",g:"B+",note:"Faculty of Law"},
  {c:"edu_ms",l:"def",g:"B+",note:"Faculty of Education"},
  {c:"med",l:"high",g:"A-",note:"Schulich School of Medicine"}
],
 the:201,
 fee:{ug:"CAD 40,000-55,000",pg:"CAD 15,000-45,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 14,000-17,000/yr",
 ddl:{fall:"Jan 15 (UG); varies by dept (Grad)",winter:"Oct-Nov (Grad)"},
 schol:["Western Scholarship of Excellence (UG)","Vanier CGS (PhD CAD 50k/yr x3)","Ontario Graduate Scholarship","Western Graduate Research Scholarship"],
 materials:["transcripts","statement of purpose","letters of recommendation","CV/resume","English proficiency scores"]
},

{id:"queens",n:"女王大学",e:"Queen's University",c:"Kingston, ON",r:176,cat:"u15",
 ll:{def:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:88,r:null,w:null,s:null,l:null}},
     high:{ielts:{t:7.5,r:null,w:null,s:null,l:null},toefl:{t:100,r:24,w:24,s:24,l:24}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"ug",l:"def",g:"mid-to-high 80s",note:"IELTS 7.0 (Academic)"},
  {c:"cs_ms",l:"def",g:"B+",note:"School of Computing"},
  {c:"eng_ms",l:"def",g:"B+",note:"Faculty of Engineering & Applied Science"},
  {c:"mba",l:"high",g:"B+",note:"Smith School of Business MBA"},
  {c:"bus_ms",l:"high",g:"B+",note:"Smith MFin/MMA"},
  {c:"law_llm",l:"high",g:"B+",note:"Faculty of Law"},
  {c:"edu_ms",l:"def",g:"B+",note:"Faculty of Education"},
  {c:"med",l:"high",g:"A-",note:"School of Medicine"}
],
 the:251,
 fee:{ug:"CAD 45,000-55,000",pg:"CAD 15,000-42,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 13,000-17,000/yr",
 ddl:{fall:"Feb 1 (UG); varies by dept (Grad)",winter:"Oct-Nov (Grad)"},
 schol:["Queen's International Scholarship","Vanier CGS (PhD CAD 50k/yr x3)","Ontario Graduate Scholarship","Banting Postdoctoral Fellowship"],
 materials:["transcripts","statement of purpose","letters of recommendation","CV/resume","English proficiency scores"]
},

{id:"uottawa",n:"渥太华大学",e:"University of Ottawa",c:"Ottawa, ON",r:203,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:86,r:null,w:22,s:null,l:null}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"ug",l:"def",g:"mid-to-high 70s",note:"IELTS 6.5; TOEFL 86 W22; bilingual campus"},
  {c:"cs_ms",l:"def",g:"B+/75%",note:"School of EECS"},
  {c:"eng_ms",l:"def",g:"B/70%",note:"Faculty of Engineering"},
  {c:"mba",l:"high",g:"B+",note:"Telfer MBA"},
  {c:"bus_ms",l:"high",g:"B+",note:"Telfer MHA/MSc Management"},
  {c:"law_llm",l:"high",g:"B+",note:"Faculty of Law (Civil & Common Law)"},
  {c:"edu_ms",l:"def",g:"B+",note:"Faculty of Education"},
  {c:"med",l:"high",g:"A-",note:"Faculty of Medicine"}
],
 the:187,
 fee:{ug:"CAD 35,000-50,000",pg:"CAD 13,000-38,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 14,000-18,000/yr",
 ddl:{fall:"Apr 1 (UG); Jan-Mar (Grad)",winter:"Nov (Grad)"},
 schol:["International Admission Scholarship (UG)","Vanier CGS (PhD CAD 50k/yr x3)","Ontario Graduate Scholarship","Excellence Scholarship"],
 materials:["transcripts","statement of purpose","letters of recommendation","CV/resume","English proficiency scores"]
},

{id:"dalhousie",n:"达尔豪斯大学",e:"Dalhousie University",c:"Halifax, NS",r:298,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}},
     grad:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:92,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"ug",l:"def",g:"mid-to-high 70s",note:"IELTS 6.5 no band <6.0"},
  {c:"cs_ms",l:"grad",g:"B+/3.3",note:"Faculty of Computer Science"},
  {c:"eng_ms",l:"grad",g:"B/3.0",note:"Faculty of Engineering"},
  {c:"mba",l:"grad",g:"B+",note:"Rowe School of Business"},
  {c:"bus_ms",l:"grad",g:"B+",note:"Rowe MFin"},
  {c:"law_llm",l:"grad",g:"B+",note:"Schulich School of Law"},
  {c:"edu_ms",l:"grad",g:"B+"},
  {c:"med",l:"grad",g:"A-",note:"Faculty of Medicine"}
],
 the:301,
 fee:{ug:"CAD 25,000-38,000",pg:"CAD 12,000-32,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 13,000-17,000/yr",
 ddl:{fall:"Apr 1 (UG); varies by dept (Grad)",winter:"Oct-Nov (Grad)"},
 schol:["Entrance Scholarships (UG)","Vanier CGS (PhD CAD 50k/yr x3)","Faculty of Graduate Studies Scholarship","Killam Predoctoral Scholarship"],
 materials:["transcripts","statement of purpose","letters of recommendation","CV/resume","English proficiency scores"]
},

{id:"ucalgary",n:"卡尔加里大学",e:"University of Calgary",c:"Calgary, AB",r:175,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:86,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6,w:6,s:6,l:6},toefl:{t:97,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"ug",l:"def",g:"mid-to-high 80s",note:"IELTS 6.5; TOEFL 86 no section <20"},
  {c:"cs_ms",l:"def",g:"3.0/4.0",note:"Dept of Computer Science"},
  {c:"eng_ms",l:"def",g:"3.0/4.0",note:"Schulich School of Engineering"},
  {c:"mba",l:"high",g:"3.0/4.0",note:"Haskayne School of Business"},
  {c:"bus_ms",l:"high",g:"3.0/4.0",note:"Haskayne specialized masters"},
  {c:"law_llm",l:"def",g:"3.3/4.0",note:"Faculty of Law"},
  {c:"edu_ms",l:"def",g:"3.0/4.0",note:"Werklund School of Education"},
  {c:"med",l:"high",g:"3.5/4.0",note:"Cumming School of Medicine"}
],
 the:201,
 fee:{ug:"CAD 28,000-40,000",pg:"CAD 12,000-35,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 14,000-18,000/yr",
 ddl:{fall:"Mar 1 (UG); varies by dept (Grad)",winter:"Oct (Grad)"},
 schol:["International Entrance Scholarship (UG)","Vanier CGS (PhD CAD 50k/yr x3)","Alberta Graduate Excellence Scholarship","Eyes High Doctoral Recruitment Scholarship"],
 materials:["transcripts","statement of purpose","letters of recommendation","CV/resume","English proficiency scores"]
},

{id:"umontreal",n:"蒙特利尔大学",e:"Université de Montréal",c:"Montreal, QC",r:141,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:21,w:21,s:21,l:21}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"ug",l:"def",g:"mid-to-high 80s",note:"French-language university; most programs require French (DELF/DALF)"},
  {c:"cs_ms",l:"def",g:"3.0/4.3",note:"DIRO; some English-taught options; Mila AI institute"},
  {c:"eng_ms",l:"def",g:"3.0/4.3",note:"Polytechnique Montreal affiliated"},
  {c:"mba",l:"high",g:"3.0/4.3",note:"HEC Montreal (affiliated); IELTS 7.0"},
  {c:"bus_ms",l:"high",g:"3.0/4.3",note:"HEC Montreal MSc programs"},
  {c:"edu_ms",l:"def",g:"3.0/4.3",note:"Faculty of Education; French required"},
  {c:"law_llm",l:"def",g:"3.0/4.3",note:"Faculty of Law; French required"},
  {c:"med",l:"high",g:"3.5/4.3",note:"Faculty of Medicine; French required"}
],
 the:150,
 fee:{ug:"CAD 25,000-35,000",pg:"CAD 10,000-30,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length; Quebec CAQ required"},
 living:"CAD 14,000-18,000/yr",
 ddl:{fall:"Feb 1 (UG); Dec-Mar (Grad)",winter:"Nov (Grad)"},
 schol:["Bursaries for international students","Vanier CGS (PhD CAD 50k/yr x3)","FRQNT Scholarship (Quebec)","Banting Postdoctoral Fellowship"],
 materials:["transcripts","statement of purpose","letters of recommendation","CV/resume","English/French proficiency scores"]
},

// ============ OTHER NOTABLE ============
{id:"sfu",n:"西蒙菲莎大学",e:"Simon Fraser University",c:"Burnaby, BC",r:328,cat:"other",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:88,r:20,w:20,s:20,l:20}},
     grad:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:93,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"ug",l:"def",g:"mid-to-high 80s",note:"IELTS 6.5 no band <6.0; TOEFL 88 no section <20"},
  {c:"cs_ms",l:"grad",g:"B+/3.33",note:"School of Computing Science"},
  {c:"eng_ms",l:"grad",g:"B+/3.0",note:"Faculty of Applied Sciences"},
  {c:"mba",l:"grad",g:"B+",note:"Beedie MBA"},
  {c:"bus_ms",l:"grad",g:"B+",note:"Beedie MoT/MSc Finance"},
  {c:"edu_ms",l:"grad",g:"B+",note:"Faculty of Education"},
  {c:"ds_ms",l:"grad",g:"B+",note:"Professional Master's in Big Data"}
],
 the:251,
 fee:{ug:"CAD 32,000-38,000",pg:"CAD 10,000-30,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 17,000-22,000/yr",
 ddl:{fall:"Jan 31 (UG); varies by dept (Grad)",winter:"Sep (Grad)"},
 schol:["SFU Open Scholarship (UG)","Vanier CGS (PhD CAD 50k/yr x3)","Graduate Fellowship","Banting Postdoctoral Fellowship"],
 materials:["transcripts","statement of purpose","letters of recommendation","CV/resume","English proficiency scores"]
},

{id:"uvic",n:"维多利亚大学",e:"University of Victoria",c:"Victoria, BC",r:322,cat:"other",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:95,r:21,w:21,s:21,l:21}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"ug",l:"def",g:"mid-to-high 80s",note:"IELTS 6.5 no band <6.0; TOEFL 90 no section <20"},
  {c:"cs_ms",l:"def",g:"B+",note:"Dept of Computer Science"},
  {c:"eng_ms",l:"def",g:"B+",note:"Faculty of Engineering & Computer Science"},
  {c:"mba",l:"high",g:"B+",note:"Gustavson School of Business"},
  {c:"bus_ms",l:"high",g:"B+",note:"Gustavson MGB"},
  {c:"edu_ms",l:"high",g:"B+",note:"Faculty of Education"},
  {c:"law_llm",l:"high",g:"B+",note:"Faculty of Law"}
],
 the:301,
 fee:{ug:"CAD 28,000-36,000",pg:"CAD 10,000-28,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 16,000-20,000/yr",
 ddl:{fall:"Feb 28 (UG); varies by dept (Grad)",winter:"Oct (Grad)"},
 schol:["UVic International Entrance Scholarship","Vanier CGS (PhD CAD 50k/yr x3)","Graduate Fellowship","President's Research Scholarship"],
 materials:["transcripts","statement of purpose","letters of recommendation","CV/resume","English proficiency scores"]
},

{id:"york",n:"约克大学",e:"York University",c:"Toronto, ON",r:353,cat:"other",
 ll:{def:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:88,r:null,w:null,s:null,l:null}},
     grad:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}},
     high:{ielts:{t:7.5,r:7,w:7,s:7,l:6.5},toefl:{t:103,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"ug",l:"def",g:"mid-to-high 70s",note:"IELTS 6.5; TOEFL 88"},
  {c:"cs_ms",l:"grad",g:"B+",note:"Lassonde School of Engineering"},
  {c:"eng_ms",l:"grad",g:"B+",note:"Lassonde"},
  {c:"mba",l:"grad",g:"B+",note:"Schulich MBA; globally ranked"},
  {c:"bus_ms",l:"grad",g:"B+",note:"Schulich MBAN/MFin/MREI"},
  {c:"law_llm",l:"grad",g:"B+",note:"Osgoode Hall Law School"},
  {c:"edu_ms",l:"high",g:"B+",note:"Faculty of Education; TOEFL 103"},
  {c:"ph_ms",l:"grad",g:"B+",note:"School of Health Policy & Management"}
],
 the:401,
 fee:{ug:"CAD 30,000-40,000",pg:"CAD 12,000-35,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 16,000-20,000/yr",
 ddl:{fall:"Feb 1 (UG); varies by dept (Grad)",winter:"Oct-Nov (Grad)"},
 schol:["International Entrance Scholarship of Distinction","Vanier CGS (PhD CAD 50k/yr x3)","Ontario Graduate Scholarship","York Graduate Scholarship"],
 materials:["transcripts","statement of purpose","letters of recommendation","CV/resume","English proficiency scores"]
}
];
COMPASS_DATA.ca = D;
})();
