// data-uk.js - UK Universities - Undergraduate Programs Only
// v4.0 - All programs are bachelor's level (BSc/BA/BEng/LLB/MBBS etc.)
(function(){
var D = [
// ============ RUSSELL GROUP TOP ============
{id:"oxford",n:"牛津大学",e:"University of Oxford",c:"Oxford",r:3,cat:"russell",
 ll:{std:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:24,w:24,s:25,l:22}},
     high:{ielts:{t:7.5,r:7,w:7,s:7,l:7},toefl:{t:110,r:24,w:24,s:25,l:22}}},
 pol:{nt:"suspended",mb:false,v:"2y",note:"Paused new TOEFL from 21 Jan 2026"},
 fee:{ug:"GBP 33,050-48,620",currency:"GBP"},
 living:"GBP 13,000-17,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa 2yr post-study work"},
 ddl:{fall:"Oct 15 (UCAS deadline for Oxford)"},
 schol:["Clarendon Fund","Rhodes Scholarship","Oxford-China Scholarship"],
 materials:["UCAS","PS","Admissions test","Interview","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA",note:"Maths + further maths recommended; MAT test required"},
  {c:"eng",l:"std",g:"A*A*A",note:"Engineering Science; PAT test required"},
  {c:"math",l:"std",g:"A*A*A",note:"MAT test required"},
  {c:"phys",l:"std",g:"A*AA",note:"PAT test required"},
  {c:"chem",l:"std",g:"A*A*A",note:"Chemistry BSc/MChem"},
  {c:"bio",l:"std",g:"A*AA",note:"Biological Sciences"},
  {c:"med",l:"high",g:"A*AA",note:"BMAT required; IB 39+"},
  {c:"law",l:"high",g:"AAA",note:"LNAT test required"},
  {c:"econ",l:"std",g:"A*AA",note:"Economics & Management; TSA test"},
  {c:"hist",l:"high",g:"AAA",note:"HAT test required"},
  {c:"psych",l:"std",g:"A*AA",note:"Experimental Psychology; TSA test"},
  {c:"phil",l:"high",g:"AAA",note:"Philosophy Politics Economics (PPE)"},
  {c:"ling",l:"high",g:"AAA",note:"Modern Languages"},
  {c:"ir",l:"high",g:"AAA",note:"Politics sub-fields available"}
]},

{id:"cambridge",n:"剑桥大学",e:"University of Cambridge",c:"Cambridge",r:2,cat:"russell",
 ll:{def:{ielts:{t:7.5,r:7,w:7,s:7,l:7},toefl:{t:110,r:25,w:25,s:25,l:25}}},
 pol:{nt:"suspended",mb:false,v:"2y",note:"Paused new TOEFL"},
 fee:{ug:"GBP 33,825-61,000",currency:"GBP"},
 living:"GBP 13,000-17,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Oct 15 (UCAS)"},
 schol:["Cambridge Trust","Gates Cambridge Scholarship","College-specific awards"],
 materials:["UCAS","PS","Admissions test","Interview","Transcript","SAQ"],
 p:[
  {c:"cs",l:"def",g:"A*A*A",note:"TMUA test recommended; IB 42+"},
  {c:"eng",l:"def",g:"A*A*A",note:"Engineering; ENGAA test required"},
  {c:"math",l:"def",g:"A*A*A",note:"STEP required; further maths essential"},
  {c:"phys",l:"def",g:"A*A*A",note:"Natural Sciences (Physical)"},
  {c:"chem",l:"def",g:"A*A*A",note:"Natural Sciences (Chemistry)"},
  {c:"bio",l:"def",g:"A*A*A",note:"Natural Sciences (Biological)"},
  {c:"med",l:"def",g:"A*A*A",note:"BMAT required; IB 40-42"},
  {c:"law",l:"def",g:"A*AA",note:"LNAT may be required"},
  {c:"econ",l:"def",g:"A*A*A",note:"Economics; TMUA recommended"},
  {c:"hist",l:"def",g:"A*AA"},
  {c:"arch",l:"def",g:"A*AA",note:"Architecture; portfolio required"},
  {c:"vet",l:"def",g:"A*AA",note:"Veterinary Medicine"},
  {c:"psych",l:"def",g:"A*A*A",note:"Psychological & Behavioural Sciences"}
]},

{id:"imperial",n:"帝国理工学院",e:"Imperial College London",c:"London",r:6,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:92,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"accepted",mb:false,v:"2y"},
 fee:{ug:"GBP 36,700-49,400",currency:"GBP"},
 living:"GBP 15,000-18,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine"},
 schol:["President's UG Scholarship","Imperial Bursary","Department-specific awards"],
 materials:["UCAS","PS","Interview (some)","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*A*A",note:"MAT test; IB 39-41"},
  {c:"ee",l:"std",g:"A*AA",note:"Electronic & Electrical Engineering"},
  {c:"me",l:"std",g:"A*A*A",note:"Mechanical Engineering"},
  {c:"ce",l:"std",g:"A*AA",note:"Civil Engineering"},
  {c:"math",l:"std",g:"A*A*A",note:"Further maths required; IB 39-41"},
  {c:"phys",l:"std",g:"A*A*A"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA",note:"Biological Sciences / Biochemistry"},
  {c:"med",l:"high",g:"A*AA",note:"BMAT/UCAT; IB 38+"},
  {c:"ds",l:"std",g:"A*AA",note:"Mathematics with Statistics"},
  {c:"ai",l:"std",g:"A*A*A",note:"Computing (AI & ML specialism)"},
  {c:"env",l:"std",g:"AAA",note:"Earth Science & Engineering"}
]},

{id:"ucl",n:"伦敦大学学院",e:"University College London",c:"London",r:9,cat:"russell",
 ll:{l1:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:92,r:24,w:24,s:20,l:20}},
     l2:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:96,r:24,w:24,s:22,l:22}},
     l3:{ielts:{t:7.0,r:7,w:7,s:7,l:7},toefl:{t:100,r:25,w:25,s:23,l:23}},
     l4:{ielts:{t:7.5,r:7,w:7,s:7,l:7},toefl:{t:109,r:27,w:27,s:23,l:23}},
     l5:{ielts:{t:8.0,r:8,w:8,s:8,l:8},toefl:{t:110,r:29,w:29,s:23,l:23}}},
 pol:{nt:"published",mb:false,v:"2y"},
 fee:{ug:"GBP 28,500-42,000",currency:"GBP"},
 living:"GBP 15,000-18,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine"},
 schol:["UCL Global UG Scholarship","Denys Holland Scholarship","Faculty-specific bursaries"],
 materials:["UCAS","PS","Transcript","Portfolio (some)"],
 p:[
  {c:"cs",l:"l1",g:"A*A*A",note:"Level 1 English; IB 40"},
  {c:"ee",l:"l1",g:"A*AA",note:"Electronic & Electrical Engineering"},
  {c:"arch",l:"l2",g:"AAB",note:"Bartlett School; portfolio required"},
  {c:"math",l:"l1",g:"A*A*A",note:"Further maths required"},
  {c:"phys",l:"l1",g:"A*A*A"},
  {c:"chem",l:"l1",g:"AAA"},
  {c:"bio",l:"l1",g:"AAA"},
  {c:"med",l:"l5",g:"A*AA",note:"UCAT; Level 5 English; IB 39"},
  {c:"law",l:"l4",g:"A*AA",note:"LNAT; Level 4 English"},
  {c:"econ",l:"l2",g:"A*AA"},
  {c:"psych",l:"l3",g:"A*AA"},
  {c:"edu",l:"l3",g:"ABB",note:"IOE - top ranked education"},
  {c:"stat",l:"l1",g:"A*AA",note:"Statistical Science"},
  {c:"ling",l:"l4",g:"ABB",note:"Linguistics"},
  {c:"hist",l:"l4",g:"AAA"},
  {c:"phil",l:"l4",g:"AAA"},
  {c:"media",l:"l3",g:"AAB",note:"Information Management / Digital Media"}
]},

{id:"lse",n:"伦敦政治经济学院",e:"LSE",c:"London",r:50,cat:"russell",
 ll:{std:{ielts:{t:7.0,r:7,w:7,s:7,l:7},toefl:{t:107,r:25,w:25,s:24,l:24}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 26,184-38,736",currency:"GBP"},
 living:"GBP 15,000-18,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["LSE UG Support Scheme","LSE Financial Support Office awards"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"econ",l:"std",g:"A*AA",note:"Economics BSc; maths A* essential; IB 38"},
  {c:"fin",l:"std",g:"A*AA",note:"Finance BSc; maths A* essential"},
  {c:"acct",l:"std",g:"AAA",note:"Accounting & Finance BSc"},
  {c:"bus",l:"std",g:"AAA",note:"Management BSc"},
  {c:"law",l:"std",g:"A*AA",note:"LNAT required"},
  {c:"ir",l:"std",g:"AAA",note:"International Relations BSc"},
  {c:"pub",l:"std",g:"AAA",note:"Politics / Government BSc"},
  {c:"hist",l:"std",g:"AAA"},
  {c:"math",l:"std",g:"A*A*A",note:"Mathematics & Economics"},
  {c:"stat",l:"std",g:"A*AA",note:"Actuarial Science / Statistics"},
  {c:"psych",l:"std",g:"A*AA",note:"Psychological & Behavioural Science"},
  {c:"soc",l:"std",g:"AAA",note:"Sociology BSc"},
  {c:"media",l:"std",g:"AAA",note:"Media & Communications"}
]},

{id:"edinburgh",n:"爱丁堡大学",e:"University of Edinburgh",c:"Edinburgh",r:22,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:5.5,w:6.0,s:5.5,l:5.5},toefl:{t:92,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:23,w:23,s:23,l:23}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 25,300-36,500",currency:"GBP"},
 living:"GBP 12,000-15,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine"},
 schol:["Edinburgh Global UG Scholarship","Principal's Career Development Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA",note:"Informatics BSc; IB 37"},
  {c:"ai",l:"std",g:"A*AA",note:"AI BSc - pioneering programme"},
  {c:"eng",l:"std",g:"AAA-ABB",note:"Various engineering disciplines"},
  {c:"math",l:"std",g:"A*AA"},
  {c:"phys",l:"std",g:"A*AA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"chem",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"A*AA",note:"UCAT required; IB 37"},
  {c:"vet",l:"high",g:"A*AA",note:"Royal (Dick) Vet School"},
  {c:"law",l:"high",g:"A*AA",note:"Scots & English law"},
  {c:"econ",l:"std",g:"A*AA"},
  {c:"bus",l:"std",g:"AAA",note:"Business School"},
  {c:"hist",l:"high",g:"AAA"},
  {c:"psych",l:"std",g:"AAA"},
  {c:"ling",l:"high",g:"AAA-AAB"},
  {c:"arch",l:"std",g:"AAA",note:"Edinburgh College of Art"}
]},

{id:"manchester",n:"曼彻斯特大学",e:"University of Manchester",c:"Manchester",r:32,cat:"russell",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}},
     med:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 25,000-35,000",currency:"GBP"},
 living:"GBP 10,000-13,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine/Dentistry"},
 schol:["Manchester Master's Bursary","Equity & Merit Scholarship","International Excellence UG"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA",note:"IB 37"},
  {c:"ee",l:"std",g:"AAA",note:"EEE / Mechatronics"},
  {c:"me",l:"std",g:"AAA"},
  {c:"ce",l:"std",g:"AAA"},
  {c:"math",l:"std",g:"A*AA"},
  {c:"phys",l:"std",g:"A*AA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"A*AA",note:"UCAT required"},
  {c:"dent",l:"high",g:"AAA",note:"UCAT required"},
  {c:"law",l:"high",g:"AAA"},
  {c:"econ",l:"med",g:"AAA"},
  {c:"bus",l:"med",g:"AAA",note:"Alliance MBS"},
  {c:"psych",l:"med",g:"AAA"},
  {c:"arch",l:"std",g:"AAA",note:"Manchester School of Architecture"},
  {c:"env",l:"std",g:"AAA-AAB"}
]},

{id:"kcl",n:"伦敦国王学院",e:"King's College London",c:"London",r:37,cat:"russell",
 ll:{a:{ielts:{t:7.5,r:7,w:7,s:7,l:7},toefl:{t:109,r:27,w:27,s:23,l:23}},
     b:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:24,w:24,s:20,l:20}},
     c:{ielts:{t:7.0,r:6,w:6,s:6,l:6},toefl:{t:96,r:23,w:23,s:20,l:20}},
     d:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:92,r:20,w:20,s:20,l:20}},
     e:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:18,l:18}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 26,500-42,000",currency:"GBP"},
 living:"GBP 15,000-18,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine/Dentistry"},
 schol:["KCL International Bursary","Desmond Tutu Scholarship","Faculty-specific awards"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"d",g:"A*AA",note:"Band D"},
  {c:"math",l:"d",g:"A*AA"},
  {c:"phys",l:"e",g:"AAA-AAB"},
  {c:"chem",l:"e",g:"AAA-AAB"},
  {c:"bio",l:"d",g:"AAA-AAB"},
  {c:"med",l:"a",g:"A*AA",note:"UCAT; Band A; IB 35 A*AA"},
  {c:"dent",l:"a",g:"A*AA",note:"UCAT; Band A"},
  {c:"nurs",l:"b",g:"ABB",note:"Band B; OSCE"},
  {c:"law",l:"b",g:"A*AA",note:"LNAT; Band B"},
  {c:"econ",l:"c",g:"AAA",note:"Band C"},
  {c:"psych",l:"c",g:"AAA"},
  {c:"hist",l:"b",g:"AAA"},
  {c:"ir",l:"b",g:"AAA",note:"War Studies / International Relations"},
  {c:"ling",l:"b",g:"AAA-AAB"},
  {c:"edu",l:"b",g:"ABB"},
  {c:"pharm",l:"d",g:"AAB"}
]},

{id:"bristol",n:"布里斯托大学",e:"University of Bristol",c:"Bristol",r:55,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 24,700-34,800",currency:"GBP"},
 living:"GBP 11,000-14,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine/Dentistry/Vet"},
 schol:["Think Big UG Scholarship","Bristol Scholars","Faculty awards"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA",note:"IB 38"},
  {c:"eng",l:"std",g:"A*AA",note:"Various engineering BEng/MEng"},
  {c:"math",l:"std",g:"A*A*A"},
  {c:"phys",l:"std",g:"A*AA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"A*AA",note:"UCAT required"},
  {c:"dent",l:"high",g:"AAA",note:"UCAT required"},
  {c:"vet",l:"high",g:"A*AA"},
  {c:"law",l:"high",g:"A*AA"},
  {c:"econ",l:"std",g:"A*AA"},
  {c:"psych",l:"std",g:"AAA"},
  {c:"env",l:"std",g:"AAA-AAB"}
]},

{id:"warwick",n:"华威大学",e:"University of Warwick",c:"Coventry",r:67,cat:"russell",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:21,s:20,l:18}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:23,l:21}}},
 pol:{nt:"accepted",mb:false,v:"2y"},
 fee:{ug:"GBP 24,600-34,000",currency:"GBP"},
 living:"GBP 10,000-13,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["Warwick UG Global Excellence Scholarship","Warwick Chancellor's Intl Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*A*A",note:"IB 39"},
  {c:"eng",l:"std",g:"A*AA",note:"Engineering BEng/MEng"},
  {c:"math",l:"std",g:"A*A*A",note:"STEP recommended; IB 39"},
  {c:"phys",l:"std",g:"A*AA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"A*AA",note:"Warwick-HYMS joint; UCAT"},
  {c:"law",l:"high",g:"A*AA",note:"LNAT"},
  {c:"econ",l:"high",g:"A*A*A",note:"Maths A* required; IB 39"},
  {c:"bus",l:"high",g:"A*AA",note:"WBS Management BSc"},
  {c:"fin",l:"high",g:"A*AA",note:"WBS Accounting & Finance"},
  {c:"psych",l:"std",g:"AAA"},
  {c:"hist",l:"high",g:"AAA"},
  {c:"media",l:"high",g:"AAA",note:"Film & Television Studies"}
]},

// ============ RUSSELL GROUP MID ============
{id:"glasgow",n:"格拉斯哥大学",e:"University of Glasgow",c:"Glasgow",r:76,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:23,w:23,s:23,l:23}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 22,000-31,000",currency:"GBP"},
 living:"GBP 10,000-13,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine/Dentistry/Vet"},
 schol:["Glasgow Excellence Entrance Scholarship","International Leadership Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"AAA-AAB",note:"Computing Science BSc; IB 36-38"},
  {c:"eng",l:"std",g:"AAA-AAB",note:"Various engineering BSc/BEng"},
  {c:"math",l:"std",g:"AAA"},
  {c:"phys",l:"std",g:"AAA-AAB"},
  {c:"chem",l:"std",g:"AAA-AAB"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"AAA",note:"UCAT required; Scottish 4-yr degree possible"},
  {c:"dent",l:"high",g:"AAA",note:"UCAT required"},
  {c:"vet",l:"high",g:"AAA",note:"School of Veterinary Medicine"},
  {c:"law",l:"high",g:"AAA",note:"Scots law LLB"},
  {c:"econ",l:"std",g:"AAA",note:"Adam Smith Business School"},
  {c:"bus",l:"std",g:"AAA-AAB"},
  {c:"psych",l:"std",g:"AAA-AAB"},
  {c:"hist",l:"high",g:"AAA-AAB"}
]},

{id:"durham",n:"杜伦大学",e:"Durham University",c:"Durham",r:78,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:92,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:102,r:25,w:25,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 24,500-33,500",currency:"GBP"},
 living:"GBP 10,000-13,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["Vice-Chancellor's Scholarship","Durham Inspired Awards"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA",note:"IB 38"},
  {c:"eng",l:"std",g:"A*AA"},
  {c:"math",l:"std",g:"A*A*A"},
  {c:"phys",l:"std",g:"A*AA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA"},
  {c:"law",l:"high",g:"A*AA",note:"LNAT required"},
  {c:"econ",l:"std",g:"A*AA",note:"Durham University Business School"},
  {c:"bus",l:"std",g:"AAA"},
  {c:"psych",l:"std",g:"AAA"},
  {c:"hist",l:"high",g:"AAA"},
  {c:"phil",l:"high",g:"AAA"},
  {c:"edu",l:"std",g:"ABB-BBB"}
]},

{id:"leeds",n:"利兹大学",e:"University of Leeds",c:"Leeds",r:75,cat:"russell",
 ll:{l60:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}},
     l65:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:88,r:20,w:21,s:22,l:19}},
     l70:{ielts:{t:7.0,r:6,w:6,s:6,l:6},toefl:{t:96,r:22,w:22,s:23,l:21}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 23,500-31,500",currency:"GBP"},
 living:"GBP 10,000-12,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["Leeds Academic Excellence Intl Scholarship","Tetley & Lupton Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"l65",g:"A*AA",note:"IB 36"},
  {c:"ee",l:"l60",g:"AAA",note:"Electronic & Electrical Engineering"},
  {c:"me",l:"l60",g:"AAA"},
  {c:"ce",l:"l60",g:"AAA"},
  {c:"math",l:"l65",g:"A*AA"},
  {c:"phys",l:"l60",g:"AAA-AAB"},
  {c:"chem",l:"l60",g:"AAA-AAB"},
  {c:"bio",l:"l60",g:"AAA-AAB"},
  {c:"med",l:"l70",g:"A*AA",note:"UCAT required"},
  {c:"law",l:"l70",g:"A*AA"},
  {c:"econ",l:"l65",g:"AAA"},
  {c:"bus",l:"l65",g:"AAA-AAB"},
  {c:"psych",l:"l65",g:"AAA"},
  {c:"media",l:"l70",g:"AAA",note:"School of Media & Communication - top ranked"},
  {c:"edu",l:"l65",g:"ABB-BBB"}
]},

{id:"sheffield",n:"谢菲尔德大学",e:"University of Sheffield",c:"Sheffield",r:91,cat:"russell",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:95,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 22,700-31,000",currency:"GBP"},
 living:"GBP 9,500-12,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["Sheffield UG International Scholarship","Department-specific awards"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA",note:"IB 36"},
  {c:"eng",l:"std",g:"AAA",note:"Various engineering programmes"},
  {c:"math",l:"std",g:"A*AA"},
  {c:"phys",l:"std",g:"AAA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"AAA",note:"UCAT required"},
  {c:"dent",l:"high",g:"AAA"},
  {c:"law",l:"high",g:"AAA"},
  {c:"econ",l:"std",g:"AAA"},
  {c:"arch",l:"std",g:"AAA",note:"Top ranked architecture"},
  {c:"psych",l:"std",g:"AAA"},
  {c:"media",l:"high",g:"AAA-AAB",note:"Journalism Studies"}
]},

{id:"southampton",n:"南安普顿大学",e:"University of Southampton",c:"Southampton",r:80,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 22,300-29,000",currency:"GBP"},
 living:"GBP 10,000-13,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine"},
 schol:["Southampton Merit Scholarship","International Foundation Year Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA",note:"Electronics & CS strong"},
  {c:"ee",l:"std",g:"AAA",note:"Top for ECS"},
  {c:"me",l:"std",g:"AAA"},
  {c:"ce",l:"std",g:"AAA"},
  {c:"math",l:"std",g:"A*AA"},
  {c:"phys",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"A*AA",note:"UCAT required"},
  {c:"law",l:"high",g:"AAA"},
  {c:"econ",l:"std",g:"AAA"},
  {c:"env",l:"std",g:"AAA-AAB",note:"Ocean & Earth Science"},
  {c:"ds",l:"std",g:"A*AA"}
]},

{id:"nottingham",n:"诺丁汉大学",e:"University of Nottingham",c:"Nottingham",r:100,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:87,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6,w:6,s:6,l:6},toefl:{t:100,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 22,000-29,000",currency:"GBP"},
 living:"GBP 9,500-12,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine/Vet"},
 schol:["Nottingham High Achiever Scholarship","Developing Solutions UG Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA",note:"IB 36"},
  {c:"eng",l:"std",g:"AAA"},
  {c:"math",l:"std",g:"A*AA"},
  {c:"phys",l:"std",g:"AAA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"A*AA",note:"UCAT required"},
  {c:"vet",l:"high",g:"AAA"},
  {c:"pharm",l:"std",g:"AAB"},
  {c:"law",l:"high",g:"AAA"},
  {c:"econ",l:"std",g:"A*AA"},
  {c:"bus",l:"std",g:"AAA",note:"Nottingham University Business School"},
  {c:"psych",l:"std",g:"AAA"}
]},

{id:"birmingham",n:"伯明翰大学",e:"University of Birmingham",c:"Birmingham",r:84,cat:"russell",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}},
     med:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:88,r:20,w:20,s:21,l:19}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:95,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 22,260-29,940",currency:"GBP"},
 living:"GBP 10,000-13,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS); Oct 15 for Medicine/Dentistry"},
 schol:["Birmingham Elite Scholarship","International Scholarship Programme"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA"},
  {c:"eng",l:"std",g:"AAA"},
  {c:"math",l:"std",g:"A*AA"},
  {c:"phys",l:"std",g:"AAA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA"},
  {c:"med",l:"high",g:"A*AA",note:"UCAT; IB 32+"},
  {c:"dent",l:"high",g:"AAA",note:"UCAT required"},
  {c:"law",l:"high",g:"AAA"},
  {c:"econ",l:"med",g:"AAA"},
  {c:"bus",l:"med",g:"AAA-AAB",note:"Birmingham Business School"},
  {c:"psych",l:"med",g:"AAA"},
  {c:"edu",l:"med",g:"ABB-BBB"}
]},

{id:"standrews",n:"圣安德鲁斯大学",e:"University of St Andrews",c:"St Andrews",r:68,cat:"other",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:24,w:24,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 25,000-33,000",currency:"GBP"},
 living:"GBP 10,000-12,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["St Andrews International Scholarship","600th Anniversary Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"AAA",note:"IB 36"},
  {c:"math",l:"std",g:"AAA"},
  {c:"phys",l:"std",g:"AAA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"ir",l:"high",g:"AAA",note:"School of International Relations top ranked"},
  {c:"econ",l:"std",g:"AAA"},
  {c:"hist",l:"high",g:"AAA"},
  {c:"phil",l:"high",g:"AAA"},
  {c:"psych",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"A*AA",note:"Gateway to Medicine programme"}
]},

{id:"exeter",n:"埃克塞特大学",e:"University of Exeter",c:"Exeter",r:130,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6,w:6,s:6,l:6},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 22,500-29,500",currency:"GBP"},
 living:"GBP 10,000-13,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["Exeter Global Excellence Scholarship","Subject-specific awards"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA"},
  {c:"eng",l:"std",g:"AAA-AAB"},
  {c:"math",l:"std",g:"A*AA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"med",l:"high",g:"A*AA",note:"UCAT required"},
  {c:"law",l:"high",g:"A*AA"},
  {c:"econ",l:"std",g:"A*AA"},
  {c:"bus",l:"std",g:"AAA",note:"Exeter Business School"},
  {c:"fin",l:"std",g:"AAA"},
  {c:"psych",l:"std",g:"AAA"},
  {c:"hist",l:"high",g:"AAA-AAB"}
]},

{id:"bath",n:"巴斯大学",e:"University of Bath",c:"Bath",r:148,cat:"other",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:21,w:21,s:21,l:21}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:24,w:24,s:24,l:24}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 22,000-29,000",currency:"GBP"},
 living:"GBP 10,000-13,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["Bath International Scholarship","Chancellor's Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA",note:"IB 36"},
  {c:"eng",l:"std",g:"A*AA",note:"Strong placement year options"},
  {c:"math",l:"std",g:"A*AA"},
  {c:"phys",l:"std",g:"A*AA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA"},
  {c:"bus",l:"high",g:"A*AA",note:"School of Management top ranked"},
  {c:"acct",l:"high",g:"A*AA",note:"Accounting & Finance BSc"},
  {c:"psych",l:"std",g:"AAA"},
  {c:"arch",l:"std",g:"AAA",note:"Architecture BSc"}
]},

{id:"york",n:"约克大学",e:"University of York",c:"York",r:141,cat:"russell",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:96,r:22,w:22,s:23,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 21,950-28,800",currency:"GBP"},
 living:"GBP 9,500-12,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["York Global Merit Scholarship","Vice-Chancellor's Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"A*AA"},
  {c:"eng",l:"std",g:"AAA-AAB"},
  {c:"math",l:"std",g:"A*AA"},
  {c:"phys",l:"std",g:"AAA"},
  {c:"chem",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"law",l:"high",g:"AAA"},
  {c:"econ",l:"std",g:"AAA"},
  {c:"psych",l:"std",g:"AAA",note:"Top ranked psychology"},
  {c:"edu",l:"std",g:"ABB-BBB"},
  {c:"hist",l:"high",g:"AAA"},
  {c:"media",l:"high",g:"AAA-AAB"}
]},

{id:"lancaster",n:"兰卡斯特大学",e:"Lancaster University",c:"Lancaster",r:122,cat:"other",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:87,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6,w:6,s:6,l:6},toefl:{t:93,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"GBP 21,500-28,000",currency:"GBP"},
 living:"GBP 9,500-12,000/yr",
 visa:{psw:"2yr",note:"Graduate Route visa"},
 ddl:{fall:"Jan 25 (UCAS)"},
 schol:["Lancaster Global Scholarship","LUMS Scholarship"],
 materials:["UCAS","PS","Transcript"],
 p:[
  {c:"cs",l:"std",g:"AAA"},
  {c:"eng",l:"std",g:"AAA-AAB"},
  {c:"math",l:"std",g:"AAA"},
  {c:"phys",l:"std",g:"AAA-AAB"},
  {c:"bio",l:"std",g:"AAA-AAB"},
  {c:"env",l:"std",g:"AAA-ABB"},
  {c:"law",l:"high",g:"AAA"},
  {c:"econ",l:"std",g:"AAA"},
  {c:"bus",l:"std",g:"AAA",note:"LUMS top ranked"},
  {c:"fin",l:"std",g:"AAA",note:"Lancaster Management School"},
  {c:"psych",l:"std",g:"AAA"},
  {c:"ling",l:"std",g:"AAA-AAB"}
]},

// ============ RUSSELL GROUP OTHER ============
{id:"newcastle",n:"纽卡斯尔大学",e:"Newcastle University",c:"Newcastle",r:110,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"A*AA"},{c:"eng",l:"std",g:"AAA"},{c:"math",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},{c:"med",l:"high",g:"A*AA",note:"UCAT required"},
  {c:"arch",l:"std",g:"AAA"},{c:"law",l:"high",g:"AAA"},
  {c:"bus",l:"std",g:"AAA-AAB"},{c:"psych",l:"std",g:"AAA"}
]},

{id:"liverpool",n:"利物浦大学",e:"University of Liverpool",c:"Liverpool",r:150,cat:"russell",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:95,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"AAA-AAB"},{c:"eng",l:"std",g:"AAA-AAB"},{c:"math",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},{c:"med",l:"high",g:"AAA",note:"UCAT required"},
  {c:"dent",l:"high",g:"AAA"},{c:"vet",l:"high",g:"AAA"},
  {c:"arch",l:"std",g:"AAA-AAB"},{c:"law",l:"high",g:"AAA"},
  {c:"bus",l:"std",g:"AAA-AAB"}
]},

{id:"qmul",n:"伦敦玛丽女王",e:"Queen Mary University of London",c:"London",r:125,cat:"russell",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"A*AA"},{c:"eng",l:"std",g:"AAA"},{c:"math",l:"std",g:"A*AA"},
  {c:"bio",l:"std",g:"AAA-AAB"},{c:"med",l:"high",g:"A*AA",note:"UCAT required"},
  {c:"dent",l:"high",g:"AAA"},{c:"law",l:"high",g:"AAA",note:"Top ranked law school"},
  {c:"econ",l:"std",g:"AAA"},{c:"ling",l:"std",g:"AAA-AAB"},
  {c:"hist",l:"high",g:"AAA-AAB"}
]},

{id:"cardiff",n:"卡迪夫大学",e:"Cardiff University",c:"Cardiff",r:154,cat:"russell",
 ll:{std:{ielts:{t:6.5,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:90,r:17,w:17,s:20,l:17}},
     high:{ielts:{t:7.0,r:6,w:6,s:6,l:6},toefl:{t:100,r:20,w:20,s:22,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"AAA-AAB"},{c:"eng",l:"std",g:"AAA-AAB"},{c:"math",l:"std",g:"AAA"},
  {c:"bio",l:"std",g:"AAA-AAB"},{c:"med",l:"high",g:"AAA",note:"UCAT required"},
  {c:"dent",l:"high",g:"AAA"},{c:"arch",l:"std",g:"AAA-AAB"},
  {c:"law",l:"high",g:"AAA"},{c:"bus",l:"std",g:"AAA-AAB"},
  {c:"media",l:"high",g:"AAA",note:"School of Journalism top ranked"},
  {c:"psych",l:"std",g:"AAA"}
]},

{id:"qub",n:"贝尔法斯特女王大学",e:"Queen's University Belfast",c:"Belfast",r:195,cat:"russell",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:17,w:17,s:20,l:17}},
     high:{ielts:{t:7.0,r:6,w:6,s:6,l:6},toefl:{t:95,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"AAA-AAB"},{c:"eng",l:"std",g:"AAA-ABB"},{c:"math",l:"std",g:"AAA-AAB"},
  {c:"bio",l:"std",g:"AAA-AAB"},{c:"med",l:"high",g:"A*AA",note:"UCAT required"},
  {c:"law",l:"high",g:"AAA"},{c:"pharm",l:"std",g:"AAB-ABB"},
  {c:"econ",l:"std",g:"AAA-AAB"},{c:"psych",l:"std",g:"AAA-AAB"}
]},

// ============ OTHER RANKED ============
{id:"loughborough",n:"拉夫堡大学",e:"Loughborough University",c:"Loughborough",r:212,cat:"other",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:92,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"AAA-AAB"},{c:"eng",l:"std",g:"AAA-AAB"},
  {c:"bus",l:"std",g:"AAA-AAB"},{c:"ds",l:"std",g:"AAA-AAB"},
  {c:"art",l:"std",g:"ABB-BBB",note:"Top for design & sport science"}
]},

{id:"surrey",n:"萨里大学",e:"University of Surrey",c:"Guildford",r:230,cat:"other",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:88,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"AAA-AAB"},{c:"eng",l:"std",g:"AAA-ABB"},
  {c:"bus",l:"std",g:"AAA-ABB"},{c:"vet",l:"std",g:"AAA",note:"School of Veterinary Medicine"},
  {c:"bio",l:"std",g:"AAA-AAB"}
]},

{id:"sussex",n:"萨塞克斯大学",e:"University of Sussex",c:"Brighton",r:218,cat:"other",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:88,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"AAA-AAB"},{c:"ai",l:"std",g:"AAA-AAB"},
  {c:"ir",l:"std",g:"AAA-AAB",note:"Top for development studies"},
  {c:"media",l:"std",g:"AAA-ABB"},{c:"psych",l:"std",g:"AAA"},
  {c:"edu",l:"std",g:"ABB-BBB"},{c:"econ",l:"std",g:"AAA-AAB"}
]},

{id:"soas",n:"伦敦大学亚非学院",e:"SOAS University of London",c:"London",r:340,cat:"other",
 ll:{std:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:92,r:22,w:22,s:22,l:22}},
     high:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:24,w:24,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"law",l:"high",g:"AAA",note:"LLB with specialisms"},{c:"ir",l:"high",g:"AAA-AAB"},
  {c:"econ",l:"std",g:"AAA-AAB"},{c:"ling",l:"std",g:"AAA-ABB"},
  {c:"hist",l:"high",g:"AAA-AAB"},{c:"soc",l:"std",g:"AAA-ABB",note:"Area studies focus"}
]},

{id:"city",n:"伦敦城市大学",e:"City, University of London",c:"London",r:320,cat:"other",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}},
     cass:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:89,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"AAA-ABB"},{c:"eng",l:"std",g:"AAA-ABB"},
  {c:"bus",l:"cass",g:"AAA",note:"Bayes Business School"},
  {c:"fin",l:"cass",g:"A*AA",note:"Bayes; top ranked finance BSc"},
  {c:"acct",l:"cass",g:"AAA"},{c:"law",l:"std",g:"AAA-AAB"},
  {c:"media",l:"std",g:"AAA-ABB",note:"Journalism & publishing"}
]},

{id:"ual",n:"伦敦艺术大学",e:"University of the Arts London",c:"London",r:null,cat:"other",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}}},
 pol:{nt:"accepted",mb:false,v:"2y"},
 p:[
  {c:"art",l:"std",g:"Portfolio",note:"CSM/LCF/LCC - world leading art & design; portfolio essential"},
  {c:"media",l:"std",g:"Portfolio",note:"Communication & media design"},
  {c:"arch",l:"std",g:"Portfolio",note:"Architecture & spatial design"}
]},

{id:"coventry",n:"考文垂大学",e:"Coventry University",c:"Coventry",r:380,cat:"other",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:79,r:18,w:18,s:20,l:17}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"BBB-BCC"},{c:"eng",l:"std",g:"BBB-BCC"},
  {c:"bus",l:"std",g:"BBB-BCC"},{c:"art",l:"std",g:"BCC-CCC",note:"Portfolio based"},
  {c:"media",l:"std",g:"BBB-BCC"}
]},

{id:"westminster",n:"威斯敏斯特大学",e:"University of Westminster",c:"London",r:400,cat:"other",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:80,r:18,w:18,s:20,l:17}}},
 pol:{nt:"accepted",mb:false,v:"2y"},
 p:[
  {c:"cs",l:"std",g:"BBB-BCC"},{c:"bus",l:"std",g:"BBB-BCC"},
  {c:"media",l:"std",g:"BBB-BCC",note:"Top for media & communications"},
  {c:"arch",l:"std",g:"BBB"},{c:"art",l:"std",g:"BCC"}
]}
];
COMPASS_DATA.uk = D;
})();
