// data-ca.js - Canadian Universities - Undergraduate Programs Only
// v4.0 - All programs are bachelor's level
(function(){
var D = [
// ============ U15 TOP TIER ============
{id:"uoft",n:"多伦多大学",e:"University of Toronto",c:"Toronto, ON",r:21,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:89,r:21,w:22,s:22,l:21}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:21,
 fee:{ug:"CAD 60,000-65,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 18,000-22,000/yr",
 ddl:{fall:"Jan 15 (OUAC)"},
 schol:["Lester B. Pearson Scholarship (full ride)","President's Scholars of Excellence","UofT Scholars Program"],
 materials:["OUAC application","Transcripts","Supplementary application","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 90s",note:"Arts & Science or Engineering stream; highly competitive"},
  {c:"eng",l:"def",g:"mid-to-high 90s",note:"Faculty of Applied Science & Engineering"},
  {c:"ee",l:"def",g:"low-to-mid 90s",note:"Electrical & Computer Engineering"},
  {c:"math",l:"def",g:"low-to-mid 90s"},
  {c:"phys",l:"def",g:"low-to-mid 90s"},
  {c:"chem",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s",note:"Life Sciences"},
  {c:"econ",l:"def",g:"low-to-mid 90s",note:"Economics / Commerce"},
  {c:"bus",l:"def",g:"low-to-mid 90s",note:"Rotman Commerce"},
  {c:"law",l:"def",g:"mid-to-high 80s",note:"No direct UG law; pre-law tracks available"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"med",l:"def",g:"low-to-mid 90s",note:"Life Science pre-med track; MD is post-grad"},
  {c:"arch",l:"def",g:"mid-to-high 80s",note:"Daniels Faculty; portfolio"},
  {c:"ds",l:"def",g:"low-to-mid 90s",note:"Data Science specialist"}
]},

{id:"ubc",n:"英属哥伦比亚大学",e:"University of British Columbia",c:"Vancouver, BC",r:34,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:22,w:21,s:21,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:45,
 fee:{ug:"CAD 49,000-60,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 18,000-22,000/yr",
 ddl:{fall:"Jan 15"},
 schol:["International Major Entrance Scholarship (up to full tuition)","Outstanding International Student Award","Karen McKellin International Leader of Tomorrow"],
 materials:["UBC application","Transcripts","Personal profile","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 90s",note:"BSc Computer Science; highly competitive"},
  {c:"eng",l:"def",g:"mid-to-high 90s",note:"Applied Science BASc"},
  {c:"math",l:"def",g:"low-to-mid 90s"},
  {c:"phys",l:"def",g:"low-to-mid 90s"},
  {c:"chem",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s"},
  {c:"econ",l:"def",g:"mid-to-high 80s",note:"Vancouver School of Economics"},
  {c:"bus",l:"def",g:"low-to-mid 90s",note:"Sauder School of Business BCom"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"media",l:"def",g:"mid-to-high 80s",note:"Journalism / Media Studies"},
  {c:"env",l:"def",g:"mid-to-high 80s",note:"Land & Food Systems / Environmental Sc."},
  {c:"arch",l:"def",g:"mid-to-high 80s",note:"SALA; portfolio may be required"}
]},

{id:"mcgill",n:"麦吉尔大学",e:"McGill University",c:"Montreal, QC",r:29,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:21,w:21,s:21,l:21}},
     high:{ielts:{t:7.0,r:6.5,w:7,s:6.5,l:6.5},toefl:{t:100,r:22,w:22,s:22,l:22}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:41,
 fee:{ug:"CAD 29,000-50,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP; Quebec CAQ required"},
 living:"CAD 15,000-20,000/yr",
 ddl:{fall:"Jan 15"},
 schol:["Entrance Scholarships (up to CAD 12,000)","One Planet Scholarship","Faculty-specific awards"],
 materials:["McGill application","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"low-to-mid 90s",note:"School of Computer Science BSc"},
  {c:"eng",l:"def",g:"low-to-mid 90s",note:"Faculty of Engineering BEng"},
  {c:"math",l:"def",g:"low-to-mid 90s"},
  {c:"phys",l:"def",g:"low-to-mid 90s"},
  {c:"chem",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"bus",l:"high",g:"low-to-mid 90s",note:"Desautels BCom; IELTS 7.0"},
  {c:"law",l:"high",g:"low-to-mid 90s",note:"Pre-law; BCL/LLB is post-grad"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"med",l:"def",g:"low-to-mid 90s",note:"Pre-med pathway; MDCM post-grad"},
  {c:"arch",l:"def",g:"mid-to-high 80s",note:"School of Architecture BSc(Arch)"}
]},

{id:"waterloo",n:"滑铁卢大学",e:"University of Waterloo",c:"Waterloo, ON",r:112,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6.5,l:6},toefl:{t:90,r:20,w:25,s:25,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:162,
 fee:{ug:"CAD 52,000-62,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 15,000-18,000/yr",
 ddl:{fall:"Feb 1 (OUAC)"},
 schol:["President's Scholarship of Distinction (CAD 10,000)","International Experience Award","Faculty-specific entrance awards"],
 materials:["OUAC application","AIF (Admission Information Form)","Transcripts","English proficiency","Euclid/CCC contest (optional)"],
 p:[
  {c:"cs",l:"def",g:"low-to-mid 90s",note:"Cheriton School of CS; co-op available; extremely competitive"},
  {c:"eng",l:"def",g:"low-to-mid 90s",note:"Software/Computer/Electrical Engineering; co-op"},
  {c:"ee",l:"def",g:"low-to-mid 90s"},
  {c:"me",l:"def",g:"low-to-mid 90s"},
  {c:"math",l:"def",g:"low-to-mid 90s",note:"Faculty of Mathematics; co-op"},
  {c:"stat",l:"def",g:"low-to-mid 90s",note:"Actuarial Science / Statistics"},
  {c:"phys",l:"def",g:"mid-to-high 80s"},
  {c:"bus",l:"def",g:"mid-to-high 80s",note:"AFM / FARM; math-heavy business"},
  {c:"acct",l:"def",g:"mid-to-high 80s",note:"School of Accounting & Finance"},
  {c:"ds",l:"def",g:"low-to-mid 90s",note:"Data Science within Math faculty"},
  {c:"env",l:"def",g:"mid-to-high 80s",note:"Faculty of Environment"}
]},

{id:"ualberta",n:"阿尔伯塔大学",e:"University of Alberta",c:"Edmonton, AB",r:96,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:21,w:21,s:21,l:21}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:119,
 fee:{ug:"CAD 33,000-42,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 14,000-18,000/yr",
 ddl:{fall:"Mar 1"},
 schol:["International Student Scholarship","President's Award of Distinction","Faculty-specific awards"],
 materials:["Alberta application","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s",note:"Computing Science BSc"},
  {c:"eng",l:"def",g:"mid-to-high 80s",note:"Faculty of Engineering BEng"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"phys",l:"def",g:"mid-to-high 80s"},
  {c:"chem",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"bus",l:"def",g:"mid-to-high 80s",note:"Alberta School of Business BCom"},
  {c:"edu",l:"def",g:"mid-to-high 80s",note:"Faculty of Education BEd"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"env",l:"def",g:"mid-to-high 80s"},
  {c:"nurs",l:"def",g:"mid-to-high 80s",note:"BScN Nursing"}
]},

{id:"mcmaster",n:"麦克马斯特大学",e:"McMaster University",c:"Hamilton, ON",r:152,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:86,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:116,
 fee:{ug:"CAD 38,000-52,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 14,000-18,000/yr",
 ddl:{fall:"Jan 15 (OUAC)"},
 schol:["Provost's Award","McMaster International Excellence Award","Faculty awards"],
 materials:["OUAC application","Supplementary application","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s",note:"Computing & Software BASc"},
  {c:"eng",l:"def",g:"low-to-mid 90s",note:"Engineering I (common first year)"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"phys",l:"def",g:"mid-to-high 80s"},
  {c:"chem",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s",note:"Life Sciences - Health Sciences stream"},
  {c:"bus",l:"def",g:"mid-to-high 80s",note:"DeGroote School BCom"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"nurs",l:"def",g:"low-to-mid 90s",note:"BScN"},
  {c:"med",l:"def",g:"low-to-mid 90s",note:"Health Sciences BHSc; pre-med; CARS test"}
]},

// ============ U15 MID TIER ============
{id:"western",n:"韦仕敦大学",e:"Western University",c:"London, ON",r:114,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:83,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:201,
 fee:{ug:"CAD 40,000-55,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 14,000-17,000/yr",
 ddl:{fall:"Jan 15 (OUAC)"},
 schol:["Western Scholarship of Excellence","International President's Entrance Scholarship","National Scholarship"],
 materials:["OUAC application","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s"},
  {c:"eng",l:"def",g:"mid-to-high 80s",note:"Faculty of Engineering BESc"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s",note:"Medical Sciences popular pre-med"},
  {c:"bus",l:"def",g:"low-to-mid 90s",note:"Ivey AEO / HBA; very competitive"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"media",l:"def",g:"mid-to-high 80s",note:"Media, Information & Technoculture"},
  {c:"nurs",l:"def",g:"mid-to-high 80s",note:"BScN"},
  {c:"med",l:"def",g:"low-to-mid 90s",note:"Medical Sciences pre-med track"}
]},

{id:"queens",n:"女王大学",e:"Queen's University",c:"Kingston, ON",r:176,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:88,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:251,
 fee:{ug:"CAD 45,000-55,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 13,000-17,000/yr",
 ddl:{fall:"Feb 1 (OUAC)"},
 schol:["Queen's International Scholarship","Chancellor's Scholarship","Principal's Scholarship"],
 materials:["OUAC application","Personal Statement of Experience","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s",note:"School of Computing BSc"},
  {c:"eng",l:"def",g:"mid-to-high 80s",note:"Smith Engineering BASc"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"phys",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s",note:"Life Sciences"},
  {c:"bus",l:"def",g:"low-to-mid 90s",note:"Smith School BCom; highly competitive"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"nurs",l:"def",g:"mid-to-high 80s",note:"BNSc"}
]},

{id:"uottawa",n:"渥太华大学",e:"University of Ottawa",c:"Ottawa, ON",r:203,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:86,r:20,w:22,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:187,
 fee:{ug:"CAD 35,000-50,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 14,000-18,000/yr",
 ddl:{fall:"Apr 1 (OUAC for Ontario; direct for others)"},
 schol:["International Admission Scholarship","Merit Scholarship","Chancellor's Scholarship"],
 materials:["Application","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s",note:"School of EECS; bilingual campus"},
  {c:"eng",l:"def",g:"mid-to-high 80s",note:"Faculty of Engineering"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s"},
  {c:"bus",l:"def",g:"mid-to-high 80s",note:"Telfer School BCom"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"law",l:"def",g:"mid-to-high 80s",note:"Pre-law; Civil & Common Law Faculty (post-grad)"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"edu",l:"def",g:"mid-to-high 80s",note:"Faculty of Education"},
  {c:"nurs",l:"def",g:"mid-to-high 80s",note:"BScN"}
]},

{id:"dalhousie",n:"达尔豪斯大学",e:"Dalhousie University",c:"Halifax, NS",r:298,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:301,
 fee:{ug:"CAD 25,000-38,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 13,000-17,000/yr",
 ddl:{fall:"Apr 1"},
 schol:["Entrance Scholarships (up to CAD 40,000)","International Impact Scholarship","Faculty awards"],
 materials:["Dalhousie application","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s",note:"Faculty of Computer Science"},
  {c:"eng",l:"def",g:"mid-to-high 80s"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s",note:"Ocean Sciences strong"},
  {c:"bus",l:"def",g:"mid-to-high 80s",note:"Rowe School BCom"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"env",l:"def",g:"mid-to-high 80s",note:"Marine & Environmental"},
  {c:"nurs",l:"def",g:"mid-to-high 80s",note:"BScN"}
]},

{id:"ucalgary",n:"卡尔加里大学",e:"University of Calgary",c:"Calgary, AB",r:175,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:86,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:201,
 fee:{ug:"CAD 28,000-40,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP based on program length"},
 living:"CAD 14,000-18,000/yr",
 ddl:{fall:"Mar 1"},
 schol:["International Entrance Scholarship","Chancellor's Club Scholarship","Faculty awards"],
 materials:["Calgary application","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s"},
  {c:"eng",l:"def",g:"mid-to-high 80s",note:"Schulich School of Engineering"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s"},
  {c:"bus",l:"def",g:"mid-to-high 80s",note:"Haskayne BCom"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"edu",l:"def",g:"mid-to-high 80s",note:"Werklund School BEd"},
  {c:"nurs",l:"def",g:"mid-to-high 80s",note:"BN"},
  {c:"env",l:"def",g:"mid-to-high 80s"}
]},

{id:"umontreal",n:"蒙特利尔大学",e:"Universite de Montreal",c:"Montreal, QC",r:141,cat:"u15",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:21,w:21,s:21,l:21}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:150,
 fee:{ug:"CAD 25,000-35,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP; Quebec CAQ required"},
 living:"CAD 14,000-18,000/yr",
 ddl:{fall:"Feb 1"},
 schol:["Bursaries for international students","Faculty excellence scholarships"],
 materials:["UdeM application","Transcripts","French & English proficiency"],
 p:[
  {c:"cs",l:"def",g:"R-score 28+",note:"DIRO; most programs in French; Mila AI lab affiliated"},
  {c:"eng",l:"def",g:"R-score 28+",note:"Polytechnique Montreal affiliated"},
  {c:"math",l:"def",g:"R-score 28+"},
  {c:"bio",l:"def",g:"R-score 26+"},
  {c:"econ",l:"def",g:"R-score 26+"},
  {c:"bus",l:"def",g:"R-score 28+",note:"HEC Montreal (affiliated); some English options"},
  {c:"law",l:"def",g:"R-score 30+",note:"Faculty of Law; French required"},
  {c:"psych",l:"def",g:"R-score 26+"},
  {c:"med",l:"def",g:"R-score 34+",note:"French required; MD post-grad"},
  {c:"edu",l:"def",g:"R-score 26+"}
]},

// ============ OTHER NOTABLE ============
{id:"sfu",n:"西蒙菲莎大学",e:"Simon Fraser University",c:"Burnaby, BC",r:328,cat:"other",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:88,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:251,
 fee:{ug:"CAD 32,000-38,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP"},
 living:"CAD 17,000-22,000/yr",
 ddl:{fall:"Jan 31"},
 schol:["SFU Open Scholarship","International Transfer Student Scholarship","Provost Entrance Award"],
 materials:["SFU application","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s",note:"School of Computing Science BSc"},
  {c:"eng",l:"def",g:"mid-to-high 80s",note:"Mechatronic Systems / Engineering Science"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s"},
  {c:"bus",l:"def",g:"mid-to-high 80s",note:"Beedie BBA"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"media",l:"def",g:"mid-to-high 80s",note:"School of Communication"},
  {c:"ds",l:"def",g:"mid-to-high 80s",note:"Data Science minor/stream"}
]},

{id:"uvic",n:"维多利亚大学",e:"University of Victoria",c:"Victoria, BC",r:322,cat:"other",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:90,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:301,
 fee:{ug:"CAD 28,000-36,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP"},
 living:"CAD 16,000-20,000/yr",
 ddl:{fall:"Feb 28"},
 schol:["UVic International Entrance Scholarship","Faculty-specific awards"],
 materials:["UVic application","Transcripts","English proficiency"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s",note:"Co-op available"},
  {c:"eng",l:"def",g:"mid-to-high 80s",note:"Software/Computer/Electrical/Mechanical"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s"},
  {c:"bus",l:"def",g:"mid-to-high 80s",note:"Gustavson BCom"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"env",l:"def",g:"mid-to-high 80s",note:"Environmental Studies"}
]},

{id:"york_ca",n:"约克大学(加拿大)",e:"York University",c:"Toronto, ON",r:353,cat:"other",
 ll:{def:{ielts:{t:6.5,r:6,w:6,s:6,l:6},toefl:{t:88,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 the:401,
 fee:{ug:"CAD 30,000-40,000",currency:"CAD"},
 visa:{psw:"1-3yr",note:"PGWP"},
 living:"CAD 16,000-20,000/yr",
 ddl:{fall:"Feb 1 (OUAC)"},
 schol:["International Entrance Scholarship of Distinction","Global Leader of Tomorrow Award"],
 materials:["OUAC application","Transcripts","English proficiency","Supplementary (Schulich)"],
 p:[
  {c:"cs",l:"def",g:"mid-to-high 80s",note:"Lassonde School BSc"},
  {c:"eng",l:"def",g:"mid-to-high 80s",note:"Lassonde BEng"},
  {c:"math",l:"def",g:"mid-to-high 80s"},
  {c:"bio",l:"def",g:"mid-to-high 80s"},
  {c:"bus",l:"def",g:"low-to-mid 90s",note:"Schulich BBA; globally ranked"},
  {c:"econ",l:"def",g:"mid-to-high 80s"},
  {c:"psych",l:"def",g:"mid-to-high 80s"},
  {c:"law",l:"def",g:"mid-to-high 80s",note:"Pre-law; Osgoode Hall is post-grad"},
  {c:"edu",l:"def",g:"mid-to-high 80s",note:"BEd concurrent"},
  {c:"media",l:"def",g:"mid-to-high 80s",note:"Film / Communication Studies"}
]}
];
COMPASS_DATA.ca = D;
})();
