// data-us.js - US Universities Undergraduate Programs (50+)
// All data: undergraduate only. Language reqs, entry grades, programs offered.
(function(){
var D = [
// ============ IVY LEAGUE ============
{id:"harvard",n:"哈佛大学",e:"Harvard University",c:"Cambridge, MA",r:4,cat:"ivy",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y",note:"建议提交但大多数申请者无需英语考试 / Recommends but does not require English tests for most applicants"},
 fee:{ug:"$59,076/yr",currency:"USD"},living:"$22,000-25,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1学生签证 / F-1 student visa"},
 ddl:{fall:"Jan 1 (RD), Nov 1 (REA)",note:"对国际生需求无关录取 / Need-blind for internationals"},
 schol:[{name:"Harvard Financial Aid",note:"100%经济需求满足；平均助学金$59k+ / 100% demonstrated need met; avg grant $59k+"}],
 materials:["Common App","Essay","RL x2","Transcript","SAT/ACT optional","Interview"],
 p:[
  {c:"cs",l:"std",g:"SAT 1500+ / ACT 34+",note:"John A. Paulson工程学院 / John A. Paulson School of Engineering"},
  {c:"econ",l:"std",g:"SAT 1500+ / ACT 34+",note:"最热门专业方向 / Most popular concentration"},
  {c:"bio",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"math",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"phys",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"psych",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"hist",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"eng",l:"std",g:"SAT 1500+ / ACT 34+",note:"应用数学与工程科学 / Applied Mathematics & Engineering Sciences"},
  {c:"ir",l:"std",g:"SAT 1500+ / ACT 34+",note:"政府学方向 / Government concentration"},
  {c:"phil",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"soc",l:"std",g:"SAT 1500+ / ACT 34+",note:"社会学系 / Sociology department"},
  {c:"env",l:"std",g:"SAT 1500+ / ACT 34+",note:"环境科学与工程 / Environmental Science & Engineering"}
]},

{id:"mit",n:"MIT",e:"Massachusetts Institute of Technology",c:"Cambridge, MA",r:1,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:90,r:null,w:null,s:null,l:null}},
     rec:{ielts:{t:7.5,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y",note:"TOEFL最低90分，建议100+ / TOEFL 90 minimum, 100+ recommended"},
 fee:{ug:"$61,990/yr",currency:"USD"},living:"$22,000-24,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1学生签证 / F-1 student visa"},
 ddl:{fall:"Jan 1 (RD), Nov 1 (EA)",note:"对国际生需求无关录取 / Need-blind for internationals"},
 schol:[{name:"MIT Financial Aid",note:"100%经济需求满足；约60%学生获得资助 / 100% demonstrated need met; ~60% receive aid"}],
 materials:["MIT Application","Essays x5","RL x2","Transcript","SAT/ACT optional","Interview"],
 p:[
  {c:"cs",l:"rec",g:"SAT 1520+ / ACT 35+",note:"6号课程-电气工程与计算机科学(EECS)；最热门专业 / Course 6 - EECS; most popular major"},
  {c:"ee",l:"rec",g:"SAT 1520+ / ACT 35+",note:"6-1/6-2号课程-电气工程与计算机科学 / Course 6-1/6-2 - EE & CS"},
  {c:"me",l:"rec",g:"SAT 1520+ / ACT 35+",note:"2号课程-机械工程 / Course 2 - Mechanical Engineering"},
  {c:"ce",l:"std",g:"SAT 1520+ / ACT 35+",note:"1号课程-土木与环境工程 / Course 1 - Civil & Environmental Engineering"},
  {c:"math",l:"rec",g:"SAT 1520+ / ACT 35+",note:"18号课程-数学 / Course 18 - Mathematics"},
  {c:"phys",l:"rec",g:"SAT 1520+ / ACT 35+",note:"8号课程-物理学 / Course 8 - Physics"},
  {c:"chem",l:"std",g:"SAT 1520+ / ACT 35+",note:"5号课程-化学 / Course 5 - Chemistry"},
  {c:"bio",l:"std",g:"SAT 1520+ / ACT 35+",note:"7号课程-生物学 / Course 7 - Biology"},
  {c:"econ",l:"std",g:"SAT 1520+ / ACT 35+",note:"14号课程-经济学 / Course 14 - Economics"},
  {c:"arch",l:"std",g:"SAT 1520+ / ACT 35+",note:"4号课程-建筑学；建议提交作品集 / Course 4 - Architecture; portfolio recommended"},
  {c:"ds",l:"rec",g:"SAT 1520+ / ACT 35+",note:"跨学科数据科学 / Interdisciplinary Data Science"},
  {c:"ai",l:"rec",g:"SAT 1520+ / ACT 35+",note:"6-4号课程-人工智能与决策 / Course 6-4 - AI & Decision Making"}
]},

{id:"stanford",n:"斯坦福大学",e:"Stanford University",c:"Stanford, CA",r:2,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:true,v:"2y",note:"需提供英语水平证明；未公布最低分要求 / English proficiency proof required; no minimum published"},
 fee:{ug:"$62,484/yr",currency:"USD"},living:"$22,000-26,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1学生签证 / F-1 student visa"},
 ddl:{fall:"Jan 2 (RD), Nov 1 (REA)",note:"对国际生需求无关录取 / Need-blind for internationals"},
 schol:[{name:"Stanford Financial Aid",note:"100%经济需求满足；无贷款；家庭收入低于$10万免学费 / 100% demonstrated need; no loans; family <$100k = free tuition"}],
 materials:["Common App/Coalition","Essays","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1500+ / ACT 34+",note:"斯坦福工程学院；录取率约4% / Stanford Engineering; acceptance rate ~4%"},
  {c:"eng",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"ee",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"econ",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"math",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"bio",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"phys",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"psych",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"ir",l:"std",g:"SAT 1500+ / ACT 34+",note:"国际关系 / International Relations"},
  {c:"ds",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"env",l:"std",g:"SAT 1500+ / ACT 34+",note:"地球系统 / Earth Systems"},
  {c:"media",l:"std",g:"SAT 1500+ / ACT 34+",note:"传播学 / Communication"}
]},

{id:"princeton",n:"普林斯顿大学",e:"Princeton University",c:"Princeton, NJ",r:12,cat:"ivy",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$59,710/yr",currency:"USD"},living:"$19,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 1 (RD), Nov 1 (SCEA)",note:"对国际生需求无关录取 / Need-blind for internationals"},
 schol:[{name:"Princeton Financial Aid",note:"100%需求满足；仅助学金无贷款；平均助学金约$60k / 100% need met; grants not loans; avg grant ~$60k"}],
 materials:["Common App","Essays","RL x2","Transcript","SAT/ACT required","Graded paper"],
 p:[
  {c:"cs",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"econ",l:"std",g:"SAT 1510+ / ACT 34+",note:"最热门专业 / Most popular major"},
  {c:"math",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"phys",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"eng",l:"std",g:"SAT 1510+ / ACT 34+",note:"BSE工程学位 / BSE Engineering"},
  {c:"ir",l:"std",g:"SAT 1510+ / ACT 34+",note:"政治学 / SPIA / Politics / SPIA"},
  {c:"hist",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"phil",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"chem",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"arch",l:"std",g:"SAT 1510+ / ACT 34+",note:"建筑与工程 / Architecture & Engineering"}
]},

{id:"yale",n:"耶鲁大学",e:"Yale University",c:"New Haven, CT",r:9,cat:"ivy",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$64,700/yr",currency:"USD"},living:"$19,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 2 (RD), Nov 1 (SCEA)",note:"对国际生需求无关录取 / Need-blind for internationals"},
 schol:[{name:"Yale Financial Aid",note:"100%需求满足；平均助学金约$62k / 100% need met; avg grant ~$62k"}],
 materials:["Common App/Coalition","Essays","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"econ",l:"std",g:"SAT 1500+ / ACT 34+",note:"最热门专业 / Most popular major"},
  {c:"bio",l:"std",g:"SAT 1500+ / ACT 34+",note:"分子生物物理与生物化学 / Molecular Biophysics & Biochemistry"},
  {c:"math",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"psych",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"hist",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"ir",l:"std",g:"SAT 1500+ / ACT 34+",note:"政治学 / 全球事务 / Political Science / Global Affairs"},
  {c:"art",l:"std",g:"SAT 1500+ / ACT 34+",note:"艺术；需提交作品集 / Art; portfolio required"},
  {c:"ling",l:"std",g:"SAT 1500+ / ACT 34+",note:"语言学系 / Linguistics Department"},
  {c:"env",l:"std",g:"SAT 1500+ / ACT 34+",note:"环境与可持续发展 / Environment & Sustainability"}
]},

{id:"columbia",n:"哥伦比亚大学",e:"Columbia University",c:"New York, NY",r:7,cat:"ivy",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$65,524/yr",currency:"USD"},living:"$20,000-28,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 1 (RD), Nov 1 (ED)",note:""},
 schol:[{name:"Columbia Financial Aid",note:"100%需求满足；对所有人需求无关录取 / 100% need met; need-blind for all"}],
 materials:["Common App/Coalition","Essays","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1500+ / ACT 34+",note:"傅氏工程学院 / Fu Foundation School of Engineering"},
  {c:"econ",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"eng",l:"std",g:"SAT 1500+ / ACT 34+",note:"SEAS - 应用物理、生物医学工程等 / SEAS - Applied Physics, BME, etc."},
  {c:"bio",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"math",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"ir",l:"std",g:"SAT 1500+ / ACT 34+",note:"政治学 / SIPA方向 / Political Science / SIPA track"},
  {c:"hist",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"psych",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"arch",l:"std",g:"SAT 1500+ / ACT 34+",note:"GSAPP - 建筑学 / GSAPP - Architecture"},
  {c:"media",l:"std",g:"SAT 1500+ / ACT 34+",note:"新闻学（巴纳德） / Journalism (Barnard)"}
]},

{id:"upenn",n:"宾夕法尼亚大学",e:"University of Pennsylvania",c:"Philadelphia, PA",r:11,cat:"ivy",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:25,s:25,l:25}},
     wharton:{ielts:{t:7.5,r:null,w:null,s:null,l:null},toefl:{t:105,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$63,452/yr",currency:"USD"},living:"$18,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 5 (RD), Nov 1 (ED)",note:""},
 schol:[{name:"UPenn Grant",note:"100%需求满足；对国际生需求有关录取 / 100% need met; need-aware for internationals"}],
 materials:["Common App","Essays","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"bus",l:"wharton",g:"SAT 1500+ / ACT 34+",note:"沃顿商学院 - 经济学理学士 / Wharton School - BS in Economics"},
  {c:"fin",l:"wharton",g:"SAT 1500+ / ACT 34+",note:"沃顿金融方向 / Wharton Finance concentration"},
  {c:"cs",l:"std",g:"SAT 1500+ / ACT 34+",note:"工程学院 / School of Engineering"},
  {c:"eng",l:"std",g:"SAT 1500+ / ACT 34+",note:"SEAS - 生物工程、系统工程等 / SEAS - Bioengineering, Systems, etc."},
  {c:"econ",l:"std",g:"SAT 1500+ / ACT 34+",note:"文理学院 / College of Arts & Sciences"},
  {c:"bio",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"nurs",l:"std",g:"SAT 1480+ / ACT 33+",note:"宾大护理学院 - 顶级排名 / Penn Nursing - top ranked"},
  {c:"ir",l:"std",g:"SAT 1500+ / ACT 34+",note:"政治学 / Political Science"},
  {c:"psych",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"arch",l:"std",g:"SAT 1500+ / ACT 34+",note:"Stuart Weitzman设计学院 / Stuart Weitzman School of Design"}
]},

{id:"cornell",n:"康奈尔大学",e:"Cornell University",c:"Ithaca, NY",r:16,cat:"ivy",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$63,200/yr",currency:"USD"},living:"$17,000-21,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 2 (RD), Nov 1 (ED)",note:""},
 schol:[{name:"Cornell Financial Aid",note:"对国际生需求有关录取；慷慨助学金 / Need-aware for internationals; generous aid"}],
 materials:["Common App","School-specific supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1480+ / ACT 34+",note:"工程学院或文理学院 / College of Engineering or Arts & Sciences"},
  {c:"eng",l:"std",g:"SAT 1480+ / ACT 34+",note:"7所学院：工程、农业、ILR等 / 7 schools: Engineering, Agriculture, ILR, etc."},
  {c:"ee",l:"std",g:"SAT 1480+ / ACT 34+",note:"ECE系 / ECE"},
  {c:"bus",l:"std",g:"SAT 1480+ / ACT 34+",note:"SC Johnson商学院下的Dyson学院 / Dyson School in SC Johnson"},
  {c:"bio",l:"std",g:"SAT 1480+ / ACT 34+",note:"农业与生命科学学院 / CALS"},
  {c:"econ",l:"std",g:"SAT 1480+ / ACT 34+"},
  {c:"arch",l:"std",g:"SAT 1460+ / ACT 33+",note:"AAP；5年制建筑学学士；需提交作品集 / AAP; 5-year B.Arch; portfolio required"},
  {c:"env",l:"std",g:"SAT 1460+ / ACT 33+",note:"农业与生命科学学院 - 环境工程 / CALS - Environmental Engineering"},
  {c:"psych",l:"std",g:"SAT 1480+ / ACT 34+"},
  {c:"vet",l:"std",g:"SAT 1480+ / ACT 34+",note:"兽医预科；兽医学院全国顶尖 / Pre-vet track; Vet college is top ranked"}
]},

{id:"brown",n:"布朗大学",e:"Brown University",c:"Providence, RI",r:63,cat:"ivy",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$65,146/yr",currency:"USD"},living:"$18,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 5 (RD), Nov 1 (ED)",note:"国内需求无关录取；国际生需求有关录取 / Need-blind domestically; need-aware intl"},
 schol:[{name:"Brown Financial Aid",note:"需求为基础；满足100%经济需求 / Need-based; meets 100% demonstrated need"}],
 materials:["Common App","Essays","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1480+ / ACT 34+"},
  {c:"econ",l:"std",g:"SAT 1480+ / ACT 34+"},
  {c:"bio",l:"std",g:"SAT 1480+ / ACT 34+"},
  {c:"math",l:"std",g:"SAT 1480+ / ACT 34+",note:"应用数学热门 / Applied Math popular"},
  {c:"eng",l:"std",g:"SAT 1480+ / ACT 34+"},
  {c:"ir",l:"std",g:"SAT 1480+ / ACT 34+",note:"国际与公共事务 / International & Public Affairs"},
  {c:"psych",l:"std",g:"SAT 1480+ / ACT 34+",note:"可选认知科学方向 / Cognitive Science track available"},
  {c:"hist",l:"std",g:"SAT 1480+ / ACT 34+"},
  {c:"med",l:"std",g:"SAT 1500+ / ACT 34+",note:"PLME 8年制本硕连读；竞争极为激烈 / PLME 8-year BS/MD; extremely selective"}
]},

{id:"dartmouth",n:"达特茅斯学院",e:"Dartmouth College",c:"Hanover, NH",r:237,cat:"ivy",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$62,658/yr",currency:"USD"},living:"$18,000-21,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 2 (RD), Nov 1 (ED)",note:"对国际生需求无关录取 / Need-blind for internationals"},
 schol:[{name:"Dartmouth Financial Aid",note:"100%需求满足；对所有人需求无关录取 / 100% need met; need-blind for all"}],
 materials:["Common App","Dartmouth writing supplement","RL x2","Transcript","SAT/ACT required","Peer eval"],
 p:[
  {c:"cs",l:"std",g:"SAT 1480+ / ACT 33+"},
  {c:"econ",l:"std",g:"SAT 1480+ / ACT 33+",note:"经济学 - 最热门专业 / Economics - most popular"},
  {c:"eng",l:"std",g:"SAT 1480+ / ACT 33+",note:"Thayer工程学院 / Thayer School of Engineering"},
  {c:"math",l:"std",g:"SAT 1480+ / ACT 33+"},
  {c:"bio",l:"std",g:"SAT 1480+ / ACT 33+"},
  {c:"hist",l:"std",g:"SAT 1480+ / ACT 33+"},
  {c:"ir",l:"std",g:"SAT 1480+ / ACT 33+",note:"政府学 / Government"},
  {c:"env",l:"std",g:"SAT 1480+ / ACT 33+",note:"环境研究 / Environmental Studies"}
]},

// ============ TOP PRIVATE ============
{id:"caltech",n:"加州理工",e:"California Institute of Technology",c:"Pasadena, CA",r:5,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$63,255/yr",currency:"USD"},living:"$20,000-23,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 3 (RD), Nov 1 (REA)",note:"国内需求无关录取 / Need-blind domestically"},
 schol:[{name:"Caltech Financial Aid",note:"100%需求满足；平均助学金超$50k / 100% need met; avg grant >$50k"}],
 materials:["Common App/Coalition","Caltech essays","RL x2","Transcript","SAT/ACT required"],
 p:[
  {c:"cs",l:"std",g:"SAT 1530+ / ACT 35+"},
  {c:"ee",l:"std",g:"SAT 1530+ / ACT 35+"},
  {c:"me",l:"std",g:"SAT 1530+ / ACT 35+"},
  {c:"phys",l:"std",g:"SAT 1530+ / ACT 35+",note:"物理项目享誉全球 / Renowned physics program"},
  {c:"math",l:"std",g:"SAT 1530+ / ACT 35+"},
  {c:"chem",l:"std",g:"SAT 1530+ / ACT 35+"},
  {c:"bio",l:"std",g:"SAT 1530+ / ACT 35+"},
  {c:"env",l:"std",g:"SAT 1530+ / ACT 35+",note:"环境科学与工程 / Environmental Science & Engineering"}
]},

{id:"duke",n:"杜克大学",e:"Duke University",c:"Durham, NC",r:24,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$63,054/yr",currency:"USD"},living:"$18,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 4 (RD), Nov 1 (ED)",note:""},
 schol:[{name:"Duke Financial Aid",note:"国内需求无关录取；国际生需求有关录取；满足100%需求 / Need-blind domestically; need-aware intl; meets 100%"}],
 materials:["Common App","Duke supplement","RL x2","Transcript","SAT/ACT optional","Optional interview"],
 p:[
  {c:"cs",l:"std",g:"SAT 1500+ / ACT 34+",note:"Pratt工程学院或文理学院 / Pratt School of Engineering or Trinity"},
  {c:"econ",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"bus",l:"std",g:"SAT 1500+ / ACT 34+",note:"经济学+市场与管理证书 / Economics + Markets & Management certificate"},
  {c:"bio",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"eng",l:"std",g:"SAT 1500+ / ACT 34+",note:"Pratt工程学院 / Pratt School of Engineering"},
  {c:"psych",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"ir",l:"std",g:"SAT 1500+ / ACT 34+",note:"公共政策 / 政治学 / Public Policy / Political Science"},
  {c:"env",l:"std",g:"SAT 1500+ / ACT 34+",note:"Nicholas学院 - 环境科学 / Nicholas School - Environmental Sciences"},
  {c:"stat",l:"std",g:"SAT 1500+ / ACT 34+",note:"统计科学 / Statistical Science"},
  {c:"hist",l:"std",g:"SAT 1500+ / ACT 34+"}
]},

{id:"northwestern",n:"西北大学",e:"Northwestern University",c:"Evanston, IL",r:24,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$63,468/yr",currency:"USD"},living:"$19,000-23,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 3 (RD), Nov 1 (ED)",note:""},
 schol:[{name:"Northwestern Aid",note:"对国际生需求有关录取；满足100%经济需求 / Need-aware for intl; meets 100% demonstrated need"}],
 materials:["Common App/Coalition","NU supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1490+ / ACT 34+",note:"McCormick工程学院 / McCormick School of Engineering"},
  {c:"econ",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"media",l:"std",g:"SAT 1490+ / ACT 34+",note:"Medill新闻学院 - 顶级排名 / Medill School of Journalism - top ranked"},
  {c:"eng",l:"std",g:"SAT 1490+ / ACT 34+",note:"McCormick工程学院 / McCormick Engineering"},
  {c:"bus",l:"std",g:"SAT 1490+ / ACT 34+",note:"可选Kellogg证书路径 / Kellogg certificate pathway available"},
  {c:"psych",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"bio",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"art",l:"std",g:"SAT 1490+ / ACT 34+",note:"Bienen音乐学院 / 传播学 / Bienen School of Music / Communication Studies"},
  {c:"math",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"edu",l:"std",g:"SAT 1490+ / ACT 34+",note:"教育与社会政策学院 / School of Education & Social Policy"}
]},

{id:"uchicago",n:"芝加哥大学",e:"University of Chicago",c:"Chicago, IL",r:11,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$64,260/yr",currency:"USD"},living:"$20,000-24,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 2 (RD), Nov 1/2 (ED I/II)",note:""},
 schol:[{name:"UChicago Odyssey",note:"国内需求无关录取；慷慨奖学金+需求助学金 / Need-blind domestically; generous merit + need-based aid"}],
 materials:["Common App/Coalition/UChicago App","Extended essay","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"econ",l:"std",g:"SAT 1510+ / ACT 34+",note:"诺贝尔经济学奖摇篮；最强经济学项目 / Nobel laureates; strongest economics program"},
  {c:"cs",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"math",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"phys",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"bio",l:"std",g:"SAT 1510+ / ACT 34+",note:"生物科学；强医学预科 / Biological Sciences; strong pre-med"},
  {c:"ir",l:"std",g:"SAT 1510+ / ACT 34+",note:"政治学 / 公共政策 / Political Science / Public Policy"},
  {c:"phil",l:"std",g:"SAT 1510+ / ACT 34+",note:"顶级哲学系 / Top philosophy department"},
  {c:"stat",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"hist",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"soc",l:"std",g:"SAT 1510+ / ACT 34+"}
]},

{id:"jhu",n:"约翰斯·霍普金斯大学",e:"Johns Hopkins University",c:"Baltimore, MD",r:15,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:26,w:22,s:25,l:26}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$62,840/yr",currency:"USD"},living:"$18,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 2 (RD), Nov 1 (ED)",note:""},
 schol:[{name:"JHU Financial Aid",note:"对国际生需求有关录取；满足100%需求 / Need-aware intl; meets 100%"}],
 materials:["Common App","JHU supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"bio",l:"std",g:"SAT 1500+ / ACT 34+",note:"全美第一生物医学研究大学 / #1 biomedical research university"},
  {c:"cs",l:"std",g:"SAT 1500+ / ACT 34+",note:"Whiting工程学院 / Whiting School of Engineering"},
  {c:"eng",l:"std",g:"SAT 1500+ / ACT 34+",note:"生物医学工程全国顶尖 / BME top ranked nationally"},
  {c:"ph",l:"std",g:"SAT 1500+ / ACT 34+",note:"Bloomberg公共卫生学院路径 / Bloomberg School of Public Health pathway"},
  {c:"ir",l:"std",g:"SAT 1500+ / ACT 34+",note:"SAIS - 国际研究 / SAIS - International Studies"},
  {c:"econ",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"math",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"psych",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"media",l:"std",g:"SAT 1500+ / ACT 34+",note:"写作研讨班 / Writing Seminars"},
  {c:"nurs",l:"std",g:"SAT 1480+ / ACT 33+",note:"直录护理学士 / Direct-entry BSN"}
]},

{id:"rice",n:"莱斯大学",e:"Rice University",c:"Houston, TX",r:92,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$56,874/yr",currency:"USD"},living:"$16,000-20,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 4 (RD), Nov 1 (ED)",note:"国内需求无关录取 / Need-blind domestically"},
 schol:[{name:"Rice Financial Aid",note:"对国际生需求有关录取；Rice投资计划大幅降低学费 / Need-aware intl; Rice Investment reduces cost significantly"}],
 materials:["Common App/Coalition","Rice supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"eng",l:"std",g:"SAT 1490+ / ACT 34+",note:"George R. Brown工程学院 / George R. Brown School of Engineering"},
  {c:"bio",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"econ",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"arch",l:"std",g:"SAT 1480+ / ACT 33+",note:"顶级建筑学院；需提交作品集 / Top-ranked architecture; portfolio required"},
  {c:"math",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"phys",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"bus",l:"std",g:"SAT 1490+ / ACT 34+",note:"Jones商学院路径 / Jones Graduate School pathway"}
]},

{id:"vanderbilt",n:"范德堡大学",e:"Vanderbilt University",c:"Nashville, TN",r:155,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$62,194/yr",currency:"USD"},living:"$18,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 1 (RD), Nov 1 (ED I)",note:""},
 schol:[{name:"Vanderbilt Scholarship",note:"多项荣誉奖学金：Cornelius Vanderbilt、Ingram、Chancellor's / Multiple merit: Cornelius Vanderbilt, Ingram, Chancellor's"}],
 materials:["Common App/Coalition","Vandy supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1490+ / ACT 34+",note:"工程学院 / School of Engineering"},
  {c:"econ",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"edu",l:"std",g:"SAT 1480+ / ACT 33+",note:"Peabody学院 - 全国第一 / Peabody College - #1 ranked"},
  {c:"bio",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"eng",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"psych",l:"std",g:"SAT 1490+ / ACT 34+",note:"人类与组织发展 / Human & Organizational Development"},
  {c:"med",l:"std",g:"SAT 1500+ / ACT 34+",note:"医学预科；无直录MD项目 / Pre-med track; no direct-entry MD"},
  {c:"media",l:"std",g:"SAT 1490+ / ACT 34+",note:"传播学 / Communication Studies"}
]},

{id:"cmu",n:"卡内基梅隆大学",e:"Carnegie Mellon University",c:"Pittsburgh, PA",r:52,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:102,r:25,w:25,s:25,l:25}},
     scs:{ielts:{t:7.5,r:null,w:null,s:null,l:null},toefl:{t:102,r:25,w:25,s:25,l:25}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$62,260/yr",currency:"USD"},living:"$18,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 3 (RD), Nov 1 (ED)",note:""},
 schol:[{name:"CMU Presidential Scholarship",note:"以成绩为基础；顶尖申请者可获全额学费 / Merit-based; full tuition for top applicants"}],
 materials:["Common App/Coalition","CMU supplement","RL x2","Transcript","SAT/ACT required","Portfolio (design)"],
 p:[
  {c:"cs",l:"scs",g:"SAT 1530+ / ACT 35+",note:"计算机科学学院 - 全球第一 / School of Computer Science - #1 globally"},
  {c:"ai",l:"scs",g:"SAT 1530+ / ACT 35+",note:"人工智能学士（美国首创） / BS in Artificial Intelligence (first in US)"},
  {c:"ee",l:"std",g:"SAT 1500+ / ACT 34+",note:"ECE系 / ECE Department"},
  {c:"me",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"ds",l:"scs",g:"SAT 1520+ / ACT 34+",note:"统计与数据科学 / Statistics & Data Science"},
  {c:"bus",l:"std",g:"SAT 1500+ / ACT 34+",note:"Tepper商学院 / Tepper School of Business"},
  {c:"art",l:"std",g:"SAT 1460+ / ACT 33+",note:"设计学院；需提交作品集 / School of Design; portfolio required"},
  {c:"arch",l:"std",g:"SAT 1460+ / ACT 33+",note:"建筑学院；需提交作品集 / School of Architecture; portfolio required"},
  {c:"math",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"stat",l:"std",g:"SAT 1500+ / ACT 34+",note:"Dietrich学院 / Dietrich College"},
  {c:"psych",l:"std",g:"SAT 1480+ / ACT 33+"}
]},

{id:"georgetown",n:"乔治城大学",e:"Georgetown University",c:"Washington, DC",r:182,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$62,844/yr",currency:"USD"},living:"$20,000-24,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 10 (RD), Nov 1 (REA)",note:""},
 schol:[{name:"Georgetown Scholarship",note:"有限荣誉奖学金+国际生需求助学金 / Limited merit + need-based for intl students"}],
 materials:["Georgetown Application (own portal)","Essays","RL x2","Transcript","SAT/ACT required"],
 p:[
  {c:"ir",l:"std",g:"SAT 1460+ / ACT 33+",note:"Walsh外交学院 - 全球第一 / Walsh School of Foreign Service - #1 globally"},
  {c:"bus",l:"std",g:"SAT 1460+ / ACT 33+",note:"McDonough商学院 / McDonough School of Business"},
  {c:"fin",l:"std",g:"SAT 1460+ / ACT 33+",note:"McDonough金融方向 / McDonough Finance"},
  {c:"ir",l:"std",g:"SAT 1460+ / ACT 33+",note:"政府与政治学 / Government & Politics"},
  {c:"econ",l:"std",g:"SAT 1460+ / ACT 33+"},
  {c:"bio",l:"std",g:"SAT 1460+ / ACT 33+"},
  {c:"hist",l:"std",g:"SAT 1460+ / ACT 33+"},
  {c:"ling",l:"std",g:"SAT 1460+ / ACT 33+",note:"语言学系 / Linguistics Department"},
  {c:"nurs",l:"std",g:"SAT 1440+ / ACT 32+",note:"护理与健康研究学院 / School of Nursing & Health Studies"}
]},

{id:"washu",n:"华盛顿大学(圣路易斯)",e:"Washington University in St. Louis",c:"St. Louis, MO",r:100,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$62,782/yr",currency:"USD"},living:"$19,000-23,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 4 (RD), Nov 1 (ED)",note:""},
 schol:[{name:"WashU Financial Aid",note:"对国际生需求有关录取；慷慨荣誉奖学金 / Need-aware for intl; generous merit scholarships"}],
 materials:["Common App/Coalition","WashU supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1490+ / ACT 34+",note:"McKelvey工程学院 / McKelvey School of Engineering"},
  {c:"bus",l:"std",g:"SAT 1490+ / ACT 34+",note:"Olin商学院 - 顶级排名 / Olin Business School - top ranked"},
  {c:"fin",l:"std",g:"SAT 1490+ / ACT 34+",note:"Olin BSBA金融方向 / Olin BSBA Finance"},
  {c:"econ",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"bio",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"eng",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"psych",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"arch",l:"std",g:"SAT 1470+ / ACT 33+",note:"Sam Fox学院；需提交作品集 / Sam Fox School; portfolio required"},
  {c:"art",l:"std",g:"SAT 1470+ / ACT 33+",note:"Sam Fox设计与视觉艺术学院 / Sam Fox School of Design & Visual Arts"}
]},

// ============ TOP PUBLIC (UC系统 + 公立旗舰) ============
{id:"ucb",n:"加州大学伯克利",e:"UC Berkeley",c:"Berkeley, CA",r:10,cat:"public",
 ll:{std:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:80,r:null,w:null,s:null,l:null}},
     rec:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y",note:"最低80分，但竞争性录取通常100+ / Minimum 80, but competitive admits typically 100+"},
 fee:{ug:"$47,066/yr (OOS)",currency:"USD"},living:"$20,000-25,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Nov 30 (UC deadline)",note:"UC申请；无提前决定/提前行动 / UC Application; no ED/EA"},
 schol:[{name:"Berkeley International Scholarship",note:"有限；主要以成绩为基础；Regents奖学金 / Limited; mostly merit-based; Regents' Scholarship"}],
 materials:["UC Application","Personal insight questions x4","Transcript","SAT/ACT not considered"],
 p:[
  {c:"cs",l:"rec",g:"GPA 4.0+ (weighted)",note:"EECS（文理学院或工程学院）；录取率约5% / EECS (L&S or Engineering); acceptance rate ~5%"},
  {c:"eng",l:"rec",g:"GPA 4.0+ (weighted)",note:"工程学院 / College of Engineering"},
  {c:"ee",l:"rec",g:"GPA 4.0+ (weighted)"},
  {c:"ds",l:"rec",g:"GPA 4.0+ (weighted)",note:"数据科学专业 - 新兴热门 / Data Science major - new and popular"},
  {c:"econ",l:"std",g:"GPA 3.9+ (weighted)"},
  {c:"bus",l:"rec",g:"GPA 4.0+ (weighted)",note:"Haas商学院；竞争非常激烈 / Haas School of Business; very competitive"},
  {c:"bio",l:"std",g:"GPA 3.9+ (weighted)"},
  {c:"math",l:"std",g:"GPA 3.9+ (weighted)"},
  {c:"phys",l:"std",g:"GPA 3.9+ (weighted)"},
  {c:"env",l:"std",g:"GPA 3.9+ (weighted)",note:"自然资源学院 / College of Natural Resources"},
  {c:"arch",l:"std",g:"GPA 3.8+ (weighted)",note:"CED；本科不要求提交作品集 / CED; portfolio not required for UG"}
]},

{id:"ucla",n:"加州大学洛杉矶",e:"UCLA",c:"Los Angeles, CA",r:18,cat:"public",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$46,326/yr (OOS)",currency:"USD"},living:"$20,000-25,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Nov 30 (UC deadline)",note:"UC申请 / UC Application"},
 schol:[{name:"UCLA Regents Scholarship",note:"顶级荣誉奖学金；全额学费+生活补贴 / Top merit-based; full tuition + stipend"}],
 materials:["UC Application","Personal insight questions x4","Transcript"],
 p:[
  {c:"cs",l:"std",g:"GPA 4.0+ (weighted)",note:"Henry Samueli工程学院 / Henry Samueli School of Engineering"},
  {c:"eng",l:"std",g:"GPA 4.0+ (weighted)"},
  {c:"bio",l:"std",g:"GPA 3.9+ (weighted)",note:"生命科学系 / Life Sciences division"},
  {c:"econ",l:"std",g:"GPA 3.9+ (weighted)",note:"商业经济学非常热门 / Business Economics very popular"},
  {c:"psych",l:"std",g:"GPA 3.9+ (weighted)",note:"顶级心理学项目 / Top psychology program"},
  {c:"math",l:"std",g:"GPA 3.9+ (weighted)"},
  {c:"media",l:"std",g:"GPA 3.9+ (weighted)",note:"戏剧影视电视学院 / School of Theater, Film, Television"},
  {c:"art",l:"std",g:"GPA 3.8+ (weighted)",note:"艺术学院；需提交作品集 / School of the Arts; portfolio"},
  {c:"ir",l:"std",g:"GPA 3.9+ (weighted)",note:"政治学 / 国际发展 / Political Science / International Development"},
  {c:"nurs",l:"std",g:"GPA 3.9+ (weighted)",note:"护理学院；直录 / School of Nursing; direct admit"}
]},

{id:"umich",n:"密歇根大学",e:"University of Michigan",c:"Ann Arbor, MI",r:21,cat:"public",
 ll:{std:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:23,w:23,s:23,l:23}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$57,273/yr (OOS)",currency:"USD"},living:"$14,000-18,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Feb 1 (RD), Nov 1 (EA)",note:""},
 schol:[{name:"UMich Merit Scholarships",note:"国际生有限；密歇根差异奖 / Limited for intl; Michigan Difference Award"}],
 materials:["Common App","UMich supplement","RL x1","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1450+ / ACT 33+",note:"工程学院或LSA / College of Engineering or LSA"},
  {c:"eng",l:"std",g:"SAT 1450+ / ACT 33+",note:"顶级工程学院 / Top-ranked engineering school"},
  {c:"bus",l:"std",g:"SAT 1460+ / ACT 33+",note:"Ross商学院 - 优先录取 / Ross School of Business - preferred admission"},
  {c:"econ",l:"std",g:"SAT 1430+ / ACT 32+"},
  {c:"bio",l:"std",g:"SAT 1430+ / ACT 32+"},
  {c:"psych",l:"std",g:"SAT 1430+ / ACT 32+"},
  {c:"ds",l:"std",g:"SAT 1450+ / ACT 33+"},
  {c:"me",l:"std",g:"SAT 1450+ / ACT 33+"},
  {c:"math",l:"std",g:"SAT 1430+ / ACT 32+"},
  {c:"nurs",l:"std",g:"SAT 1400+ / ACT 31+",note:"护理学院 / School of Nursing"}
]},

{id:"usc",n:"南加州大学",e:"University of Southern California",c:"Los Angeles, CA",r:80,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$66,640/yr",currency:"USD"},living:"$20,000-24,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 15 (RD)",note:""},
 schol:[{name:"USC Trustee/Presidential Scholarship",note:"全额/半额学费荣誉奖学金 / Full/half tuition merit scholarships"}],
 materials:["Common App","USC supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1460+ / ACT 33+",note:"Viterbi工程学院 / Viterbi School of Engineering"},
  {c:"bus",l:"std",g:"SAT 1460+ / ACT 33+",note:"Marshall商学院 / Marshall School of Business"},
  {c:"media",l:"std",g:"SAT 1440+ / ACT 32+",note:"Annenberg传播学院 - 顶级排名 / Annenberg School of Communication - top ranked"},
  {c:"eng",l:"std",g:"SAT 1460+ / ACT 33+",note:"Viterbi工程学院 / Viterbi Engineering"},
  {c:"art",l:"std",g:"SAT 1400+ / ACT 31+",note:"电影艺术学院；需提交作品集/样片 / School of Cinematic Arts; portfolio/reel"},
  {c:"bio",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"arch",l:"std",g:"SAT 1440+ / ACT 32+",note:"建筑学院；需提交作品集 / School of Architecture; portfolio required"},
  {c:"econ",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"ir",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"psych",l:"std",g:"SAT 1440+ / ACT 32+"}
]},

{id:"nyu",n:"纽约大学",e:"New York University",c:"New York, NY",r:38,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$60,438/yr",currency:"USD"},living:"$22,000-28,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 5 (RD), Nov 1 (ED I), Jan 1 (ED II)",note:""},
 schol:[{name:"NYU Merit Scholarships",note:"对国际生需求有关录取；可申请荣誉奖学金 / Need-aware for intl; merit-based available"}],
 materials:["Common App/Coalition","NYU supplement","RL x1","Transcript","SAT/ACT optional"],
 p:[
  {c:"bus",l:"std",g:"SAT 1460+ / ACT 33+",note:"Stern商学院 - 顶级排名 / Stern School of Business - top ranked"},
  {c:"fin",l:"std",g:"SAT 1460+ / ACT 33+",note:"Stern金融方向 / Stern Finance"},
  {c:"cs",l:"std",g:"SAT 1450+ / ACT 33+",note:"Tandon工程学院或文理学院 / Tandon School of Engineering or CAS"},
  {c:"econ",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"media",l:"std",g:"SAT 1440+ / ACT 32+",note:"Steinhardt / Tisch影视学院 / Steinhardt / Tisch Film & TV"},
  {c:"art",l:"std",g:"SAT 1400+ / ACT 31+",note:"Tisch艺术学院；需提交作品集/试镜 / Tisch School of the Arts; portfolio/audition"},
  {c:"ir",l:"std",g:"SAT 1440+ / ACT 32+",note:"政治学 / 全球文理研究 / Politics / Global Liberal Studies"},
  {c:"math",l:"std",g:"SAT 1450+ / ACT 33+",note:"Courant数学科学研究所 / Courant Institute of Mathematical Sciences"},
  {c:"nurs",l:"std",g:"SAT 1400+ / ACT 31+",note:"Rory Meyers护理学院 / Rory Meyers College of Nursing"},
  {c:"psych",l:"std",g:"SAT 1440+ / ACT 32+"}
]},

{id:"gatech",n:"佐治亚理工",e:"Georgia Institute of Technology",c:"Atlanta, GA",r:85,cat:"public",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:90,r:19,w:19,s:19,l:19}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$35,378/yr (OOS)",currency:"USD"},living:"$14,000-18,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 4 (RD), Nov 1 (EA I)",note:""},
 schol:[{name:"GT Stamps Scholarship",note:"全额荣誉奖学金；校长奖学金亦可申请 / Full merit scholarship; President's Scholarship also available"}],
 materials:["Common App/Coalition","GT supplement","RL x1","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1450+ / ACT 33+",note:"计算学院 - 全国前五 / College of Computing - top 5 nationally"},
  {c:"ee",l:"std",g:"SAT 1430+ / ACT 32+"},
  {c:"me",l:"std",g:"SAT 1430+ / ACT 32+",note:"Woodruff机械工程学院 / Woodruff School"},
  {c:"ce",l:"std",g:"SAT 1420+ / ACT 32+"},
  {c:"eng",l:"std",g:"SAT 1430+ / ACT 32+",note:"航空、生物医学、化工、工业工程等 / Aerospace, BME, ChemE, IE, etc."},
  {c:"bus",l:"std",g:"SAT 1420+ / ACT 32+",note:"Scheller商学院 / Scheller College of Business"},
  {c:"ds",l:"std",g:"SAT 1440+ / ACT 33+"},
  {c:"bio",l:"std",g:"SAT 1400+ / ACT 31+",note:"理学院 / College of Sciences"},
  {c:"arch",l:"std",g:"SAT 1400+ / ACT 31+",note:"设计学院；作品集有帮助 / College of Design; portfolio helpful"},
  {c:"math",l:"std",g:"SAT 1430+ / ACT 32+"}
]},

{id:"uiuc",n:"伊利诺伊大学",e:"University of Illinois Urbana-Champaign",c:"Champaign, IL",r:64,cat:"public",
 ll:{std:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:79,r:null,w:null,s:null,l:null}},
     eng:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$38,098/yr (OOS)",currency:"USD"},living:"$12,000-16,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 5",note:"按学院申请 / Apply to specific college"},
 schol:[{name:"UIUC Merit",note:"国际生奖学金有限；部分院系有专项奖学金 / Limited intl scholarships; some department-specific"}],
 materials:["Common App","UIUC supplement","RL x1","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"eng",g:"SAT 1480+ / ACT 34+",note:"Grainger工程学院 - CS全国前五 / Grainger College of Engineering - CS top 5"},
  {c:"ee",l:"eng",g:"SAT 1440+ / ACT 33+",note:"ECE系 / ECE Department"},
  {c:"me",l:"eng",g:"SAT 1420+ / ACT 32+"},
  {c:"ce",l:"eng",g:"SAT 1400+ / ACT 31+"},
  {c:"bus",l:"std",g:"SAT 1400+ / ACT 31+",note:"Gies商学院 / Gies College of Business"},
  {c:"acct",l:"std",g:"SAT 1400+ / ACT 31+",note:"Gies - 顶级会计项目 / Gies - top accounting program"},
  {c:"econ",l:"std",g:"SAT 1360+ / ACT 30+"},
  {c:"ds",l:"eng",g:"SAT 1460+ / ACT 33+",note:"统计学+计算机跨学科 / Statistics + CS interdisciplinary"},
  {c:"bio",l:"std",g:"SAT 1360+ / ACT 30+"},
  {c:"arch",l:"std",g:"SAT 1360+ / ACT 30+",note:"建筑学院 / School of Architecture"}
]},

{id:"utaustin",n:"德克萨斯大学奥斯汀",e:"University of Texas at Austin",c:"Austin, TX",r:58,cat:"public",
 ll:{std:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:79,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$41,070/yr (OOS)",currency:"USD"},living:"$14,000-18,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Dec 1",note:"优先截止日期 / Priority deadline"},
 schol:[{name:"UT Austin International Scholarship",note:"有限；Texas Exes奖学金 / Limited; Texas Exes Scholarship"}],
 materials:["ApplyTexas/Common App","Essays","RL","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1400+ / ACT 32+",note:"顶级CS项目；国际生竞争非常激烈 / Top CS program; very competitive for intl"},
  {c:"eng",l:"std",g:"SAT 1380+ / ACT 31+",note:"Cockrell工程学院 / Cockrell School of Engineering"},
  {c:"bus",l:"std",g:"SAT 1380+ / ACT 31+",note:"McCombs商学院 / McCombs School of Business"},
  {c:"econ",l:"std",g:"SAT 1350+ / ACT 30+"},
  {c:"bio",l:"std",g:"SAT 1350+ / ACT 30+"},
  {c:"media",l:"std",g:"SAT 1350+ / ACT 30+",note:"Moody传播学院 / Moody College of Communication"},
  {c:"arch",l:"std",g:"SAT 1350+ / ACT 30+",note:"建筑学院 / School of Architecture"},
  {c:"math",l:"std",g:"SAT 1380+ / ACT 31+"},
  {c:"ir",l:"std",g:"SAT 1350+ / ACT 30+",note:"LBJ政策学院路径 / 政府学 / LBJ School pathway / Government"}
]},

{id:"uw",n:"华盛顿大学",e:"University of Washington",c:"Seattle, WA",r:63,cat:"public",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:76,r:17,w:17,s:17,l:17}},
     rec:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:92,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y",note:"最低76分，但竞争性录取约92+ / Min 76 but competitive admits ~92+"},
 fee:{ug:"$41,997/yr (OOS)",currency:"USD"},living:"$16,000-20,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Nov 15",note:""},
 schol:[{name:"UW Scholarships",note:"国际生有限；可申请院系奖学金 / Limited for intl; departmental scholarships available"}],
 materials:["Coalition App","Essays","Transcript","SAT/ACT not required"],
 p:[
  {c:"cs",l:"rec",g:"GPA 3.9+",note:"Paul G. Allen计算机学院；直录或竞争性入学 / Paul G. Allen School; direct admit or competitive entry"},
  {c:"eng",l:"rec",g:"GPA 3.8+",note:"工程学院 / College of Engineering"},
  {c:"bio",l:"std",g:"GPA 3.7+"},
  {c:"bus",l:"rec",g:"GPA 3.8+",note:"Foster商学院；大二申请 / Foster School of Business; apply as sophomore"},
  {c:"econ",l:"std",g:"GPA 3.7+"},
  {c:"psych",l:"std",g:"GPA 3.7+"},
  {c:"math",l:"std",g:"GPA 3.7+"},
  {c:"nurs",l:"std",g:"GPA 3.8+",note:"护理学院；竞争激烈 / School of Nursing; highly competitive"},
  {c:"env",l:"std",g:"GPA 3.7+",note:"环境学院 / College of the Environment"}
]},

{id:"purdue",n:"普渡大学",e:"Purdue University",c:"West Lafayette, IN",r:100,cat:"public",
 ll:{std:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:80,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$31,104/yr (OOS)",currency:"USD"},living:"$12,000-15,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 15 (RD), Nov 1 (EA)",note:"按学院申请 / Apply to specific college"},
 schol:[{name:"Purdue Merit Scholarships",note:"国际生竞争性荣誉奖学金 / Competitive merit awards for intl students"}],
 materials:["Common App/Purdue App","Essay","RL x1","Transcript","SAT/ACT recommended"],
 p:[
  {c:"cs",l:"std",g:"SAT 1380+ / ACT 31+",note:"全国前十CS项目 / Top 10 CS program nationally"},
  {c:"eng",l:"std",g:"SAT 1360+ / ACT 30+",note:"工程学院 - 顶级排名 / College of Engineering - top ranked"},
  {c:"ee",l:"std",g:"SAT 1360+ / ACT 30+"},
  {c:"me",l:"std",g:"SAT 1360+ / ACT 30+"},
  {c:"ce",l:"std",g:"SAT 1340+ / ACT 29+"},
  {c:"bus",l:"std",g:"SAT 1340+ / ACT 29+",note:"Daniels商学院 / Daniels School of Business"},
  {c:"bio",l:"std",g:"SAT 1320+ / ACT 28+"},
  {c:"math",l:"std",g:"SAT 1340+ / ACT 29+"},
  {c:"pharm",l:"std",g:"SAT 1360+ / ACT 30+",note:"药学院；直录6年制PharmD / College of Pharmacy; direct admit 6-yr PharmD"},
  {c:"ds",l:"std",g:"SAT 1380+ / ACT 31+",note:"跨学科数据科学 / Data Science interdisciplinary"}
]},

{id:"osu",n:"俄亥俄州立大学",e:"Ohio State University",c:"Columbus, OH",r:140,cat:"public",
 ll:{std:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:79,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$36,722/yr (OOS)",currency:"USD"},living:"$12,000-16,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Feb 1 (RD), Nov 1 (EA)",note:""},
 schol:[{name:"OSU Merit Awards",note:"Maximus、Provost、Trustees奖学金供高分学生申请 / Maximus, Provost, Trustees scholarships for high achievers"}],
 materials:["Common App/OSU App","Essays","Transcript","SAT/ACT recommended"],
 p:[
  {c:"cs",l:"std",g:"SAT 1350+ / ACT 30+"},
  {c:"eng",l:"std",g:"SAT 1350+ / ACT 30+",note:"工程学院 / College of Engineering"},
  {c:"bus",l:"std",g:"SAT 1340+ / ACT 29+",note:"Fisher商学院 / Fisher College of Business"},
  {c:"bio",l:"std",g:"SAT 1300+ / ACT 28+"},
  {c:"nurs",l:"std",g:"SAT 1320+ / ACT 28+"},
  {c:"econ",l:"std",g:"SAT 1300+ / ACT 28+"},
  {c:"psych",l:"std",g:"SAT 1300+ / ACT 28+"},
  {c:"med",l:"std",g:"SAT 1400+ / ACT 31+",note:"医学预科；无直录MD项目 / Pre-med track; no direct-entry MD"}
]},

{id:"psu",n:"宾州州立大学",e:"Pennsylvania State University",c:"University Park, PA",r:89,cat:"public",
 ll:{std:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:80,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$38,824/yr (OOS)",currency:"USD"},living:"$13,000-17,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Rolling (priority Nov 30)",note:""},
 schol:[{name:"Penn State Merit",note:"国际生有限奖学金；Schreyer荣誉学院 / Limited intl awards; Schreyer Honors College"}],
 materials:["Common App/PSU App","Essay","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1340+ / ACT 30+"},
  {c:"eng",l:"std",g:"SAT 1340+ / ACT 30+",note:"规模庞大的工程项目 / Large engineering program"},
  {c:"bus",l:"std",g:"SAT 1320+ / ACT 29+",note:"Smeal商学院 / Smeal College of Business"},
  {c:"econ",l:"std",g:"SAT 1300+ / ACT 28+"},
  {c:"bio",l:"std",g:"SAT 1300+ / ACT 28+"},
  {c:"nurs",l:"std",g:"SAT 1320+ / ACT 29+"},
  {c:"arch",l:"std",g:"SAT 1300+ / ACT 28+",note:"Stuckeman建筑学院 / Stuckeman School of Architecture"},
  {c:"media",l:"std",g:"SAT 1300+ / ACT 28+",note:"Bellisario传播学院 / Bellisario College of Communications"}
]},

{id:"uwmadison",n:"威斯康星大学麦迪逊",e:"University of Wisconsin-Madison",c:"Madison, WI",r:83,cat:"public",
 ll:{std:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:80,r:null,w:null,s:null,l:null}},
     rec:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:95,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$39,427/yr (OOS)",currency:"USD"},living:"$13,000-17,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Feb 1",note:"优先截止日期11月1日 / Priority deadline Nov 1"},
 schol:[{name:"UW-Madison Merit",note:"校长奖学金；国际生有限 / Chancellor's Scholarship; limited for intl"}],
 materials:["Common App/UW System","Essays","RL x1","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"rec",g:"SAT 1380+ / ACT 31+",note:"公立大学CS前十 / Top 10 public CS"},
  {c:"eng",l:"rec",g:"SAT 1360+ / ACT 30+",note:"工程学院 / College of Engineering"},
  {c:"bus",l:"std",g:"SAT 1340+ / ACT 30+",note:"威斯康星商学院 / Wisconsin School of Business"},
  {c:"bio",l:"std",g:"SAT 1320+ / ACT 28+"},
  {c:"econ",l:"std",g:"SAT 1320+ / ACT 28+"},
  {c:"ds",l:"rec",g:"SAT 1380+ / ACT 31+"},
  {c:"math",l:"std",g:"SAT 1340+ / ACT 29+"},
  {c:"nurs",l:"std",g:"SAT 1340+ / ACT 29+",note:"护理学院；直录 / School of Nursing; direct admit"},
  {c:"env",l:"std",g:"SAT 1300+ / ACT 28+",note:"Nelson研究所 / Nelson Institute"}
]},

{id:"uf",n:"佛罗里达大学",e:"University of Florida",c:"Gainesville, FL",r:168,cat:"public",
 ll:{std:{ielts:{t:6.0,r:null,w:null,s:null,l:null},toefl:{t:80,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$28,658/yr (OOS)",currency:"USD"},living:"$12,000-15,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Nov 1 (priority), Mar 1",note:""},
 schol:[{name:"UF Scholarships",note:"国际生有限；Machen佛罗里达机会学者项目 / Limited for intl; Machen Florida Opportunity Scholars"}],
 materials:["Common App/UF App","Essays","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1350+ / ACT 30+",note:"Herbert Wertheim工程学院 / Herbert Wertheim College of Engineering"},
  {c:"eng",l:"std",g:"SAT 1340+ / ACT 30+"},
  {c:"bus",l:"std",g:"SAT 1320+ / ACT 29+",note:"Warrington商学院 / Warrington College of Business"},
  {c:"bio",l:"std",g:"SAT 1300+ / ACT 28+"},
  {c:"econ",l:"std",g:"SAT 1300+ / ACT 28+"},
  {c:"med",l:"std",g:"SAT 1400+ / ACT 31+",note:"医学预科；佛罗里达大学医学院 / Pre-med; UF College of Medicine"},
  {c:"nurs",l:"std",g:"SAT 1320+ / ACT 29+"},
  {c:"pharm",l:"std",g:"SAT 1340+ / ACT 29+",note:"直录PharmD / Direct admit to PharmD"}
]},

{id:"uva",n:"弗吉尼亚大学",e:"University of Virginia",c:"Charlottesville, VA",r:113,cat:"public",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$56,837/yr (OOS)",currency:"USD"},living:"$14,000-18,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 5 (RD), Nov 1 (EA)",note:""},
 schol:[{name:"Jefferson Scholarship",note:"全额荣誉奖学金；UVA最具声望 / Full merit scholarship; most prestigious at UVA"}],
 materials:["Common App/Coalition","UVA supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1420+ / ACT 32+",note:"工程学院 / School of Engineering"},
  {c:"eng",l:"std",g:"SAT 1420+ / ACT 32+"},
  {c:"bus",l:"std",g:"SAT 1430+ / ACT 32+",note:"McIntire商学院（大二申请） / McIntire School of Commerce (apply as 2nd year)"},
  {c:"econ",l:"std",g:"SAT 1400+ / ACT 31+"},
  {c:"bio",l:"std",g:"SAT 1400+ / ACT 31+"},
  {c:"psych",l:"std",g:"SAT 1400+ / ACT 31+"},
  {c:"hist",l:"std",g:"SAT 1400+ / ACT 31+"},
  {c:"ir",l:"std",g:"SAT 1420+ / ACT 32+",note:"Batten领导力学院 / 政治学 / Batten School of Leadership / Politics"},
  {c:"arch",l:"std",g:"SAT 1380+ / ACT 31+",note:"建筑学院 / School of Architecture"}
]},

{id:"unc",n:"北卡教堂山",e:"University of North Carolina at Chapel Hill",c:"Chapel Hill, NC",r:53,cat:"public",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$39,338/yr (OOS)",currency:"USD"},living:"$13,000-17,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 15 (RD), Oct 15 (EA)",note:""},
 schol:[{name:"Morehead-Cain Scholarship",note:"全额荣誉奖学金 - 美国历史最悠久 / Full merit scholarship - oldest in US"}],
 materials:["Common App/Coalition","Short answer essays","RL x1","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1380+ / ACT 31+"},
  {c:"bus",l:"std",g:"SAT 1400+ / ACT 31+",note:"Kenan-Flagler商学院；大二申请 / Kenan-Flagler; apply sophomore year"},
  {c:"bio",l:"std",g:"SAT 1360+ / ACT 30+"},
  {c:"econ",l:"std",g:"SAT 1360+ / ACT 30+"},
  {c:"media",l:"std",g:"SAT 1360+ / ACT 30+",note:"Hussman新闻学院 / Hussman School of Journalism"},
  {c:"psych",l:"std",g:"SAT 1360+ / ACT 30+"},
  {c:"nurs",l:"std",g:"SAT 1360+ / ACT 30+",note:"护理学院；直录BSN / School of Nursing; direct-admit BSN"},
  {c:"ph",l:"std",g:"SAT 1380+ / ACT 31+",note:"Gillings公共卫生学院 / Gillings School of Public Health"}
]},

{id:"emory",n:"埃默里大学",e:"Emory University",c:"Atlanta, GA",r:126,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$60,774/yr",currency:"USD"},living:"$16,000-20,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 1 (RD), Nov 1 (ED I)",note:""},
 schol:[{name:"Emory Scholars",note:"全额荣誉奖学金；多条评选路径 / Full merit scholarships; multiple tracks"}],
 materials:["Common App/Coalition","Emory supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"bus",l:"std",g:"SAT 1440+ / ACT 32+",note:"Goizueta商学院 / Goizueta Business School"},
  {c:"bio",l:"std",g:"SAT 1440+ / ACT 32+",note:"强医学预科；埃默里医院 / Strong pre-med; Emory Hospital"},
  {c:"cs",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"econ",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"psych",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"nurs",l:"std",g:"SAT 1420+ / ACT 31+",note:"Nell Hodgson Woodruff护理学院 / Nell Hodgson Woodruff School of Nursing"},
  {c:"hist",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"med",l:"std",g:"SAT 1460+ / ACT 33+",note:"医学预科；埃默里医学院 / Pre-med; Emory School of Medicine"}
]},

{id:"notredame",n:"圣母大学",e:"University of Notre Dame",c:"Notre Dame, IN",r:176,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$62,693/yr",currency:"USD"},living:"$17,000-21,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 1 (RD), Nov 1 (REA)",note:""},
 schol:[{name:"Notre Dame Scholarship",note:"需求为基础；满足100%经济需求 / Need-based; meets 100% demonstrated need"}],
 materials:["Common App","Notre Dame supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"bus",l:"std",g:"SAT 1440+ / ACT 33+",note:"Mendoza商学院 - 顶级排名 / Mendoza College of Business - top ranked"},
  {c:"cs",l:"std",g:"SAT 1440+ / ACT 33+",note:"工程学院 / College of Engineering"},
  {c:"eng",l:"std",g:"SAT 1440+ / ACT 33+"},
  {c:"econ",l:"std",g:"SAT 1440+ / ACT 33+"},
  {c:"ir",l:"std",g:"SAT 1440+ / ACT 33+",note:"Keough学院；政治学 / Keough School; Political Science"},
  {c:"bio",l:"std",g:"SAT 1440+ / ACT 33+"},
  {c:"psych",l:"std",g:"SAT 1440+ / ACT 33+"},
  {c:"arch",l:"std",g:"SAT 1420+ / ACT 32+",note:"5年制建筑学学士；需提交作品集 / 5-year B.Arch; portfolio required"}
]},

{id:"tufts",n:"塔夫茨大学",e:"Tufts University",c:"Medford, MA",r:262,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$65,222/yr",currency:"USD"},living:"$18,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 3 (RD), Nov 1 (ED I)",note:""},
 schol:[{name:"Tufts Financial Aid",note:"对国际生需求有关录取；满足100%经济需求 / Need-aware for intl; meets 100% demonstrated need"}],
 materials:["Common App/Coalition","Tufts supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"ir",l:"std",g:"SAT 1440+ / ACT 32+",note:"Fletcher学院路径；强国关/政治项目 / Fletcher School pathway; strong IR/politics"},
  {c:"cs",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"eng",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"bio",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"econ",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"psych",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"env",l:"std",g:"SAT 1420+ / ACT 31+"},
  {c:"med",l:"std",g:"SAT 1460+ / ACT 33+",note:"医学预科；塔夫茨医疗中心 / Pre-med track; Tufts Medical Center"}
]},

{id:"bu",n:"波士顿大学",e:"Boston University",c:"Boston, MA",r:87,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:90,r:20,w:22,s:20,l:21}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$63,798/yr",currency:"USD"},living:"$18,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 4 (RD), Nov 1 (ED I)",note:""},
 schol:[{name:"BU Presidential Scholarship",note:"全额学费荣誉奖学金；另有Trustee奖学金 / Full tuition merit; Trustee Scholarship also"}],
 materials:["Common App","BU supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1400+ / ACT 32+",note:"文理学院或工程学院 / College of Arts & Sciences or Engineering"},
  {c:"eng",l:"std",g:"SAT 1400+ / ACT 32+",note:"工程学院 / College of Engineering"},
  {c:"bus",l:"std",g:"SAT 1400+ / ACT 32+",note:"Questrom商学院 / Questrom School of Business"},
  {c:"media",l:"std",g:"SAT 1380+ / ACT 31+",note:"传播学院 / College of Communication"},
  {c:"bio",l:"std",g:"SAT 1380+ / ACT 31+"},
  {c:"econ",l:"std",g:"SAT 1380+ / ACT 31+"},
  {c:"ir",l:"std",g:"SAT 1380+ / ACT 31+",note:"Pardee全球研究学院 / Pardee School of Global Studies"},
  {c:"psych",l:"std",g:"SAT 1380+ / ACT 31+"},
  {c:"nurs",l:"std",g:"SAT 1360+ / ACT 30+"},
  {c:"edu",l:"std",g:"SAT 1340+ / ACT 30+",note:"Wheelock教育学院 / Wheelock College of Education"}
]},

{id:"neu",n:"东北大学",e:"Northeastern University",c:"Boston, MA",r:326,cat:"private",
 ll:{std:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:92,r:null,w:null,s:null,l:null}},
     rec:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:99,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$60,192/yr",currency:"USD"},living:"$18,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 1 (RD), Nov 1 (ED/EA)",note:""},
 schol:[{name:"NEU Dean's Scholarship",note:"以成绩为基础；最高全额学费 / Merit-based; up to full tuition"}],
 materials:["Common App","NEU supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"rec",g:"SAT 1430+ / ACT 33+",note:"Khoury计算机科学学院；含Co-op项目 / Khoury College of Computer Sciences; co-op program"},
  {c:"eng",l:"rec",g:"SAT 1420+ / ACT 32+",note:"含Co-op实习 / Co-op integrated"},
  {c:"bus",l:"std",g:"SAT 1400+ / ACT 31+",note:"D'Amore-McKim商学院 / D'Amore-McKim School of Business"},
  {c:"ds",l:"rec",g:"SAT 1430+ / ACT 33+",note:"数据科学+Co-op / Data Science + co-op"},
  {c:"bio",l:"std",g:"SAT 1380+ / ACT 31+"},
  {c:"econ",l:"std",g:"SAT 1380+ / ACT 31+"},
  {c:"ir",l:"std",g:"SAT 1380+ / ACT 31+",note:"国际事务 / International Affairs"},
  {c:"psych",l:"std",g:"SAT 1380+ / ACT 31+"},
  {c:"nurs",l:"std",g:"SAT 1380+ / ACT 31+",note:"Bouvé健康科学学院 / Bouvé College of Health Sciences"},
  {c:"pharm",l:"std",g:"SAT 1380+ / ACT 31+",note:"6年制PharmD含Co-op / 6-year PharmD co-op"}
]}

];
COMPASS_DATA.usa = D;
})();
