// data-us.js - US Universities Undergraduate Programs (50+)
// All data: undergraduate only. Language reqs, entry grades, programs offered.
(function(){
var D = [
// ============ IVY LEAGUE ============
{id:"harvard",n:"哈佛大学",e:"Harvard University",c:"Cambridge, MA",r:4,cat:"ivy",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y",note:"Recommends but does not require English tests for most applicants"},
 fee:{ug:"$59,076/yr",currency:"USD"},living:"$22,000-25,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1 student visa"},
 ddl:{fall:"Jan 1 (RD), Nov 1 (REA)",note:"Need-blind for internationals"},
 schol:[{name:"Harvard Financial Aid",note:"100% demonstrated need met; avg grant $59k+"}],
 materials:["Common App","Essay","RL x2","Transcript","SAT/ACT optional","Interview"],
 p:[
  {c:"cs",l:"std",g:"SAT 1500+ / ACT 34+",note:"John A. Paulson School of Engineering"},
  {c:"econ",l:"std",g:"SAT 1500+ / ACT 34+",note:"Most popular concentration"},
  {c:"bio",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"math",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"phys",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"psych",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"hist",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"eng",l:"std",g:"SAT 1500+ / ACT 34+",note:"Applied Mathematics & Engineering Sciences"},
  {c:"ir",l:"std",g:"SAT 1500+ / ACT 34+",note:"Government concentration"},
  {c:"phil",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"soc",l:"std",g:"SAT 1500+ / ACT 34+",note:"Sociology department"},
  {c:"env",l:"std",g:"SAT 1500+ / ACT 34+",note:"Environmental Science & Engineering"}
]},

{id:"mit",n:"MIT",e:"Massachusetts Institute of Technology",c:"Cambridge, MA",r:1,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:90,r:null,w:null,s:null,l:null}},
     rec:{ielts:{t:7.5,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y",note:"TOEFL 90 minimum, 100+ recommended"},
 fee:{ug:"$61,990/yr",currency:"USD"},living:"$22,000-24,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1 student visa"},
 ddl:{fall:"Jan 1 (RD), Nov 1 (EA)",note:"Need-blind for internationals"},
 schol:[{name:"MIT Financial Aid",note:"100% demonstrated need met; ~60% receive aid"}],
 materials:["MIT Application","Essays x5","RL x2","Transcript","SAT/ACT optional","Interview"],
 p:[
  {c:"cs",l:"rec",g:"SAT 1520+ / ACT 35+",note:"Course 6 - EECS; most popular major"},
  {c:"ee",l:"rec",g:"SAT 1520+ / ACT 35+",note:"Course 6-1/6-2"},
  {c:"me",l:"rec",g:"SAT 1520+ / ACT 35+",note:"Course 2"},
  {c:"ce",l:"std",g:"SAT 1520+ / ACT 35+",note:"Course 1"},
  {c:"math",l:"rec",g:"SAT 1520+ / ACT 35+",note:"Course 18"},
  {c:"phys",l:"rec",g:"SAT 1520+ / ACT 35+",note:"Course 8"},
  {c:"chem",l:"std",g:"SAT 1520+ / ACT 35+",note:"Course 5"},
  {c:"bio",l:"std",g:"SAT 1520+ / ACT 35+",note:"Course 7"},
  {c:"econ",l:"std",g:"SAT 1520+ / ACT 35+",note:"Course 14"},
  {c:"arch",l:"std",g:"SAT 1520+ / ACT 35+",note:"Course 4; portfolio recommended"},
  {c:"ds",l:"rec",g:"SAT 1520+ / ACT 35+",note:"Interdisciplinary Data Science"},
  {c:"ai",l:"rec",g:"SAT 1520+ / ACT 35+",note:"Course 6-4"}
]},

{id:"stanford",n:"斯坦福大学",e:"Stanford University",c:"Stanford, CA",r:2,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:true,v:"2y",note:"English proficiency proof required; no minimum published"},
 fee:{ug:"$62,484/yr",currency:"USD"},living:"$22,000-26,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1 student visa"},
 ddl:{fall:"Jan 2 (RD), Nov 1 (REA)",note:"Need-blind for internationals"},
 schol:[{name:"Stanford Financial Aid",note:"100% demonstrated need; no loans; family <$100k = free tuition"}],
 materials:["Common App/Coalition","Essays","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1500+ / ACT 34+",note:"Stanford Engineering; acceptance rate ~4%"},
  {c:"eng",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"ee",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"econ",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"math",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"bio",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"phys",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"psych",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"ir",l:"std",g:"SAT 1500+ / ACT 34+",note:"International Relations"},
  {c:"ds",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"env",l:"std",g:"SAT 1500+ / ACT 34+",note:"Earth Systems"},
  {c:"media",l:"std",g:"SAT 1500+ / ACT 34+",note:"Communication"}
]},

{id:"princeton",n:"普林斯顿大学",e:"Princeton University",c:"Princeton, NJ",r:12,cat:"ivy",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$59,710/yr",currency:"USD"},living:"$19,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 1 (RD), Nov 1 (SCEA)",note:"Need-blind for internationals"},
 schol:[{name:"Princeton Financial Aid",note:"100% need met; grants not loans; avg grant ~$60k"}],
 materials:["Common App","Essays","RL x2","Transcript","SAT/ACT required","Graded paper"],
 p:[
  {c:"cs",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"econ",l:"std",g:"SAT 1510+ / ACT 34+",note:"Most popular major"},
  {c:"math",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"phys",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"eng",l:"std",g:"SAT 1510+ / ACT 34+",note:"BSE Engineering"},
  {c:"ir",l:"std",g:"SAT 1510+ / ACT 34+",note:"Politics / SPIA"},
  {c:"hist",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"phil",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"chem",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"arch",l:"std",g:"SAT 1510+ / ACT 34+",note:"Architecture & Engineering"}
]},

{id:"yale",n:"耶鲁大学",e:"Yale University",c:"New Haven, CT",r:9,cat:"ivy",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$64,700/yr",currency:"USD"},living:"$19,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 2 (RD), Nov 1 (SCEA)",note:"Need-blind for internationals"},
 schol:[{name:"Yale Financial Aid",note:"100% need met; avg grant ~$62k"}],
 materials:["Common App/Coalition","Essays","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"econ",l:"std",g:"SAT 1500+ / ACT 34+",note:"Most popular major"},
  {c:"bio",l:"std",g:"SAT 1500+ / ACT 34+",note:"Molecular Biophysics & Biochemistry"},
  {c:"math",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"psych",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"hist",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"ir",l:"std",g:"SAT 1500+ / ACT 34+",note:"Political Science / Global Affairs"},
  {c:"art",l:"std",g:"SAT 1500+ / ACT 34+",note:"Art; portfolio required"},
  {c:"ling",l:"std",g:"SAT 1500+ / ACT 34+",note:"Linguistics Department"},
  {c:"env",l:"std",g:"SAT 1500+ / ACT 34+",note:"Environment & Sustainability"}
]},

{id:"columbia",n:"哥伦比亚大学",e:"Columbia University",c:"New York, NY",r:7,cat:"ivy",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$65,524/yr",currency:"USD"},living:"$20,000-28,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 1 (RD), Nov 1 (ED)",note:""},
 schol:[{name:"Columbia Financial Aid",note:"100% need met; need-blind for all"}],
 materials:["Common App/Coalition","Essays","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1500+ / ACT 34+",note:"Fu Foundation School of Engineering"},
  {c:"econ",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"eng",l:"std",g:"SAT 1500+ / ACT 34+",note:"SEAS - Applied Physics, BME, etc."},
  {c:"bio",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"math",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"ir",l:"std",g:"SAT 1500+ / ACT 34+",note:"Political Science / SIPA track"},
  {c:"hist",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"psych",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"arch",l:"std",g:"SAT 1500+ / ACT 34+",note:"GSAPP - Architecture"},
  {c:"media",l:"std",g:"SAT 1500+ / ACT 34+",note:"Journalism (Barnard)"}
]},

{id:"upenn",n:"宾夕法尼亚大学",e:"University of Pennsylvania",c:"Philadelphia, PA",r:11,cat:"ivy",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:25,s:25,l:25}},
     wharton:{ielts:{t:7.5,r:null,w:null,s:null,l:null},toefl:{t:105,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$63,452/yr",currency:"USD"},living:"$18,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 5 (RD), Nov 1 (ED)",note:""},
 schol:[{name:"UPenn Grant",note:"100% need met; need-aware for internationals"}],
 materials:["Common App","Essays","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"bus",l:"wharton",g:"SAT 1500+ / ACT 34+",note:"Wharton School - BS in Economics"},
  {c:"fin",l:"wharton",g:"SAT 1500+ / ACT 34+",note:"Wharton Finance concentration"},
  {c:"cs",l:"std",g:"SAT 1500+ / ACT 34+",note:"School of Engineering"},
  {c:"eng",l:"std",g:"SAT 1500+ / ACT 34+",note:"SEAS - Bioengineering, Systems, etc."},
  {c:"econ",l:"std",g:"SAT 1500+ / ACT 34+",note:"College of Arts & Sciences"},
  {c:"bio",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"nurs",l:"std",g:"SAT 1480+ / ACT 33+",note:"Penn Nursing - top ranked"},
  {c:"ir",l:"std",g:"SAT 1500+ / ACT 34+",note:"Political Science"},
  {c:"psych",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"arch",l:"std",g:"SAT 1500+ / ACT 34+",note:"Stuart Weitzman School of Design"}
]},

{id:"cornell",n:"康奈尔大学",e:"Cornell University",c:"Ithaca, NY",r:16,cat:"ivy",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$63,200/yr",currency:"USD"},living:"$17,000-21,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 2 (RD), Nov 1 (ED)",note:""},
 schol:[{name:"Cornell Financial Aid",note:"Need-aware for internationals; generous aid"}],
 materials:["Common App","School-specific supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1480+ / ACT 34+",note:"College of Engineering or Arts & Sciences"},
  {c:"eng",l:"std",g:"SAT 1480+ / ACT 34+",note:"7 schools: Engineering, Agriculture, ILR, etc."},
  {c:"ee",l:"std",g:"SAT 1480+ / ACT 34+",note:"ECE"},
  {c:"bus",l:"std",g:"SAT 1480+ / ACT 34+",note:"Dyson School in SC Johnson"},
  {c:"bio",l:"std",g:"SAT 1480+ / ACT 34+",note:"CALS"},
  {c:"econ",l:"std",g:"SAT 1480+ / ACT 34+"},
  {c:"arch",l:"std",g:"SAT 1460+ / ACT 33+",note:"AAP; 5-year B.Arch; portfolio required"},
  {c:"env",l:"std",g:"SAT 1460+ / ACT 33+",note:"CALS - Environmental Engineering"},
  {c:"psych",l:"std",g:"SAT 1480+ / ACT 34+"},
  {c:"vet",l:"std",g:"SAT 1480+ / ACT 34+",note:"Pre-vet track; Vet college is top ranked"}
]},

{id:"brown",n:"布朗大学",e:"Brown University",c:"Providence, RI",r:63,cat:"ivy",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$65,146/yr",currency:"USD"},living:"$18,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 5 (RD), Nov 1 (ED)",note:"Need-blind domestically; need-aware intl"},
 schol:[{name:"Brown Financial Aid",note:"Need-based; meets 100% demonstrated need"}],
 materials:["Common App","Essays","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1480+ / ACT 34+"},
  {c:"econ",l:"std",g:"SAT 1480+ / ACT 34+"},
  {c:"bio",l:"std",g:"SAT 1480+ / ACT 34+"},
  {c:"math",l:"std",g:"SAT 1480+ / ACT 34+",note:"Applied Math popular"},
  {c:"eng",l:"std",g:"SAT 1480+ / ACT 34+"},
  {c:"ir",l:"std",g:"SAT 1480+ / ACT 34+",note:"International & Public Affairs"},
  {c:"psych",l:"std",g:"SAT 1480+ / ACT 34+",note:"Cognitive Science track available"},
  {c:"hist",l:"std",g:"SAT 1480+ / ACT 34+"},
  {c:"med",l:"std",g:"SAT 1500+ / ACT 34+",note:"PLME 8-year BS/MD; extremely selective"}
]},

{id:"dartmouth",n:"达特茅斯学院",e:"Dartmouth College",c:"Hanover, NH",r:237,cat:"ivy",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$62,658/yr",currency:"USD"},living:"$18,000-21,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 2 (RD), Nov 1 (ED)",note:"Need-blind for internationals"},
 schol:[{name:"Dartmouth Financial Aid",note:"100% need met; need-blind for all"}],
 materials:["Common App","Dartmouth writing supplement","RL x2","Transcript","SAT/ACT required","Peer eval"],
 p:[
  {c:"cs",l:"std",g:"SAT 1480+ / ACT 33+"},
  {c:"econ",l:"std",g:"SAT 1480+ / ACT 33+",note:"Economics - most popular"},
  {c:"eng",l:"std",g:"SAT 1480+ / ACT 33+",note:"Thayer School of Engineering"},
  {c:"math",l:"std",g:"SAT 1480+ / ACT 33+"},
  {c:"bio",l:"std",g:"SAT 1480+ / ACT 33+"},
  {c:"hist",l:"std",g:"SAT 1480+ / ACT 33+"},
  {c:"ir",l:"std",g:"SAT 1480+ / ACT 33+",note:"Government"},
  {c:"env",l:"std",g:"SAT 1480+ / ACT 33+",note:"Environmental Studies"}
]},

// ============ TOP PRIVATE ============
{id:"caltech",n:"加州理工",e:"California Institute of Technology",c:"Pasadena, CA",r:5,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$63,255/yr",currency:"USD"},living:"$20,000-23,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 3 (RD), Nov 1 (REA)",note:"Need-blind domestically"},
 schol:[{name:"Caltech Financial Aid",note:"100% need met; avg grant >$50k"}],
 materials:["Common App/Coalition","Caltech essays","RL x2","Transcript","SAT/ACT required"],
 p:[
  {c:"cs",l:"std",g:"SAT 1530+ / ACT 35+"},
  {c:"ee",l:"std",g:"SAT 1530+ / ACT 35+"},
  {c:"me",l:"std",g:"SAT 1530+ / ACT 35+"},
  {c:"phys",l:"std",g:"SAT 1530+ / ACT 35+",note:"Renowned physics program"},
  {c:"math",l:"std",g:"SAT 1530+ / ACT 35+"},
  {c:"chem",l:"std",g:"SAT 1530+ / ACT 35+"},
  {c:"bio",l:"std",g:"SAT 1530+ / ACT 35+"},
  {c:"env",l:"std",g:"SAT 1530+ / ACT 35+",note:"Environmental Science & Engineering"}
]},

{id:"duke",n:"杜克大学",e:"Duke University",c:"Durham, NC",r:24,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$63,054/yr",currency:"USD"},living:"$18,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 4 (RD), Nov 1 (ED)",note:""},
 schol:[{name:"Duke Financial Aid",note:"Need-blind domestically; need-aware intl; meets 100%"}],
 materials:["Common App","Duke supplement","RL x2","Transcript","SAT/ACT optional","Optional interview"],
 p:[
  {c:"cs",l:"std",g:"SAT 1500+ / ACT 34+",note:"Pratt School of Engineering or Trinity"},
  {c:"econ",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"bus",l:"std",g:"SAT 1500+ / ACT 34+",note:"Economics + Markets & Management certificate"},
  {c:"bio",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"eng",l:"std",g:"SAT 1500+ / ACT 34+",note:"Pratt School of Engineering"},
  {c:"psych",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"ir",l:"std",g:"SAT 1500+ / ACT 34+",note:"Public Policy / Political Science"},
  {c:"env",l:"std",g:"SAT 1500+ / ACT 34+",note:"Nicholas School - Environmental Sciences"},
  {c:"stat",l:"std",g:"SAT 1500+ / ACT 34+",note:"Statistical Science"},
  {c:"hist",l:"std",g:"SAT 1500+ / ACT 34+"}
]},

{id:"northwestern",n:"西北大学",e:"Northwestern University",c:"Evanston, IL",r:24,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$63,468/yr",currency:"USD"},living:"$19,000-23,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 3 (RD), Nov 1 (ED)",note:""},
 schol:[{name:"Northwestern Aid",note:"Need-aware for intl; meets 100% demonstrated need"}],
 materials:["Common App/Coalition","NU supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1490+ / ACT 34+",note:"McCormick School of Engineering"},
  {c:"econ",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"media",l:"std",g:"SAT 1490+ / ACT 34+",note:"Medill School of Journalism - top ranked"},
  {c:"eng",l:"std",g:"SAT 1490+ / ACT 34+",note:"McCormick Engineering"},
  {c:"bus",l:"std",g:"SAT 1490+ / ACT 34+",note:"Kellogg certificate pathway available"},
  {c:"psych",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"bio",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"art",l:"std",g:"SAT 1490+ / ACT 34+",note:"Bienen School of Music / Communication Studies"},
  {c:"math",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"edu",l:"std",g:"SAT 1490+ / ACT 34+",note:"School of Education & Social Policy"}
]},

{id:"uchicago",n:"芝加哥大学",e:"University of Chicago",c:"Chicago, IL",r:11,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$64,260/yr",currency:"USD"},living:"$20,000-24,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 2 (RD), Nov 1/2 (ED I/II)",note:""},
 schol:[{name:"UChicago Odyssey",note:"Need-blind domestically; generous merit + need-based aid"}],
 materials:["Common App/Coalition/UChicago App","Extended essay","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"econ",l:"std",g:"SAT 1510+ / ACT 34+",note:"Nobel laureates; strongest economics program"},
  {c:"cs",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"math",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"phys",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"bio",l:"std",g:"SAT 1510+ / ACT 34+",note:"Biological Sciences; strong pre-med"},
  {c:"ir",l:"std",g:"SAT 1510+ / ACT 34+",note:"Political Science / Public Policy"},
  {c:"phil",l:"std",g:"SAT 1510+ / ACT 34+",note:"Top philosophy department"},
  {c:"stat",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"hist",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"soc",l:"std",g:"SAT 1510+ / ACT 34+"}
]},

{id:"jhu",n:"约翰斯·霍普金斯大学",e:"Johns Hopkins University",c:"Baltimore, MD",r:15,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:26,w:22,s:25,l:26}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$62,840/yr",currency:"USD"},living:"$18,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 2 (RD), Nov 1 (ED)",note:""},
 schol:[{name:"JHU Financial Aid",note:"Need-aware intl; meets 100%"}],
 materials:["Common App","JHU supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"bio",l:"std",g:"SAT 1500+ / ACT 34+",note:"#1 biomedical research university"},
  {c:"cs",l:"std",g:"SAT 1500+ / ACT 34+",note:"Whiting School of Engineering"},
  {c:"eng",l:"std",g:"SAT 1500+ / ACT 34+",note:"BME top ranked nationally"},
  {c:"ph",l:"std",g:"SAT 1500+ / ACT 34+",note:"Bloomberg School of Public Health pathway"},
  {c:"ir",l:"std",g:"SAT 1500+ / ACT 34+",note:"SAIS - International Studies"},
  {c:"econ",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"math",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"psych",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"media",l:"std",g:"SAT 1500+ / ACT 34+",note:"Writing Seminars"},
  {c:"nurs",l:"std",g:"SAT 1480+ / ACT 33+",note:"Direct-entry BSN"}
]},

{id:"rice",n:"莱斯大学",e:"Rice University",c:"Houston, TX",r:92,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$56,874/yr",currency:"USD"},living:"$16,000-20,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 4 (RD), Nov 1 (ED)",note:"Need-blind domestically"},
 schol:[{name:"Rice Financial Aid",note:"Need-aware intl; Rice Investment reduces cost significantly"}],
 materials:["Common App/Coalition","Rice supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"eng",l:"std",g:"SAT 1490+ / ACT 34+",note:"George R. Brown School of Engineering"},
  {c:"bio",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"econ",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"arch",l:"std",g:"SAT 1480+ / ACT 33+",note:"Top-ranked architecture; portfolio required"},
  {c:"math",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"phys",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"bus",l:"std",g:"SAT 1490+ / ACT 34+",note:"Jones Graduate School pathway"}
]},

{id:"vanderbilt",n:"范德堡大学",e:"Vanderbilt University",c:"Nashville, TN",r:155,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$62,194/yr",currency:"USD"},living:"$18,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 1 (RD), Nov 1 (ED I)",note:""},
 schol:[{name:"Vanderbilt Scholarship",note:"Multiple merit: Cornelius Vanderbilt, Ingram, Chancellor's"}],
 materials:["Common App/Coalition","Vandy supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1490+ / ACT 34+",note:"School of Engineering"},
  {c:"econ",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"edu",l:"std",g:"SAT 1480+ / ACT 33+",note:"Peabody College - #1 ranked"},
  {c:"bio",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"eng",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"psych",l:"std",g:"SAT 1490+ / ACT 34+",note:"Human & Organizational Development"},
  {c:"med",l:"std",g:"SAT 1500+ / ACT 34+",note:"Pre-med track; no direct-entry MD"},
  {c:"media",l:"std",g:"SAT 1490+ / ACT 34+",note:"Communication Studies"}
]},

{id:"cmu",n:"卡内基梅隆大学",e:"Carnegie Mellon University",c:"Pittsburgh, PA",r:52,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:102,r:25,w:25,s:25,l:25}},
     scs:{ielts:{t:7.5,r:null,w:null,s:null,l:null},toefl:{t:102,r:25,w:25,s:25,l:25}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$62,260/yr",currency:"USD"},living:"$18,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 3 (RD), Nov 1 (ED)",note:""},
 schol:[{name:"CMU Presidential Scholarship",note:"Merit-based; full tuition for top applicants"}],
 materials:["Common App/Coalition","CMU supplement","RL x2","Transcript","SAT/ACT required","Portfolio (design)"],
 p:[
  {c:"cs",l:"scs",g:"SAT 1530+ / ACT 35+",note:"School of Computer Science - #1 globally"},
  {c:"ai",l:"scs",g:"SAT 1530+ / ACT 35+",note:"BS in Artificial Intelligence (first in US)"},
  {c:"ee",l:"std",g:"SAT 1500+ / ACT 34+",note:"ECE Department"},
  {c:"me",l:"std",g:"SAT 1500+ / ACT 34+"},
  {c:"ds",l:"scs",g:"SAT 1520+ / ACT 34+",note:"Statistics & Data Science"},
  {c:"bus",l:"std",g:"SAT 1500+ / ACT 34+",note:"Tepper School of Business"},
  {c:"art",l:"std",g:"SAT 1460+ / ACT 33+",note:"School of Design; portfolio required"},
  {c:"arch",l:"std",g:"SAT 1460+ / ACT 33+",note:"School of Architecture; portfolio required"},
  {c:"math",l:"std",g:"SAT 1510+ / ACT 34+"},
  {c:"stat",l:"std",g:"SAT 1500+ / ACT 34+",note:"Dietrich College"},
  {c:"psych",l:"std",g:"SAT 1480+ / ACT 33+"}
]},

{id:"georgetown",n:"乔治城大学",e:"Georgetown University",c:"Washington, DC",r:182,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$62,844/yr",currency:"USD"},living:"$20,000-24,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 10 (RD), Nov 1 (REA)",note:""},
 schol:[{name:"Georgetown Scholarship",note:"Limited merit + need-based for intl students"}],
 materials:["Georgetown Application (own portal)","Essays","RL x2","Transcript","SAT/ACT required"],
 p:[
  {c:"ir",l:"std",g:"SAT 1460+ / ACT 33+",note:"Walsh School of Foreign Service - #1 globally"},
  {c:"bus",l:"std",g:"SAT 1460+ / ACT 33+",note:"McDonough School of Business"},
  {c:"fin",l:"std",g:"SAT 1460+ / ACT 33+",note:"McDonough Finance"},
  {c:"ir",l:"std",g:"SAT 1460+ / ACT 33+",note:"Government & Politics"},
  {c:"econ",l:"std",g:"SAT 1460+ / ACT 33+"},
  {c:"bio",l:"std",g:"SAT 1460+ / ACT 33+"},
  {c:"hist",l:"std",g:"SAT 1460+ / ACT 33+"},
  {c:"ling",l:"std",g:"SAT 1460+ / ACT 33+",note:"Linguistics Department"},
  {c:"nurs",l:"std",g:"SAT 1440+ / ACT 32+",note:"School of Nursing & Health Studies"}
]},

{id:"washu",n:"华盛顿大学(圣路易斯)",e:"Washington University in St. Louis",c:"St. Louis, MO",r:100,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$62,782/yr",currency:"USD"},living:"$19,000-23,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 4 (RD), Nov 1 (ED)",note:""},
 schol:[{name:"WashU Financial Aid",note:"Need-aware for intl; generous merit scholarships"}],
 materials:["Common App/Coalition","WashU supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1490+ / ACT 34+",note:"McKelvey School of Engineering"},
  {c:"bus",l:"std",g:"SAT 1490+ / ACT 34+",note:"Olin Business School - top ranked"},
  {c:"fin",l:"std",g:"SAT 1490+ / ACT 34+",note:"Olin BSBA Finance"},
  {c:"econ",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"bio",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"eng",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"psych",l:"std",g:"SAT 1490+ / ACT 34+"},
  {c:"arch",l:"std",g:"SAT 1470+ / ACT 33+",note:"Sam Fox School; portfolio required"},
  {c:"art",l:"std",g:"SAT 1470+ / ACT 33+",note:"Sam Fox School of Design & Visual Arts"}
]},

// ============ TOP PUBLIC (UC系统 + 公立旗舰) ============
{id:"ucb",n:"加州大学伯克利",e:"UC Berkeley",c:"Berkeley, CA",r:10,cat:"public",
 ll:{std:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:80,r:null,w:null,s:null,l:null}},
     rec:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y",note:"Minimum 80, but competitive admits typically 100+"},
 fee:{ug:"$47,066/yr (OOS)",currency:"USD"},living:"$20,000-25,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Nov 30 (UC deadline)",note:"UC Application; no ED/EA"},
 schol:[{name:"Berkeley International Scholarship",note:"Limited; mostly merit-based; Regents' Scholarship"}],
 materials:["UC Application","Personal insight questions x4","Transcript","SAT/ACT not considered"],
 p:[
  {c:"cs",l:"rec",g:"GPA 4.0+ (weighted)",note:"EECS (L&S or Engineering); acceptance rate ~5%"},
  {c:"eng",l:"rec",g:"GPA 4.0+ (weighted)",note:"College of Engineering"},
  {c:"ee",l:"rec",g:"GPA 4.0+ (weighted)"},
  {c:"ds",l:"rec",g:"GPA 4.0+ (weighted)",note:"Data Science major - new and popular"},
  {c:"econ",l:"std",g:"GPA 3.9+ (weighted)"},
  {c:"bus",l:"rec",g:"GPA 4.0+ (weighted)",note:"Haas School of Business; very competitive"},
  {c:"bio",l:"std",g:"GPA 3.9+ (weighted)"},
  {c:"math",l:"std",g:"GPA 3.9+ (weighted)"},
  {c:"phys",l:"std",g:"GPA 3.9+ (weighted)"},
  {c:"env",l:"std",g:"GPA 3.9+ (weighted)",note:"College of Natural Resources"},
  {c:"arch",l:"std",g:"GPA 3.8+ (weighted)",note:"CED; portfolio not required for UG"}
]},

{id:"ucla",n:"加州大学洛杉矶",e:"UCLA",c:"Los Angeles, CA",r:18,cat:"public",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$46,326/yr (OOS)",currency:"USD"},living:"$20,000-25,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Nov 30 (UC deadline)",note:"UC Application"},
 schol:[{name:"UCLA Regents Scholarship",note:"Top merit-based; full tuition + stipend"}],
 materials:["UC Application","Personal insight questions x4","Transcript"],
 p:[
  {c:"cs",l:"std",g:"GPA 4.0+ (weighted)",note:"Henry Samueli School of Engineering"},
  {c:"eng",l:"std",g:"GPA 4.0+ (weighted)"},
  {c:"bio",l:"std",g:"GPA 3.9+ (weighted)",note:"Life Sciences division"},
  {c:"econ",l:"std",g:"GPA 3.9+ (weighted)",note:"Business Economics very popular"},
  {c:"psych",l:"std",g:"GPA 3.9+ (weighted)",note:"Top psychology program"},
  {c:"math",l:"std",g:"GPA 3.9+ (weighted)"},
  {c:"media",l:"std",g:"GPA 3.9+ (weighted)",note:"School of Theater, Film, Television"},
  {c:"art",l:"std",g:"GPA 3.8+ (weighted)",note:"School of the Arts; portfolio"},
  {c:"ir",l:"std",g:"GPA 3.9+ (weighted)",note:"Political Science / International Development"},
  {c:"nurs",l:"std",g:"GPA 3.9+ (weighted)",note:"School of Nursing; direct admit"}
]},

{id:"umich",n:"密歇根大学",e:"University of Michigan",c:"Ann Arbor, MI",r:21,cat:"public",
 ll:{std:{ielts:{t:7.0,r:6.5,w:6.5,s:6.5,l:6.5},toefl:{t:100,r:23,w:23,s:23,l:23}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$57,273/yr (OOS)",currency:"USD"},living:"$14,000-18,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Feb 1 (RD), Nov 1 (EA)",note:""},
 schol:[{name:"UMich Merit Scholarships",note:"Limited for intl; Michigan Difference Award"}],
 materials:["Common App","UMich supplement","RL x1","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1450+ / ACT 33+",note:"College of Engineering or LSA"},
  {c:"eng",l:"std",g:"SAT 1450+ / ACT 33+",note:"Top-ranked engineering school"},
  {c:"bus",l:"std",g:"SAT 1460+ / ACT 33+",note:"Ross School of Business - preferred admission"},
  {c:"econ",l:"std",g:"SAT 1430+ / ACT 32+"},
  {c:"bio",l:"std",g:"SAT 1430+ / ACT 32+"},
  {c:"psych",l:"std",g:"SAT 1430+ / ACT 32+"},
  {c:"ds",l:"std",g:"SAT 1450+ / ACT 33+"},
  {c:"me",l:"std",g:"SAT 1450+ / ACT 33+"},
  {c:"math",l:"std",g:"SAT 1430+ / ACT 32+"},
  {c:"nurs",l:"std",g:"SAT 1400+ / ACT 31+",note:"School of Nursing"}
]},

{id:"usc",n:"南加州大学",e:"University of Southern California",c:"Los Angeles, CA",r:80,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$66,640/yr",currency:"USD"},living:"$20,000-24,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 15 (RD)",note:""},
 schol:[{name:"USC Trustee/Presidential Scholarship",note:"Full/half tuition merit scholarships"}],
 materials:["Common App","USC supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1460+ / ACT 33+",note:"Viterbi School of Engineering"},
  {c:"bus",l:"std",g:"SAT 1460+ / ACT 33+",note:"Marshall School of Business"},
  {c:"media",l:"std",g:"SAT 1440+ / ACT 32+",note:"Annenberg School of Communication - top ranked"},
  {c:"eng",l:"std",g:"SAT 1460+ / ACT 33+",note:"Viterbi Engineering"},
  {c:"art",l:"std",g:"SAT 1400+ / ACT 31+",note:"School of Cinematic Arts; portfolio/reel"},
  {c:"bio",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"arch",l:"std",g:"SAT 1440+ / ACT 32+",note:"School of Architecture; portfolio required"},
  {c:"econ",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"ir",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"psych",l:"std",g:"SAT 1440+ / ACT 32+"}
]},

{id:"nyu",n:"纽约大学",e:"New York University",c:"New York, NY",r:38,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$60,438/yr",currency:"USD"},living:"$22,000-28,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 5 (RD), Nov 1 (ED I), Jan 1 (ED II)",note:""},
 schol:[{name:"NYU Merit Scholarships",note:"Need-aware for intl; merit-based available"}],
 materials:["Common App/Coalition","NYU supplement","RL x1","Transcript","SAT/ACT optional"],
 p:[
  {c:"bus",l:"std",g:"SAT 1460+ / ACT 33+",note:"Stern School of Business - top ranked"},
  {c:"fin",l:"std",g:"SAT 1460+ / ACT 33+",note:"Stern Finance"},
  {c:"cs",l:"std",g:"SAT 1450+ / ACT 33+",note:"Tandon School of Engineering or CAS"},
  {c:"econ",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"media",l:"std",g:"SAT 1440+ / ACT 32+",note:"Steinhardt / Tisch Film & TV"},
  {c:"art",l:"std",g:"SAT 1400+ / ACT 31+",note:"Tisch School of the Arts; portfolio/audition"},
  {c:"ir",l:"std",g:"SAT 1440+ / ACT 32+",note:"Politics / Global Liberal Studies"},
  {c:"math",l:"std",g:"SAT 1450+ / ACT 33+",note:"Courant Institute of Mathematical Sciences"},
  {c:"nurs",l:"std",g:"SAT 1400+ / ACT 31+",note:"Rory Meyers College of Nursing"},
  {c:"psych",l:"std",g:"SAT 1440+ / ACT 32+"}
]},

{id:"gatech",n:"佐治亚理工",e:"Georgia Institute of Technology",c:"Atlanta, GA",r:85,cat:"public",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:90,r:19,w:19,s:19,l:19}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$35,378/yr (OOS)",currency:"USD"},living:"$14,000-18,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 4 (RD), Nov 1 (EA I)",note:""},
 schol:[{name:"GT Stamps Scholarship",note:"Full merit scholarship; President's Scholarship also available"}],
 materials:["Common App/Coalition","GT supplement","RL x1","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1450+ / ACT 33+",note:"College of Computing - top 5 nationally"},
  {c:"ee",l:"std",g:"SAT 1430+ / ACT 32+"},
  {c:"me",l:"std",g:"SAT 1430+ / ACT 32+",note:"Woodruff School"},
  {c:"ce",l:"std",g:"SAT 1420+ / ACT 32+"},
  {c:"eng",l:"std",g:"SAT 1430+ / ACT 32+",note:"Aerospace, BME, ChemE, IE, etc."},
  {c:"bus",l:"std",g:"SAT 1420+ / ACT 32+",note:"Scheller College of Business"},
  {c:"ds",l:"std",g:"SAT 1440+ / ACT 33+"},
  {c:"bio",l:"std",g:"SAT 1400+ / ACT 31+",note:"College of Sciences"},
  {c:"arch",l:"std",g:"SAT 1400+ / ACT 31+",note:"College of Design; portfolio helpful"},
  {c:"math",l:"std",g:"SAT 1430+ / ACT 32+"}
]},

{id:"uiuc",n:"伊利诺伊大学",e:"University of Illinois Urbana-Champaign",c:"Champaign, IL",r:64,cat:"public",
 ll:{std:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:79,r:null,w:null,s:null,l:null}},
     eng:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$38,098/yr (OOS)",currency:"USD"},living:"$12,000-16,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 5",note:"Apply to specific college"},
 schol:[{name:"UIUC Merit",note:"Limited intl scholarships; some department-specific"}],
 materials:["Common App","UIUC supplement","RL x1","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"eng",g:"SAT 1480+ / ACT 34+",note:"Grainger College of Engineering - CS top 5"},
  {c:"ee",l:"eng",g:"SAT 1440+ / ACT 33+",note:"ECE Department"},
  {c:"me",l:"eng",g:"SAT 1420+ / ACT 32+"},
  {c:"ce",l:"eng",g:"SAT 1400+ / ACT 31+"},
  {c:"bus",l:"std",g:"SAT 1400+ / ACT 31+",note:"Gies College of Business"},
  {c:"acct",l:"std",g:"SAT 1400+ / ACT 31+",note:"Gies - top accounting program"},
  {c:"econ",l:"std",g:"SAT 1360+ / ACT 30+"},
  {c:"ds",l:"eng",g:"SAT 1460+ / ACT 33+",note:"Statistics + CS interdisciplinary"},
  {c:"bio",l:"std",g:"SAT 1360+ / ACT 30+"},
  {c:"arch",l:"std",g:"SAT 1360+ / ACT 30+",note:"School of Architecture"}
]},

{id:"utaustin",n:"德克萨斯大学奥斯汀",e:"University of Texas at Austin",c:"Austin, TX",r:58,cat:"public",
 ll:{std:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:79,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$41,070/yr (OOS)",currency:"USD"},living:"$14,000-18,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Dec 1",note:"Priority deadline"},
 schol:[{name:"UT Austin International Scholarship",note:"Limited; Texas Exes Scholarship"}],
 materials:["ApplyTexas/Common App","Essays","RL","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1400+ / ACT 32+",note:"Top CS program; very competitive for intl"},
  {c:"eng",l:"std",g:"SAT 1380+ / ACT 31+",note:"Cockrell School of Engineering"},
  {c:"bus",l:"std",g:"SAT 1380+ / ACT 31+",note:"McCombs School of Business"},
  {c:"econ",l:"std",g:"SAT 1350+ / ACT 30+"},
  {c:"bio",l:"std",g:"SAT 1350+ / ACT 30+"},
  {c:"media",l:"std",g:"SAT 1350+ / ACT 30+",note:"Moody College of Communication"},
  {c:"arch",l:"std",g:"SAT 1350+ / ACT 30+",note:"School of Architecture"},
  {c:"math",l:"std",g:"SAT 1380+ / ACT 31+"},
  {c:"ir",l:"std",g:"SAT 1350+ / ACT 30+",note:"LBJ School pathway / Government"}
]},

{id:"uw",n:"华盛顿大学",e:"University of Washington",c:"Seattle, WA",r:63,cat:"public",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:76,r:17,w:17,s:17,l:17}},
     rec:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:92,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y",note:"Min 76 but competitive admits ~92+"},
 fee:{ug:"$41,997/yr (OOS)",currency:"USD"},living:"$16,000-20,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Nov 15",note:""},
 schol:[{name:"UW Scholarships",note:"Limited for intl; departmental scholarships available"}],
 materials:["Coalition App","Essays","Transcript","SAT/ACT not required"],
 p:[
  {c:"cs",l:"rec",g:"GPA 3.9+",note:"Paul G. Allen School; direct admit or competitive entry"},
  {c:"eng",l:"rec",g:"GPA 3.8+",note:"College of Engineering"},
  {c:"bio",l:"std",g:"GPA 3.7+"},
  {c:"bus",l:"rec",g:"GPA 3.8+",note:"Foster School of Business; apply as sophomore"},
  {c:"econ",l:"std",g:"GPA 3.7+"},
  {c:"psych",l:"std",g:"GPA 3.7+"},
  {c:"math",l:"std",g:"GPA 3.7+"},
  {c:"nurs",l:"std",g:"GPA 3.8+",note:"School of Nursing; highly competitive"},
  {c:"env",l:"std",g:"GPA 3.7+",note:"College of the Environment"}
]},

{id:"purdue",n:"普渡大学",e:"Purdue University",c:"West Lafayette, IN",r:100,cat:"public",
 ll:{std:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:80,r:20,w:20,s:20,l:20}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$31,104/yr (OOS)",currency:"USD"},living:"$12,000-15,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 15 (RD), Nov 1 (EA)",note:"Apply to specific college"},
 schol:[{name:"Purdue Merit Scholarships",note:"Competitive merit awards for intl students"}],
 materials:["Common App/Purdue App","Essay","RL x1","Transcript","SAT/ACT recommended"],
 p:[
  {c:"cs",l:"std",g:"SAT 1380+ / ACT 31+",note:"Top 10 CS program nationally"},
  {c:"eng",l:"std",g:"SAT 1360+ / ACT 30+",note:"College of Engineering - top ranked"},
  {c:"ee",l:"std",g:"SAT 1360+ / ACT 30+"},
  {c:"me",l:"std",g:"SAT 1360+ / ACT 30+"},
  {c:"ce",l:"std",g:"SAT 1340+ / ACT 29+"},
  {c:"bus",l:"std",g:"SAT 1340+ / ACT 29+",note:"Daniels School of Business"},
  {c:"bio",l:"std",g:"SAT 1320+ / ACT 28+"},
  {c:"math",l:"std",g:"SAT 1340+ / ACT 29+"},
  {c:"pharm",l:"std",g:"SAT 1360+ / ACT 30+",note:"College of Pharmacy; direct admit 6-yr PharmD"},
  {c:"ds",l:"std",g:"SAT 1380+ / ACT 31+",note:"Data Science interdisciplinary"}
]},

{id:"osu",n:"俄亥俄州立大学",e:"Ohio State University",c:"Columbus, OH",r:140,cat:"public",
 ll:{std:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:79,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$36,722/yr (OOS)",currency:"USD"},living:"$12,000-16,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Feb 1 (RD), Nov 1 (EA)",note:""},
 schol:[{name:"OSU Merit Awards",note:"Maximus, Provost, Trustees scholarships for high achievers"}],
 materials:["Common App/OSU App","Essays","Transcript","SAT/ACT recommended"],
 p:[
  {c:"cs",l:"std",g:"SAT 1350+ / ACT 30+"},
  {c:"eng",l:"std",g:"SAT 1350+ / ACT 30+",note:"College of Engineering"},
  {c:"bus",l:"std",g:"SAT 1340+ / ACT 29+",note:"Fisher College of Business"},
  {c:"bio",l:"std",g:"SAT 1300+ / ACT 28+"},
  {c:"nurs",l:"std",g:"SAT 1320+ / ACT 28+"},
  {c:"econ",l:"std",g:"SAT 1300+ / ACT 28+"},
  {c:"psych",l:"std",g:"SAT 1300+ / ACT 28+"},
  {c:"med",l:"std",g:"SAT 1400+ / ACT 31+",note:"Pre-med track; no direct-entry MD"}
]},

{id:"psu",n:"宾州州立大学",e:"Pennsylvania State University",c:"University Park, PA",r:89,cat:"public",
 ll:{std:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:80,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$38,824/yr (OOS)",currency:"USD"},living:"$13,000-17,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Rolling (priority Nov 30)",note:""},
 schol:[{name:"Penn State Merit",note:"Limited intl awards; Schreyer Honors College"}],
 materials:["Common App/PSU App","Essay","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1340+ / ACT 30+"},
  {c:"eng",l:"std",g:"SAT 1340+ / ACT 30+",note:"Large engineering program"},
  {c:"bus",l:"std",g:"SAT 1320+ / ACT 29+",note:"Smeal College of Business"},
  {c:"econ",l:"std",g:"SAT 1300+ / ACT 28+"},
  {c:"bio",l:"std",g:"SAT 1300+ / ACT 28+"},
  {c:"nurs",l:"std",g:"SAT 1320+ / ACT 29+"},
  {c:"arch",l:"std",g:"SAT 1300+ / ACT 28+",note:"Stuckeman School of Architecture"},
  {c:"media",l:"std",g:"SAT 1300+ / ACT 28+",note:"Bellisario College of Communications"}
]},

{id:"uwmadison",n:"威斯康星大学麦迪逊",e:"University of Wisconsin-Madison",c:"Madison, WI",r:83,cat:"public",
 ll:{std:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:80,r:null,w:null,s:null,l:null}},
     rec:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:95,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$39,427/yr (OOS)",currency:"USD"},living:"$13,000-17,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Feb 1",note:"Priority deadline Nov 1"},
 schol:[{name:"UW-Madison Merit",note:"Chancellor's Scholarship; limited for intl"}],
 materials:["Common App/UW System","Essays","RL x1","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"rec",g:"SAT 1380+ / ACT 31+",note:"Top 10 public CS"},
  {c:"eng",l:"rec",g:"SAT 1360+ / ACT 30+",note:"College of Engineering"},
  {c:"bus",l:"std",g:"SAT 1340+ / ACT 30+",note:"Wisconsin School of Business"},
  {c:"bio",l:"std",g:"SAT 1320+ / ACT 28+"},
  {c:"econ",l:"std",g:"SAT 1320+ / ACT 28+"},
  {c:"ds",l:"rec",g:"SAT 1380+ / ACT 31+"},
  {c:"math",l:"std",g:"SAT 1340+ / ACT 29+"},
  {c:"nurs",l:"std",g:"SAT 1340+ / ACT 29+",note:"School of Nursing; direct admit"},
  {c:"env",l:"std",g:"SAT 1300+ / ACT 28+",note:"Nelson Institute"}
]},

{id:"uf",n:"佛罗里达大学",e:"University of Florida",c:"Gainesville, FL",r:168,cat:"public",
 ll:{std:{ielts:{t:6.0,r:null,w:null,s:null,l:null},toefl:{t:80,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$28,658/yr (OOS)",currency:"USD"},living:"$12,000-15,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Nov 1 (priority), Mar 1",note:""},
 schol:[{name:"UF Scholarships",note:"Limited for intl; Machen Florida Opportunity Scholars"}],
 materials:["Common App/UF App","Essays","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1350+ / ACT 30+",note:"Herbert Wertheim College of Engineering"},
  {c:"eng",l:"std",g:"SAT 1340+ / ACT 30+"},
  {c:"bus",l:"std",g:"SAT 1320+ / ACT 29+",note:"Warrington College of Business"},
  {c:"bio",l:"std",g:"SAT 1300+ / ACT 28+"},
  {c:"econ",l:"std",g:"SAT 1300+ / ACT 28+"},
  {c:"med",l:"std",g:"SAT 1400+ / ACT 31+",note:"Pre-med; UF College of Medicine"},
  {c:"nurs",l:"std",g:"SAT 1320+ / ACT 29+"},
  {c:"pharm",l:"std",g:"SAT 1340+ / ACT 29+",note:"Direct admit to PharmD"}
]},

{id:"uva",n:"弗吉尼亚大学",e:"University of Virginia",c:"Charlottesville, VA",r:113,cat:"public",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$56,837/yr (OOS)",currency:"USD"},living:"$14,000-18,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 5 (RD), Nov 1 (EA)",note:""},
 schol:[{name:"Jefferson Scholarship",note:"Full merit scholarship; most prestigious at UVA"}],
 materials:["Common App/Coalition","UVA supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1420+ / ACT 32+",note:"School of Engineering"},
  {c:"eng",l:"std",g:"SAT 1420+ / ACT 32+"},
  {c:"bus",l:"std",g:"SAT 1430+ / ACT 32+",note:"McIntire School of Commerce (apply as 2nd year)"},
  {c:"econ",l:"std",g:"SAT 1400+ / ACT 31+"},
  {c:"bio",l:"std",g:"SAT 1400+ / ACT 31+"},
  {c:"psych",l:"std",g:"SAT 1400+ / ACT 31+"},
  {c:"hist",l:"std",g:"SAT 1400+ / ACT 31+"},
  {c:"ir",l:"std",g:"SAT 1420+ / ACT 32+",note:"Batten School of Leadership / Politics"},
  {c:"arch",l:"std",g:"SAT 1380+ / ACT 31+",note:"School of Architecture"}
]},

{id:"unc",n:"北卡教堂山",e:"University of North Carolina at Chapel Hill",c:"Chapel Hill, NC",r:53,cat:"public",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$39,338/yr (OOS)",currency:"USD"},living:"$13,000-17,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 15 (RD), Oct 15 (EA)",note:""},
 schol:[{name:"Morehead-Cain Scholarship",note:"Full merit scholarship - oldest in US"}],
 materials:["Common App/Coalition","Short answer essays","RL x1","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1380+ / ACT 31+"},
  {c:"bus",l:"std",g:"SAT 1400+ / ACT 31+",note:"Kenan-Flagler; apply sophomore year"},
  {c:"bio",l:"std",g:"SAT 1360+ / ACT 30+"},
  {c:"econ",l:"std",g:"SAT 1360+ / ACT 30+"},
  {c:"media",l:"std",g:"SAT 1360+ / ACT 30+",note:"Hussman School of Journalism"},
  {c:"psych",l:"std",g:"SAT 1360+ / ACT 30+"},
  {c:"nurs",l:"std",g:"SAT 1360+ / ACT 30+",note:"School of Nursing; direct-admit BSN"},
  {c:"ph",l:"std",g:"SAT 1380+ / ACT 31+",note:"Gillings School of Public Health"}
]},

{id:"emory",n:"埃默里大学",e:"Emory University",c:"Atlanta, GA",r:126,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$60,774/yr",currency:"USD"},living:"$16,000-20,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 1 (RD), Nov 1 (ED I)",note:""},
 schol:[{name:"Emory Scholars",note:"Full merit scholarships; multiple tracks"}],
 materials:["Common App/Coalition","Emory supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"bus",l:"std",g:"SAT 1440+ / ACT 32+",note:"Goizueta Business School"},
  {c:"bio",l:"std",g:"SAT 1440+ / ACT 32+",note:"Strong pre-med; Emory Hospital"},
  {c:"cs",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"econ",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"psych",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"nurs",l:"std",g:"SAT 1420+ / ACT 31+",note:"Nell Hodgson Woodruff School of Nursing"},
  {c:"hist",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"med",l:"std",g:"SAT 1460+ / ACT 33+",note:"Pre-med; Emory School of Medicine"}
]},

{id:"notredame",n:"圣母大学",e:"University of Notre Dame",c:"Notre Dame, IN",r:176,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$62,693/yr",currency:"USD"},living:"$17,000-21,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 1 (RD), Nov 1 (REA)",note:""},
 schol:[{name:"Notre Dame Scholarship",note:"Need-based; meets 100% demonstrated need"}],
 materials:["Common App","Notre Dame supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"bus",l:"std",g:"SAT 1440+ / ACT 33+",note:"Mendoza College of Business - top ranked"},
  {c:"cs",l:"std",g:"SAT 1440+ / ACT 33+",note:"College of Engineering"},
  {c:"eng",l:"std",g:"SAT 1440+ / ACT 33+"},
  {c:"econ",l:"std",g:"SAT 1440+ / ACT 33+"},
  {c:"ir",l:"std",g:"SAT 1440+ / ACT 33+",note:"Keough School; Political Science"},
  {c:"bio",l:"std",g:"SAT 1440+ / ACT 33+"},
  {c:"psych",l:"std",g:"SAT 1440+ / ACT 33+"},
  {c:"arch",l:"std",g:"SAT 1420+ / ACT 32+",note:"5-year B.Arch; portfolio required"}
]},

{id:"tufts",n:"塔夫茨大学",e:"Tufts University",c:"Medford, MA",r:262,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:100,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$65,222/yr",currency:"USD"},living:"$18,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 3 (RD), Nov 1 (ED I)",note:""},
 schol:[{name:"Tufts Financial Aid",note:"Need-aware for intl; meets 100% demonstrated need"}],
 materials:["Common App/Coalition","Tufts supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"ir",l:"std",g:"SAT 1440+ / ACT 32+",note:"Fletcher School pathway; strong IR/politics"},
  {c:"cs",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"eng",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"bio",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"econ",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"psych",l:"std",g:"SAT 1440+ / ACT 32+"},
  {c:"env",l:"std",g:"SAT 1420+ / ACT 31+"},
  {c:"med",l:"std",g:"SAT 1460+ / ACT 33+",note:"Pre-med track; Tufts Medical Center"}
]},

{id:"bu",n:"波士顿大学",e:"Boston University",c:"Boston, MA",r:87,cat:"private",
 ll:{std:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:90,r:20,w:22,s:20,l:21}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$63,798/yr",currency:"USD"},living:"$18,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 4 (RD), Nov 1 (ED I)",note:""},
 schol:[{name:"BU Presidential Scholarship",note:"Full tuition merit; Trustee Scholarship also"}],
 materials:["Common App","BU supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"std",g:"SAT 1400+ / ACT 32+",note:"College of Arts & Sciences or Engineering"},
  {c:"eng",l:"std",g:"SAT 1400+ / ACT 32+",note:"College of Engineering"},
  {c:"bus",l:"std",g:"SAT 1400+ / ACT 32+",note:"Questrom School of Business"},
  {c:"media",l:"std",g:"SAT 1380+ / ACT 31+",note:"College of Communication"},
  {c:"bio",l:"std",g:"SAT 1380+ / ACT 31+"},
  {c:"econ",l:"std",g:"SAT 1380+ / ACT 31+"},
  {c:"ir",l:"std",g:"SAT 1380+ / ACT 31+",note:"Pardee School of Global Studies"},
  {c:"psych",l:"std",g:"SAT 1380+ / ACT 31+"},
  {c:"nurs",l:"std",g:"SAT 1360+ / ACT 30+"},
  {c:"edu",l:"std",g:"SAT 1340+ / ACT 30+",note:"Wheelock College of Education"}
]},

{id:"neu",n:"东北大学",e:"Northeastern University",c:"Boston, MA",r:326,cat:"private",
 ll:{std:{ielts:{t:6.5,r:null,w:null,s:null,l:null},toefl:{t:92,r:null,w:null,s:null,l:null}},
     rec:{ielts:{t:7.0,r:null,w:null,s:null,l:null},toefl:{t:99,r:null,w:null,s:null,l:null}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"$60,192/yr",currency:"USD"},living:"$18,000-22,000/yr",
 visa:{psw:"OPT 12mo + STEM 24mo",note:"F-1"},
 ddl:{fall:"Jan 1 (RD), Nov 1 (ED/EA)",note:""},
 schol:[{name:"NEU Dean's Scholarship",note:"Merit-based; up to full tuition"}],
 materials:["Common App","NEU supplement","RL x2","Transcript","SAT/ACT optional"],
 p:[
  {c:"cs",l:"rec",g:"SAT 1430+ / ACT 33+",note:"Khoury College of Computer Sciences; co-op program"},
  {c:"eng",l:"rec",g:"SAT 1420+ / ACT 32+",note:"Co-op integrated"},
  {c:"bus",l:"std",g:"SAT 1400+ / ACT 31+",note:"D'Amore-McKim School of Business"},
  {c:"ds",l:"rec",g:"SAT 1430+ / ACT 33+",note:"Data Science + co-op"},
  {c:"bio",l:"std",g:"SAT 1380+ / ACT 31+"},
  {c:"econ",l:"std",g:"SAT 1380+ / ACT 31+"},
  {c:"ir",l:"std",g:"SAT 1380+ / ACT 31+",note:"International Affairs"},
  {c:"psych",l:"std",g:"SAT 1380+ / ACT 31+"},
  {c:"nurs",l:"std",g:"SAT 1380+ / ACT 31+",note:"Bouvé College of Health Sciences"},
  {c:"pharm",l:"std",g:"SAT 1380+ / ACT 31+",note:"6-year PharmD co-op"}
]}

];
COMPASS_DATA.usa = D;
})();
