// data-mo.js - Macau Universities - Undergraduate Programs Only
// v4.0 - All programs are bachelor's level
COMPASS_DATA.mo = [
{id:"um",n:"澳门大学",e:"University of Macau",c:"Macau",r:245,cat:"public",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:79,r:19,w:19,s:19,l:19}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"MOP 86,400/yr",currency:"MOP"},
 living:"MOP 60,000-80,000/yr",
 the:null,
 visa:{psw:"0",note:"No post-study work visa; need employer sponsor"},
 ddl:{fall:"Jan-Mar (mainland); May-Jun (others)"},
 schol:["UM Macao Scholarship (full/half tuition)","UM Academic Excellence Award"],
 materials:["Transcripts","Personal statement","English proficiency test score","Interview (some)"],
 p:[
  {c:"cs",l:"std",g:"高考一本线上 / IB 28+ / A-Level BBB",note:"科技学院计算机科学理学士 / FST Computer Science BSc"},
  {c:"ee",l:"std",g:"高考一本线上 / IB 28+ / BBB",note:"电机及电脑工程 / Electrical & Computer Engineering"},
  {c:"ce",l:"std",g:"高考一本线上 / IB 28+ / BBB",note:"土木工程 / Civil Engineering"},
  {c:"math",l:"std",g:"高考一本线上 / IB 28+ / BBB"},
  {c:"bio",l:"std",g:"高考一本线上 / IB 28+ / BBB",note:"生物医学 / Biomedical Sciences"},
  {c:"bus",l:"std",g:"高考一本线上 / IB 28+ / BBB",note:"工商管理学院 / Faculty of Business Administration"},
  {c:"fin",l:"std",g:"高考一本线上 / IB 28+ / BBB",note:"工商管理学士 / BBA Finance"},
  {c:"acct",l:"std",g:"高考一本线上 / IB 28+ / BBB"},
  {c:"law",l:"std",g:"高考一本线上 / IB 30+ / AAB",note:"法学院-葡萄牙法与中国法 / Faculty of Law - Portuguese & Chinese law"},
  {c:"edu",l:"std",g:"高考一本线上 / IB 28+ / BBB",note:"教育学院 / Faculty of Education"},
  {c:"media",l:"std",g:"高考一本线上 / IB 28+ / BBB",note:"传播学文学士 / Communication BA"},
  {c:"psych",l:"std",g:"高考一本线上 / IB 28+ / BBB"}
]},

{id:"must",n:"澳门科技大学",e:"Macau University of Science and Technology",c:"Macau",r:520,cat:"private",
 ll:{std:{ielts:{t:6.0,r:5.5,w:5.5,s:5.5,l:5.5},toefl:{t:79,r:19,w:19,s:19,l:19}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"MOP 80,000-120,000/yr",currency:"MOP"},
 living:"MOP 60,000-80,000/yr",
 the:null,
 visa:{psw:"0",note:"No post-study work visa; need employer sponsor"},
 ddl:{fall:"Jan-Mar (mainland); year-round others"},
 schol:["MUST Scholarship for Outstanding Students","Merit-based tuition reduction available"],
 materials:["Transcripts","Personal statement","English proficiency test score"],
 p:[
  {c:"cs",l:"std",g:"高考二本线上 / IB 26+ / BCC",note:"资讯科技学院 / Faculty of Information Technology"},
  {c:"bus",l:"std",g:"高考二本线上 / IB 26+ / BCC",note:"商学院 / School of Business"},
  {c:"fin",l:"std",g:"高考二本线上 / IB 26+ / BCC"},
  {c:"med",l:"std",g:"高考一本线上 / IB 30+ / AAB",note:"医学院 / Faculty of Medicine - MBBS"},
  {c:"pharm",l:"std",g:"高考一本线上 / IB 28+ / BBB",note:"药学院 / Faculty of Pharmacy"},
  {c:"media",l:"std",g:"高考二本线上 / IB 26+ / BCC",note:"人文艺术学院传播学 / School of Communication"},
  {c:"art",l:"std",g:"高考二本线上 / Portfolio",note:"人文艺术学院艺术学 / School of Art"},
  {c:"law",l:"std",g:"高考二本线上 / IB 28+ / BBB"}
]},

{id:"cityu_mo",n:"澳门城市大学",e:"City University of Macau",c:"Macau",r:null,cat:"private",
 ll:{std:{ielts:{t:5.5,r:5,w:5,s:5,l:5},toefl:{t:72,r:17,w:17,s:17,l:17}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"MOP 50,000-70,000/yr",currency:"MOP"},
 living:"MOP 60,000-80,000/yr",
 the:null,
 visa:{psw:"0",note:"No post-study work visa; need employer sponsor"},
 ddl:{fall:"Jan-Jul"},
 schol:["City U Scholarship for mainland and international students"],
 materials:["Transcripts","Personal statement","English proficiency test score"],
 p:[
  {c:"bus",l:"std",g:"高考二本线上 / IB 24+ / CCC"},
  {c:"fin",l:"std",g:"高考二本线上 / IB 24+ / CCC"},
  {c:"edu",l:"std",g:"高考二本线上 / IB 24+ / CCC"},
  {c:"art",l:"std",g:"高考二本线上 / Portfolio",note:"设计类课程 / Design programmes"},
  {c:"media",l:"std",g:"高考二本线上 / IB 24+ / CCC"}
]},

{id:"mpu",n:"澳门理工大学",e:"Macao Polytechnic University",c:"Macau",r:null,cat:"public",
 ll:{std:{ielts:{t:5.5,r:5,w:5,s:5,l:5},toefl:{t:72,r:17,w:17,s:17,l:17}}},
 pol:{nt:"pending",mb:false,v:"2y"},
 fee:{ug:"MOP 32,000-50,000/yr",currency:"MOP"},
 living:"MOP 60,000-80,000/yr",
 the:null,
 visa:{psw:"0",note:"No post-study work visa; need employer sponsor"},
 ddl:{fall:"Jan-May"},
 schol:["MPU Scholarship; government-funded tuition subsidy"],
 materials:["Transcripts","Personal statement","English proficiency test score"],
 p:[
  {c:"cs",l:"std",g:"高考二本线上 / IB 24+ / CCC",note:"计算机课程 / Computing programme"},
  {c:"bus",l:"std",g:"高考二本线上 / IB 24+ / CCC"},
  {c:"edu",l:"std",g:"高考二本线上 / IB 24+ / CCC"},
  {c:"media",l:"std",g:"高考二本线上 / IB 24+ / CCC",note:"艺术与传播 / Arts and communication"},
  {c:"art",l:"std",g:"高考二本线上 / Portfolio",note:"视觉艺术与设计 / Visual arts & design"}
]}
];
